// Code generated by ent, DO NOT EDIT.

package answerevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/abhisek/mathiz/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLTE(FieldID, id))
}

// Sequence applies equality check predicate on the "sequence" field. It's identical to SequenceEQ.
func Sequence(v int64) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldSequence, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldTimestamp, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldSessionID, v))
}

// SkillID applies equality check predicate on the "skill_id" field. It's identical to SkillIDEQ.
func SkillID(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldSkillID, v))
}

// Tier applies equality check predicate on the "tier" field. It's identical to TierEQ.
func Tier(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldTier, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldCategory, v))
}

// QuestionText applies equality check predicate on the "question_text" field. It's identical to QuestionTextEQ.
func QuestionText(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldQuestionText, v))
}

// CorrectAnswer applies equality check predicate on the "correct_answer" field. It's identical to CorrectAnswerEQ.
func CorrectAnswer(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldCorrectAnswer, v))
}

// LearnerAnswer applies equality check predicate on the "learner_answer" field. It's identical to LearnerAnswerEQ.
func LearnerAnswer(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldLearnerAnswer, v))
}

// Correct applies equality check predicate on the "correct" field. It's identical to CorrectEQ.
func Correct(v bool) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldCorrect, v))
}

// TimeMs applies equality check predicate on the "time_ms" field. It's identical to TimeMsEQ.
func TimeMs(v int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldTimeMs, v))
}

// AnswerFormat applies equality check predicate on the "answer_format" field. It's identical to AnswerFormatEQ.
func AnswerFormat(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldAnswerFormat, v))
}

// SequenceEQ applies the EQ predicate on the "sequence" field.
func SequenceEQ(v int64) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldSequence, v))
}

// SequenceNEQ applies the NEQ predicate on the "sequence" field.
func SequenceNEQ(v int64) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNEQ(FieldSequence, v))
}

// SequenceIn applies the In predicate on the "sequence" field.
func SequenceIn(vs ...int64) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldIn(FieldSequence, vs...))
}

// SequenceNotIn applies the NotIn predicate on the "sequence" field.
func SequenceNotIn(vs ...int64) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNotIn(FieldSequence, vs...))
}

// SequenceGT applies the GT predicate on the "sequence" field.
func SequenceGT(v int64) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGT(FieldSequence, v))
}

// SequenceGTE applies the GTE predicate on the "sequence" field.
func SequenceGTE(v int64) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGTE(FieldSequence, v))
}

// SequenceLT applies the LT predicate on the "sequence" field.
func SequenceLT(v int64) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLT(FieldSequence, v))
}

// SequenceLTE applies the LTE predicate on the "sequence" field.
func SequenceLTE(v int64) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLTE(FieldSequence, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLTE(FieldTimestamp, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContainsFold(FieldSessionID, v))
}

// SkillIDEQ applies the EQ predicate on the "skill_id" field.
func SkillIDEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldSkillID, v))
}

// SkillIDNEQ applies the NEQ predicate on the "skill_id" field.
func SkillIDNEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNEQ(FieldSkillID, v))
}

// SkillIDIn applies the In predicate on the "skill_id" field.
func SkillIDIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldIn(FieldSkillID, vs...))
}

// SkillIDNotIn applies the NotIn predicate on the "skill_id" field.
func SkillIDNotIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNotIn(FieldSkillID, vs...))
}

// SkillIDGT applies the GT predicate on the "skill_id" field.
func SkillIDGT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGT(FieldSkillID, v))
}

// SkillIDGTE applies the GTE predicate on the "skill_id" field.
func SkillIDGTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGTE(FieldSkillID, v))
}

// SkillIDLT applies the LT predicate on the "skill_id" field.
func SkillIDLT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLT(FieldSkillID, v))
}

// SkillIDLTE applies the LTE predicate on the "skill_id" field.
func SkillIDLTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLTE(FieldSkillID, v))
}

// SkillIDContains applies the Contains predicate on the "skill_id" field.
func SkillIDContains(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContains(FieldSkillID, v))
}

// SkillIDHasPrefix applies the HasPrefix predicate on the "skill_id" field.
func SkillIDHasPrefix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasPrefix(FieldSkillID, v))
}

// SkillIDHasSuffix applies the HasSuffix predicate on the "skill_id" field.
func SkillIDHasSuffix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasSuffix(FieldSkillID, v))
}

// SkillIDEqualFold applies the EqualFold predicate on the "skill_id" field.
func SkillIDEqualFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEqualFold(FieldSkillID, v))
}

// SkillIDContainsFold applies the ContainsFold predicate on the "skill_id" field.
func SkillIDContainsFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContainsFold(FieldSkillID, v))
}

// TierEQ applies the EQ predicate on the "tier" field.
func TierEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldTier, v))
}

// TierNEQ applies the NEQ predicate on the "tier" field.
func TierNEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNEQ(FieldTier, v))
}

// TierIn applies the In predicate on the "tier" field.
func TierIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldIn(FieldTier, vs...))
}

// TierNotIn applies the NotIn predicate on the "tier" field.
func TierNotIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNotIn(FieldTier, vs...))
}

// TierGT applies the GT predicate on the "tier" field.
func TierGT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGT(FieldTier, v))
}

// TierGTE applies the GTE predicate on the "tier" field.
func TierGTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGTE(FieldTier, v))
}

// TierLT applies the LT predicate on the "tier" field.
func TierLT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLT(FieldTier, v))
}

// TierLTE applies the LTE predicate on the "tier" field.
func TierLTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLTE(FieldTier, v))
}

// TierContains applies the Contains predicate on the "tier" field.
func TierContains(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContains(FieldTier, v))
}

// TierHasPrefix applies the HasPrefix predicate on the "tier" field.
func TierHasPrefix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasPrefix(FieldTier, v))
}

// TierHasSuffix applies the HasSuffix predicate on the "tier" field.
func TierHasSuffix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasSuffix(FieldTier, v))
}

// TierEqualFold applies the EqualFold predicate on the "tier" field.
func TierEqualFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEqualFold(FieldTier, v))
}

// TierContainsFold applies the ContainsFold predicate on the "tier" field.
func TierContainsFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContainsFold(FieldTier, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContainsFold(FieldCategory, v))
}

// QuestionTextEQ applies the EQ predicate on the "question_text" field.
func QuestionTextEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldQuestionText, v))
}

// QuestionTextNEQ applies the NEQ predicate on the "question_text" field.
func QuestionTextNEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNEQ(FieldQuestionText, v))
}

// QuestionTextIn applies the In predicate on the "question_text" field.
func QuestionTextIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldIn(FieldQuestionText, vs...))
}

// QuestionTextNotIn applies the NotIn predicate on the "question_text" field.
func QuestionTextNotIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNotIn(FieldQuestionText, vs...))
}

// QuestionTextGT applies the GT predicate on the "question_text" field.
func QuestionTextGT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGT(FieldQuestionText, v))
}

// QuestionTextGTE applies the GTE predicate on the "question_text" field.
func QuestionTextGTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGTE(FieldQuestionText, v))
}

// QuestionTextLT applies the LT predicate on the "question_text" field.
func QuestionTextLT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLT(FieldQuestionText, v))
}

// QuestionTextLTE applies the LTE predicate on the "question_text" field.
func QuestionTextLTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLTE(FieldQuestionText, v))
}

// QuestionTextContains applies the Contains predicate on the "question_text" field.
func QuestionTextContains(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContains(FieldQuestionText, v))
}

// QuestionTextHasPrefix applies the HasPrefix predicate on the "question_text" field.
func QuestionTextHasPrefix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasPrefix(FieldQuestionText, v))
}

// QuestionTextHasSuffix applies the HasSuffix predicate on the "question_text" field.
func QuestionTextHasSuffix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasSuffix(FieldQuestionText, v))
}

// QuestionTextEqualFold applies the EqualFold predicate on the "question_text" field.
func QuestionTextEqualFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEqualFold(FieldQuestionText, v))
}

// QuestionTextContainsFold applies the ContainsFold predicate on the "question_text" field.
func QuestionTextContainsFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContainsFold(FieldQuestionText, v))
}

// CorrectAnswerEQ applies the EQ predicate on the "correct_answer" field.
func CorrectAnswerEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldCorrectAnswer, v))
}

// CorrectAnswerNEQ applies the NEQ predicate on the "correct_answer" field.
func CorrectAnswerNEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNEQ(FieldCorrectAnswer, v))
}

// CorrectAnswerIn applies the In predicate on the "correct_answer" field.
func CorrectAnswerIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldIn(FieldCorrectAnswer, vs...))
}

// CorrectAnswerNotIn applies the NotIn predicate on the "correct_answer" field.
func CorrectAnswerNotIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNotIn(FieldCorrectAnswer, vs...))
}

// CorrectAnswerGT applies the GT predicate on the "correct_answer" field.
func CorrectAnswerGT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGT(FieldCorrectAnswer, v))
}

// CorrectAnswerGTE applies the GTE predicate on the "correct_answer" field.
func CorrectAnswerGTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGTE(FieldCorrectAnswer, v))
}

// CorrectAnswerLT applies the LT predicate on the "correct_answer" field.
func CorrectAnswerLT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLT(FieldCorrectAnswer, v))
}

// CorrectAnswerLTE applies the LTE predicate on the "correct_answer" field.
func CorrectAnswerLTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLTE(FieldCorrectAnswer, v))
}

// CorrectAnswerContains applies the Contains predicate on the "correct_answer" field.
func CorrectAnswerContains(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContains(FieldCorrectAnswer, v))
}

// CorrectAnswerHasPrefix applies the HasPrefix predicate on the "correct_answer" field.
func CorrectAnswerHasPrefix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasPrefix(FieldCorrectAnswer, v))
}

// CorrectAnswerHasSuffix applies the HasSuffix predicate on the "correct_answer" field.
func CorrectAnswerHasSuffix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasSuffix(FieldCorrectAnswer, v))
}

// CorrectAnswerEqualFold applies the EqualFold predicate on the "correct_answer" field.
func CorrectAnswerEqualFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEqualFold(FieldCorrectAnswer, v))
}

// CorrectAnswerContainsFold applies the ContainsFold predicate on the "correct_answer" field.
func CorrectAnswerContainsFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContainsFold(FieldCorrectAnswer, v))
}

// LearnerAnswerEQ applies the EQ predicate on the "learner_answer" field.
func LearnerAnswerEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldLearnerAnswer, v))
}

// LearnerAnswerNEQ applies the NEQ predicate on the "learner_answer" field.
func LearnerAnswerNEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNEQ(FieldLearnerAnswer, v))
}

// LearnerAnswerIn applies the In predicate on the "learner_answer" field.
func LearnerAnswerIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldIn(FieldLearnerAnswer, vs...))
}

// LearnerAnswerNotIn applies the NotIn predicate on the "learner_answer" field.
func LearnerAnswerNotIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNotIn(FieldLearnerAnswer, vs...))
}

// LearnerAnswerGT applies the GT predicate on the "learner_answer" field.
func LearnerAnswerGT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGT(FieldLearnerAnswer, v))
}

// LearnerAnswerGTE applies the GTE predicate on the "learner_answer" field.
func LearnerAnswerGTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGTE(FieldLearnerAnswer, v))
}

// LearnerAnswerLT applies the LT predicate on the "learner_answer" field.
func LearnerAnswerLT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLT(FieldLearnerAnswer, v))
}

// LearnerAnswerLTE applies the LTE predicate on the "learner_answer" field.
func LearnerAnswerLTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLTE(FieldLearnerAnswer, v))
}

// LearnerAnswerContains applies the Contains predicate on the "learner_answer" field.
func LearnerAnswerContains(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContains(FieldLearnerAnswer, v))
}

// LearnerAnswerHasPrefix applies the HasPrefix predicate on the "learner_answer" field.
func LearnerAnswerHasPrefix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasPrefix(FieldLearnerAnswer, v))
}

// LearnerAnswerHasSuffix applies the HasSuffix predicate on the "learner_answer" field.
func LearnerAnswerHasSuffix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasSuffix(FieldLearnerAnswer, v))
}

// LearnerAnswerEqualFold applies the EqualFold predicate on the "learner_answer" field.
func LearnerAnswerEqualFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEqualFold(FieldLearnerAnswer, v))
}

// LearnerAnswerContainsFold applies the ContainsFold predicate on the "learner_answer" field.
func LearnerAnswerContainsFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContainsFold(FieldLearnerAnswer, v))
}

// CorrectEQ applies the EQ predicate on the "correct" field.
func CorrectEQ(v bool) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldCorrect, v))
}

// CorrectNEQ applies the NEQ predicate on the "correct" field.
func CorrectNEQ(v bool) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNEQ(FieldCorrect, v))
}

// TimeMsEQ applies the EQ predicate on the "time_ms" field.
func TimeMsEQ(v int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldTimeMs, v))
}

// TimeMsNEQ applies the NEQ predicate on the "time_ms" field.
func TimeMsNEQ(v int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNEQ(FieldTimeMs, v))
}

// TimeMsIn applies the In predicate on the "time_ms" field.
func TimeMsIn(vs ...int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldIn(FieldTimeMs, vs...))
}

// TimeMsNotIn applies the NotIn predicate on the "time_ms" field.
func TimeMsNotIn(vs ...int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNotIn(FieldTimeMs, vs...))
}

// TimeMsGT applies the GT predicate on the "time_ms" field.
func TimeMsGT(v int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGT(FieldTimeMs, v))
}

// TimeMsGTE applies the GTE predicate on the "time_ms" field.
func TimeMsGTE(v int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGTE(FieldTimeMs, v))
}

// TimeMsLT applies the LT predicate on the "time_ms" field.
func TimeMsLT(v int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLT(FieldTimeMs, v))
}

// TimeMsLTE applies the LTE predicate on the "time_ms" field.
func TimeMsLTE(v int) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLTE(FieldTimeMs, v))
}

// AnswerFormatEQ applies the EQ predicate on the "answer_format" field.
func AnswerFormatEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEQ(FieldAnswerFormat, v))
}

// AnswerFormatNEQ applies the NEQ predicate on the "answer_format" field.
func AnswerFormatNEQ(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNEQ(FieldAnswerFormat, v))
}

// AnswerFormatIn applies the In predicate on the "answer_format" field.
func AnswerFormatIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldIn(FieldAnswerFormat, vs...))
}

// AnswerFormatNotIn applies the NotIn predicate on the "answer_format" field.
func AnswerFormatNotIn(vs ...string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldNotIn(FieldAnswerFormat, vs...))
}

// AnswerFormatGT applies the GT predicate on the "answer_format" field.
func AnswerFormatGT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGT(FieldAnswerFormat, v))
}

// AnswerFormatGTE applies the GTE predicate on the "answer_format" field.
func AnswerFormatGTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldGTE(FieldAnswerFormat, v))
}

// AnswerFormatLT applies the LT predicate on the "answer_format" field.
func AnswerFormatLT(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLT(FieldAnswerFormat, v))
}

// AnswerFormatLTE applies the LTE predicate on the "answer_format" field.
func AnswerFormatLTE(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldLTE(FieldAnswerFormat, v))
}

// AnswerFormatContains applies the Contains predicate on the "answer_format" field.
func AnswerFormatContains(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContains(FieldAnswerFormat, v))
}

// AnswerFormatHasPrefix applies the HasPrefix predicate on the "answer_format" field.
func AnswerFormatHasPrefix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasPrefix(FieldAnswerFormat, v))
}

// AnswerFormatHasSuffix applies the HasSuffix predicate on the "answer_format" field.
func AnswerFormatHasSuffix(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldHasSuffix(FieldAnswerFormat, v))
}

// AnswerFormatEqualFold applies the EqualFold predicate on the "answer_format" field.
func AnswerFormatEqualFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldEqualFold(FieldAnswerFormat, v))
}

// AnswerFormatContainsFold applies the ContainsFold predicate on the "answer_format" field.
func AnswerFormatContainsFold(v string) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.FieldContainsFold(FieldAnswerFormat, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AnswerEvent) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AnswerEvent) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AnswerEvent) predicate.AnswerEvent {
	return predicate.AnswerEvent(sql.NotPredicates(p))
}
