// Code generated by ent, DO NOT EDIT.

package quest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/abhisek/mathiz/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Quest {
	return predicate.Quest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Quest {
	return predicate.Quest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Quest {
	return predicate.Quest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Quest {
	return predicate.Quest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Quest {
	return predicate.Quest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Quest {
	return predicate.Quest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Quest {
	return predicate.Quest(sql.FieldLTE(FieldID, id))
}

// UID applies equality check predicate on the "uid" field. It's identical to UIDEQ.
func UID(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldUID, v))
}

// FamilySpaceID applies equality check predicate on the "family_space_id" field. It's identical to FamilySpaceIDEQ.
func FamilySpaceID(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldFamilySpaceID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldName, v))
}

// Emoji applies equality check predicate on the "emoji" field. It's identical to EmojiEQ.
func Emoji(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldEmoji, v))
}

// SkillID applies equality check predicate on the "skill_id" field. It's identical to SkillIDEQ.
func SkillID(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldSkillID, v))
}

// ChildUID applies equality check predicate on the "child_uid" field. It's identical to ChildUIDEQ.
func ChildUID(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldChildUID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UIDEQ applies the EQ predicate on the "uid" field.
func UIDEQ(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldUID, v))
}

// UIDNEQ applies the NEQ predicate on the "uid" field.
func UIDNEQ(v string) predicate.Quest {
	return predicate.Quest(sql.FieldNEQ(FieldUID, v))
}

// UIDIn applies the In predicate on the "uid" field.
func UIDIn(vs ...string) predicate.Quest {
	return predicate.Quest(sql.FieldIn(FieldUID, vs...))
}

// UIDNotIn applies the NotIn predicate on the "uid" field.
func UIDNotIn(vs ...string) predicate.Quest {
	return predicate.Quest(sql.FieldNotIn(FieldUID, vs...))
}

// UIDGT applies the GT predicate on the "uid" field.
func UIDGT(v string) predicate.Quest {
	return predicate.Quest(sql.FieldGT(FieldUID, v))
}

// UIDGTE applies the GTE predicate on the "uid" field.
func UIDGTE(v string) predicate.Quest {
	return predicate.Quest(sql.FieldGTE(FieldUID, v))
}

// UIDLT applies the LT predicate on the "uid" field.
func UIDLT(v string) predicate.Quest {
	return predicate.Quest(sql.FieldLT(FieldUID, v))
}

// UIDLTE applies the LTE predicate on the "uid" field.
func UIDLTE(v string) predicate.Quest {
	return predicate.Quest(sql.FieldLTE(FieldUID, v))
}

// UIDContains applies the Contains predicate on the "uid" field.
func UIDContains(v string) predicate.Quest {
	return predicate.Quest(sql.FieldContains(FieldUID, v))
}

// UIDHasPrefix applies the HasPrefix predicate on the "uid" field.
func UIDHasPrefix(v string) predicate.Quest {
	return predicate.Quest(sql.FieldHasPrefix(FieldUID, v))
}

// UIDHasSuffix applies the HasSuffix predicate on the "uid" field.
func UIDHasSuffix(v string) predicate.Quest {
	return predicate.Quest(sql.FieldHasSuffix(FieldUID, v))
}

// UIDEqualFold applies the EqualFold predicate on the "uid" field.
func UIDEqualFold(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEqualFold(FieldUID, v))
}

// UIDContainsFold applies the ContainsFold predicate on the "uid" field.
func UIDContainsFold(v string) predicate.Quest {
	return predicate.Quest(sql.FieldContainsFold(FieldUID, v))
}

// FamilySpaceIDEQ applies the EQ predicate on the "family_space_id" field.
func FamilySpaceIDEQ(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldFamilySpaceID, v))
}

// FamilySpaceIDNEQ applies the NEQ predicate on the "family_space_id" field.
func FamilySpaceIDNEQ(v string) predicate.Quest {
	return predicate.Quest(sql.FieldNEQ(FieldFamilySpaceID, v))
}

// FamilySpaceIDIn applies the In predicate on the "family_space_id" field.
func FamilySpaceIDIn(vs ...string) predicate.Quest {
	return predicate.Quest(sql.FieldIn(FieldFamilySpaceID, vs...))
}

// FamilySpaceIDNotIn applies the NotIn predicate on the "family_space_id" field.
func FamilySpaceIDNotIn(vs ...string) predicate.Quest {
	return predicate.Quest(sql.FieldNotIn(FieldFamilySpaceID, vs...))
}

// FamilySpaceIDGT applies the GT predicate on the "family_space_id" field.
func FamilySpaceIDGT(v string) predicate.Quest {
	return predicate.Quest(sql.FieldGT(FieldFamilySpaceID, v))
}

// FamilySpaceIDGTE applies the GTE predicate on the "family_space_id" field.
func FamilySpaceIDGTE(v string) predicate.Quest {
	return predicate.Quest(sql.FieldGTE(FieldFamilySpaceID, v))
}

// FamilySpaceIDLT applies the LT predicate on the "family_space_id" field.
func FamilySpaceIDLT(v string) predicate.Quest {
	return predicate.Quest(sql.FieldLT(FieldFamilySpaceID, v))
}

// FamilySpaceIDLTE applies the LTE predicate on the "family_space_id" field.
func FamilySpaceIDLTE(v string) predicate.Quest {
	return predicate.Quest(sql.FieldLTE(FieldFamilySpaceID, v))
}

// FamilySpaceIDContains applies the Contains predicate on the "family_space_id" field.
func FamilySpaceIDContains(v string) predicate.Quest {
	return predicate.Quest(sql.FieldContains(FieldFamilySpaceID, v))
}

// FamilySpaceIDHasPrefix applies the HasPrefix predicate on the "family_space_id" field.
func FamilySpaceIDHasPrefix(v string) predicate.Quest {
	return predicate.Quest(sql.FieldHasPrefix(FieldFamilySpaceID, v))
}

// FamilySpaceIDHasSuffix applies the HasSuffix predicate on the "family_space_id" field.
func FamilySpaceIDHasSuffix(v string) predicate.Quest {
	return predicate.Quest(sql.FieldHasSuffix(FieldFamilySpaceID, v))
}

// FamilySpaceIDEqualFold applies the EqualFold predicate on the "family_space_id" field.
func FamilySpaceIDEqualFold(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEqualFold(FieldFamilySpaceID, v))
}

// FamilySpaceIDContainsFold applies the ContainsFold predicate on the "family_space_id" field.
func FamilySpaceIDContainsFold(v string) predicate.Quest {
	return predicate.Quest(sql.FieldContainsFold(FieldFamilySpaceID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Quest {
	return predicate.Quest(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Quest {
	return predicate.Quest(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Quest {
	return predicate.Quest(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Quest {
	return predicate.Quest(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Quest {
	return predicate.Quest(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Quest {
	return predicate.Quest(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Quest {
	return predicate.Quest(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Quest {
	return predicate.Quest(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Quest {
	return predicate.Quest(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Quest {
	return predicate.Quest(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Quest {
	return predicate.Quest(sql.FieldContainsFold(FieldName, v))
}

// EmojiEQ applies the EQ predicate on the "emoji" field.
func EmojiEQ(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldEmoji, v))
}

// EmojiNEQ applies the NEQ predicate on the "emoji" field.
func EmojiNEQ(v string) predicate.Quest {
	return predicate.Quest(sql.FieldNEQ(FieldEmoji, v))
}

// EmojiIn applies the In predicate on the "emoji" field.
func EmojiIn(vs ...string) predicate.Quest {
	return predicate.Quest(sql.FieldIn(FieldEmoji, vs...))
}

// EmojiNotIn applies the NotIn predicate on the "emoji" field.
func EmojiNotIn(vs ...string) predicate.Quest {
	return predicate.Quest(sql.FieldNotIn(FieldEmoji, vs...))
}

// EmojiGT applies the GT predicate on the "emoji" field.
func EmojiGT(v string) predicate.Quest {
	return predicate.Quest(sql.FieldGT(FieldEmoji, v))
}

// EmojiGTE applies the GTE predicate on the "emoji" field.
func EmojiGTE(v string) predicate.Quest {
	return predicate.Quest(sql.FieldGTE(FieldEmoji, v))
}

// EmojiLT applies the LT predicate on the "emoji" field.
func EmojiLT(v string) predicate.Quest {
	return predicate.Quest(sql.FieldLT(FieldEmoji, v))
}

// EmojiLTE applies the LTE predicate on the "emoji" field.
func EmojiLTE(v string) predicate.Quest {
	return predicate.Quest(sql.FieldLTE(FieldEmoji, v))
}

// EmojiContains applies the Contains predicate on the "emoji" field.
func EmojiContains(v string) predicate.Quest {
	return predicate.Quest(sql.FieldContains(FieldEmoji, v))
}

// EmojiHasPrefix applies the HasPrefix predicate on the "emoji" field.
func EmojiHasPrefix(v string) predicate.Quest {
	return predicate.Quest(sql.FieldHasPrefix(FieldEmoji, v))
}

// EmojiHasSuffix applies the HasSuffix predicate on the "emoji" field.
func EmojiHasSuffix(v string) predicate.Quest {
	return predicate.Quest(sql.FieldHasSuffix(FieldEmoji, v))
}

// EmojiEqualFold applies the EqualFold predicate on the "emoji" field.
func EmojiEqualFold(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEqualFold(FieldEmoji, v))
}

// EmojiContainsFold applies the ContainsFold predicate on the "emoji" field.
func EmojiContainsFold(v string) predicate.Quest {
	return predicate.Quest(sql.FieldContainsFold(FieldEmoji, v))
}

// SkillIDEQ applies the EQ predicate on the "skill_id" field.
func SkillIDEQ(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldSkillID, v))
}

// SkillIDNEQ applies the NEQ predicate on the "skill_id" field.
func SkillIDNEQ(v string) predicate.Quest {
	return predicate.Quest(sql.FieldNEQ(FieldSkillID, v))
}

// SkillIDIn applies the In predicate on the "skill_id" field.
func SkillIDIn(vs ...string) predicate.Quest {
	return predicate.Quest(sql.FieldIn(FieldSkillID, vs...))
}

// SkillIDNotIn applies the NotIn predicate on the "skill_id" field.
func SkillIDNotIn(vs ...string) predicate.Quest {
	return predicate.Quest(sql.FieldNotIn(FieldSkillID, vs...))
}

// SkillIDGT applies the GT predicate on the "skill_id" field.
func SkillIDGT(v string) predicate.Quest {
	return predicate.Quest(sql.FieldGT(FieldSkillID, v))
}

// SkillIDGTE applies the GTE predicate on the "skill_id" field.
func SkillIDGTE(v string) predicate.Quest {
	return predicate.Quest(sql.FieldGTE(FieldSkillID, v))
}

// SkillIDLT applies the LT predicate on the "skill_id" field.
func SkillIDLT(v string) predicate.Quest {
	return predicate.Quest(sql.FieldLT(FieldSkillID, v))
}

// SkillIDLTE applies the LTE predicate on the "skill_id" field.
func SkillIDLTE(v string) predicate.Quest {
	return predicate.Quest(sql.FieldLTE(FieldSkillID, v))
}

// SkillIDContains applies the Contains predicate on the "skill_id" field.
func SkillIDContains(v string) predicate.Quest {
	return predicate.Quest(sql.FieldContains(FieldSkillID, v))
}

// SkillIDHasPrefix applies the HasPrefix predicate on the "skill_id" field.
func SkillIDHasPrefix(v string) predicate.Quest {
	return predicate.Quest(sql.FieldHasPrefix(FieldSkillID, v))
}

// SkillIDHasSuffix applies the HasSuffix predicate on the "skill_id" field.
func SkillIDHasSuffix(v string) predicate.Quest {
	return predicate.Quest(sql.FieldHasSuffix(FieldSkillID, v))
}

// SkillIDEqualFold applies the EqualFold predicate on the "skill_id" field.
func SkillIDEqualFold(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEqualFold(FieldSkillID, v))
}

// SkillIDContainsFold applies the ContainsFold predicate on the "skill_id" field.
func SkillIDContainsFold(v string) predicate.Quest {
	return predicate.Quest(sql.FieldContainsFold(FieldSkillID, v))
}

// ChildUIDEQ applies the EQ predicate on the "child_uid" field.
func ChildUIDEQ(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldChildUID, v))
}

// ChildUIDNEQ applies the NEQ predicate on the "child_uid" field.
func ChildUIDNEQ(v string) predicate.Quest {
	return predicate.Quest(sql.FieldNEQ(FieldChildUID, v))
}

// ChildUIDIn applies the In predicate on the "child_uid" field.
func ChildUIDIn(vs ...string) predicate.Quest {
	return predicate.Quest(sql.FieldIn(FieldChildUID, vs...))
}

// ChildUIDNotIn applies the NotIn predicate on the "child_uid" field.
func ChildUIDNotIn(vs ...string) predicate.Quest {
	return predicate.Quest(sql.FieldNotIn(FieldChildUID, vs...))
}

// ChildUIDGT applies the GT predicate on the "child_uid" field.
func ChildUIDGT(v string) predicate.Quest {
	return predicate.Quest(sql.FieldGT(FieldChildUID, v))
}

// ChildUIDGTE applies the GTE predicate on the "child_uid" field.
func ChildUIDGTE(v string) predicate.Quest {
	return predicate.Quest(sql.FieldGTE(FieldChildUID, v))
}

// ChildUIDLT applies the LT predicate on the "child_uid" field.
func ChildUIDLT(v string) predicate.Quest {
	return predicate.Quest(sql.FieldLT(FieldChildUID, v))
}

// ChildUIDLTE applies the LTE predicate on the "child_uid" field.
func ChildUIDLTE(v string) predicate.Quest {
	return predicate.Quest(sql.FieldLTE(FieldChildUID, v))
}

// ChildUIDContains applies the Contains predicate on the "child_uid" field.
func ChildUIDContains(v string) predicate.Quest {
	return predicate.Quest(sql.FieldContains(FieldChildUID, v))
}

// ChildUIDHasPrefix applies the HasPrefix predicate on the "child_uid" field.
func ChildUIDHasPrefix(v string) predicate.Quest {
	return predicate.Quest(sql.FieldHasPrefix(FieldChildUID, v))
}

// ChildUIDHasSuffix applies the HasSuffix predicate on the "child_uid" field.
func ChildUIDHasSuffix(v string) predicate.Quest {
	return predicate.Quest(sql.FieldHasSuffix(FieldChildUID, v))
}

// ChildUIDEqualFold applies the EqualFold predicate on the "child_uid" field.
func ChildUIDEqualFold(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEqualFold(FieldChildUID, v))
}

// ChildUIDContainsFold applies the ContainsFold predicate on the "child_uid" field.
func ChildUIDContainsFold(v string) predicate.Quest {
	return predicate.Quest(sql.FieldContainsFold(FieldChildUID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Quest {
	return predicate.Quest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Quest {
	return predicate.Quest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Quest {
	return predicate.Quest(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Quest {
	return predicate.Quest(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Quest {
	return predicate.Quest(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Quest {
	return predicate.Quest(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Quest {
	return predicate.Quest(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Quest {
	return predicate.Quest(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Quest {
	return predicate.Quest(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Quest {
	return predicate.Quest(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Quest {
	return predicate.Quest(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Quest {
	return predicate.Quest(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Quest {
	return predicate.Quest(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Quest) predicate.Quest {
	return predicate.Quest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Quest) predicate.Quest {
	return predicate.Quest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Quest) predicate.Quest {
	return predicate.Quest(sql.NotPredicates(p))
}
