// Code generated by ent, DO NOT EDIT.

package questprogress

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the questprogress type in the database.
	Label = "quest_progress"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldQuestUID holds the string denoting the quest_uid field in the database.
	FieldQuestUID = "quest_uid"
	// FieldChildUID holds the string denoting the child_uid field in the database.
	FieldChildUID = "child_uid"
	// FieldQuestionUID holds the string denoting the question_uid field in the database.
	FieldQuestionUID = "question_uid"
	// FieldCorrect holds the string denoting the correct field in the database.
	FieldCorrect = "correct"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the questprogress in the database.
	Table = "quest_progresses"
)

// Columns holds all SQL columns for questprogress fields.
var Columns = []string{
	FieldID,
	FieldUID,
	FieldQuestUID,
	FieldChildUID,
	FieldQuestionUID,
	FieldCorrect,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCorrect holds the default value on creation for the "correct" field.
	DefaultCorrect bool
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the QuestProgress queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUID orders the results by the uid field.
func ByUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUID, opts...).ToFunc()
}

// ByQuestUID orders the results by the quest_uid field.
func ByQuestUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuestUID, opts...).ToFunc()
}

// ByChildUID orders the results by the child_uid field.
func ByChildUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChildUID, opts...).ToFunc()
}

// ByQuestionUID orders the results by the question_uid field.
func ByQuestionUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuestionUID, opts...).ToFunc()
}

// ByCorrect orders the results by the correct field.
func ByCorrect(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCorrect, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
