// Code generated by ent, DO NOT EDIT.

package billingstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/abhisek/mathiz/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BillingState {
	return predicate.BillingState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BillingState {
	return predicate.BillingState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BillingState {
	return predicate.BillingState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BillingState {
	return predicate.BillingState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BillingState {
	return predicate.BillingState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BillingState {
	return predicate.BillingState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BillingState {
	return predicate.BillingState(sql.FieldLTE(FieldID, id))
}

// UID applies equality check predicate on the "uid" field. It's identical to UIDEQ.
func UID(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldUID, v))
}

// FamilySpaceID applies equality check predicate on the "family_space_id" field. It's identical to FamilySpaceIDEQ.
func FamilySpaceID(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldFamilySpaceID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldProvider, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldCustomerID, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldSubscriptionID, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldPlanID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldStatus, v))
}

// CurrentPeriodEnd applies equality check predicate on the "current_period_end" field. It's identical to CurrentPeriodEndEQ.
func CurrentPeriodEnd(v time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldCurrentPeriodEnd, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UIDEQ applies the EQ predicate on the "uid" field.
func UIDEQ(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldUID, v))
}

// UIDNEQ applies the NEQ predicate on the "uid" field.
func UIDNEQ(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldNEQ(FieldUID, v))
}

// UIDIn applies the In predicate on the "uid" field.
func UIDIn(vs ...string) predicate.BillingState {
	return predicate.BillingState(sql.FieldIn(FieldUID, vs...))
}

// UIDNotIn applies the NotIn predicate on the "uid" field.
func UIDNotIn(vs ...string) predicate.BillingState {
	return predicate.BillingState(sql.FieldNotIn(FieldUID, vs...))
}

// UIDGT applies the GT predicate on the "uid" field.
func UIDGT(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldGT(FieldUID, v))
}

// UIDGTE applies the GTE predicate on the "uid" field.
func UIDGTE(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldGTE(FieldUID, v))
}

// UIDLT applies the LT predicate on the "uid" field.
func UIDLT(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldLT(FieldUID, v))
}

// UIDLTE applies the LTE predicate on the "uid" field.
func UIDLTE(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldLTE(FieldUID, v))
}

// UIDContains applies the Contains predicate on the "uid" field.
func UIDContains(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldContains(FieldUID, v))
}

// UIDHasPrefix applies the HasPrefix predicate on the "uid" field.
func UIDHasPrefix(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldHasPrefix(FieldUID, v))
}

// UIDHasSuffix applies the HasSuffix predicate on the "uid" field.
func UIDHasSuffix(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldHasSuffix(FieldUID, v))
}

// UIDEqualFold applies the EqualFold predicate on the "uid" field.
func UIDEqualFold(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEqualFold(FieldUID, v))
}

// UIDContainsFold applies the ContainsFold predicate on the "uid" field.
func UIDContainsFold(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldContainsFold(FieldUID, v))
}

// FamilySpaceIDEQ applies the EQ predicate on the "family_space_id" field.
func FamilySpaceIDEQ(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldFamilySpaceID, v))
}

// FamilySpaceIDNEQ applies the NEQ predicate on the "family_space_id" field.
func FamilySpaceIDNEQ(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldNEQ(FieldFamilySpaceID, v))
}

// FamilySpaceIDIn applies the In predicate on the "family_space_id" field.
func FamilySpaceIDIn(vs ...string) predicate.BillingState {
	return predicate.BillingState(sql.FieldIn(FieldFamilySpaceID, vs...))
}

// FamilySpaceIDNotIn applies the NotIn predicate on the "family_space_id" field.
func FamilySpaceIDNotIn(vs ...string) predicate.BillingState {
	return predicate.BillingState(sql.FieldNotIn(FieldFamilySpaceID, vs...))
}

// FamilySpaceIDGT applies the GT predicate on the "family_space_id" field.
func FamilySpaceIDGT(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldGT(FieldFamilySpaceID, v))
}

// FamilySpaceIDGTE applies the GTE predicate on the "family_space_id" field.
func FamilySpaceIDGTE(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldGTE(FieldFamilySpaceID, v))
}

// FamilySpaceIDLT applies the LT predicate on the "family_space_id" field.
func FamilySpaceIDLT(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldLT(FieldFamilySpaceID, v))
}

// FamilySpaceIDLTE applies the LTE predicate on the "family_space_id" field.
func FamilySpaceIDLTE(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldLTE(FieldFamilySpaceID, v))
}

// FamilySpaceIDContains applies the Contains predicate on the "family_space_id" field.
func FamilySpaceIDContains(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldContains(FieldFamilySpaceID, v))
}

// FamilySpaceIDHasPrefix applies the HasPrefix predicate on the "family_space_id" field.
func FamilySpaceIDHasPrefix(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldHasPrefix(FieldFamilySpaceID, v))
}

// FamilySpaceIDHasSuffix applies the HasSuffix predicate on the "family_space_id" field.
func FamilySpaceIDHasSuffix(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldHasSuffix(FieldFamilySpaceID, v))
}

// FamilySpaceIDEqualFold applies the EqualFold predicate on the "family_space_id" field.
func FamilySpaceIDEqualFold(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEqualFold(FieldFamilySpaceID, v))
}

// FamilySpaceIDContainsFold applies the ContainsFold predicate on the "family_space_id" field.
func FamilySpaceIDContainsFold(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldContainsFold(FieldFamilySpaceID, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.BillingState {
	return predicate.BillingState(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.BillingState {
	return predicate.BillingState(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldContainsFold(FieldProvider, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.BillingState {
	return predicate.BillingState(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.BillingState {
	return predicate.BillingState(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldContainsFold(FieldCustomerID, v))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...string) predicate.BillingState {
	return predicate.BillingState(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...string) predicate.BillingState {
	return predicate.BillingState(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDGT applies the GT predicate on the "subscription_id" field.
func SubscriptionIDGT(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldGT(FieldSubscriptionID, v))
}

// SubscriptionIDGTE applies the GTE predicate on the "subscription_id" field.
func SubscriptionIDGTE(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldGTE(FieldSubscriptionID, v))
}

// SubscriptionIDLT applies the LT predicate on the "subscription_id" field.
func SubscriptionIDLT(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldLT(FieldSubscriptionID, v))
}

// SubscriptionIDLTE applies the LTE predicate on the "subscription_id" field.
func SubscriptionIDLTE(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldLTE(FieldSubscriptionID, v))
}

// SubscriptionIDContains applies the Contains predicate on the "subscription_id" field.
func SubscriptionIDContains(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldContains(FieldSubscriptionID, v))
}

// SubscriptionIDHasPrefix applies the HasPrefix predicate on the "subscription_id" field.
func SubscriptionIDHasPrefix(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldHasPrefix(FieldSubscriptionID, v))
}

// SubscriptionIDHasSuffix applies the HasSuffix predicate on the "subscription_id" field.
func SubscriptionIDHasSuffix(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldHasSuffix(FieldSubscriptionID, v))
}

// SubscriptionIDEqualFold applies the EqualFold predicate on the "subscription_id" field.
func SubscriptionIDEqualFold(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEqualFold(FieldSubscriptionID, v))
}

// SubscriptionIDContainsFold applies the ContainsFold predicate on the "subscription_id" field.
func SubscriptionIDContainsFold(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldContainsFold(FieldSubscriptionID, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...string) predicate.BillingState {
	return predicate.BillingState(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...string) predicate.BillingState {
	return predicate.BillingState(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDGT applies the GT predicate on the "plan_id" field.
func PlanIDGT(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldGT(FieldPlanID, v))
}

// PlanIDGTE applies the GTE predicate on the "plan_id" field.
func PlanIDGTE(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldGTE(FieldPlanID, v))
}

// PlanIDLT applies the LT predicate on the "plan_id" field.
func PlanIDLT(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldLT(FieldPlanID, v))
}

// PlanIDLTE applies the LTE predicate on the "plan_id" field.
func PlanIDLTE(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldLTE(FieldPlanID, v))
}

// PlanIDContains applies the Contains predicate on the "plan_id" field.
func PlanIDContains(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldContains(FieldPlanID, v))
}

// PlanIDHasPrefix applies the HasPrefix predicate on the "plan_id" field.
func PlanIDHasPrefix(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldHasPrefix(FieldPlanID, v))
}

// PlanIDHasSuffix applies the HasSuffix predicate on the "plan_id" field.
func PlanIDHasSuffix(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldHasSuffix(FieldPlanID, v))
}

// PlanIDEqualFold applies the EqualFold predicate on the "plan_id" field.
func PlanIDEqualFold(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEqualFold(FieldPlanID, v))
}

// PlanIDContainsFold applies the ContainsFold predicate on the "plan_id" field.
func PlanIDContainsFold(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldContainsFold(FieldPlanID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.BillingState {
	return predicate.BillingState(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.BillingState {
	return predicate.BillingState(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.BillingState {
	return predicate.BillingState(sql.FieldContainsFold(FieldStatus, v))
}

// CurrentPeriodEndEQ applies the EQ predicate on the "current_period_end" field.
func CurrentPeriodEndEQ(v time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldCurrentPeriodEnd, v))
}

// CurrentPeriodEndNEQ applies the NEQ predicate on the "current_period_end" field.
func CurrentPeriodEndNEQ(v time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldNEQ(FieldCurrentPeriodEnd, v))
}

// CurrentPeriodEndIn applies the In predicate on the "current_period_end" field.
func CurrentPeriodEndIn(vs ...time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldIn(FieldCurrentPeriodEnd, vs...))
}

// CurrentPeriodEndNotIn applies the NotIn predicate on the "current_period_end" field.
func CurrentPeriodEndNotIn(vs ...time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldNotIn(FieldCurrentPeriodEnd, vs...))
}

// CurrentPeriodEndGT applies the GT predicate on the "current_period_end" field.
func CurrentPeriodEndGT(v time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldGT(FieldCurrentPeriodEnd, v))
}

// CurrentPeriodEndGTE applies the GTE predicate on the "current_period_end" field.
func CurrentPeriodEndGTE(v time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldGTE(FieldCurrentPeriodEnd, v))
}

// CurrentPeriodEndLT applies the LT predicate on the "current_period_end" field.
func CurrentPeriodEndLT(v time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldLT(FieldCurrentPeriodEnd, v))
}

// CurrentPeriodEndLTE applies the LTE predicate on the "current_period_end" field.
func CurrentPeriodEndLTE(v time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldLTE(FieldCurrentPeriodEnd, v))
}

// CurrentPeriodEndIsNil applies the IsNil predicate on the "current_period_end" field.
func CurrentPeriodEndIsNil() predicate.BillingState {
	return predicate.BillingState(sql.FieldIsNull(FieldCurrentPeriodEnd))
}

// CurrentPeriodEndNotNil applies the NotNil predicate on the "current_period_end" field.
func CurrentPeriodEndNotNil() predicate.BillingState {
	return predicate.BillingState(sql.FieldNotNull(FieldCurrentPeriodEnd))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BillingState {
	return predicate.BillingState(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BillingState) predicate.BillingState {
	return predicate.BillingState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BillingState) predicate.BillingState {
	return predicate.BillingState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BillingState) predicate.BillingState {
	return predicate.BillingState(sql.NotPredicates(p))
}
