// Code generated by ent, DO NOT EDIT.

package masteryevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the masteryevent type in the database.
	Label = "mastery_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSequence holds the string denoting the sequence field in the database.
	FieldSequence = "sequence"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldSkillID holds the string denoting the skill_id field in the database.
	FieldSkillID = "skill_id"
	// FieldFromState holds the string denoting the from_state field in the database.
	FieldFromState = "from_state"
	// FieldToState holds the string denoting the to_state field in the database.
	FieldToState = "to_state"
	// FieldTrigger holds the string denoting the trigger field in the database.
	FieldTrigger = "trigger"
	// FieldFluencyScore holds the string denoting the fluency_score field in the database.
	FieldFluencyScore = "fluency_score"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// Table holds the table name of the masteryevent in the database.
	Table = "mastery_events"
)

// Columns holds all SQL columns for masteryevent fields.
var Columns = []string{
	FieldID,
	FieldSequence,
	FieldTimestamp,
	FieldSkillID,
	FieldFromState,
	FieldToState,
	FieldTrigger,
	FieldFluencyScore,
	FieldSessionID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTimestamp holds the default value on creation for the "timestamp" field.
	DefaultTimestamp func() time.Time
	// SkillIDValidator is a validator for the "skill_id" field. It is called by the builders before save.
	SkillIDValidator func(string) error
	// FromStateValidator is a validator for the "from_state" field. It is called by the builders before save.
	FromStateValidator func(string) error
	// ToStateValidator is a validator for the "to_state" field. It is called by the builders before save.
	ToStateValidator func(string) error
	// TriggerValidator is a validator for the "trigger" field. It is called by the builders before save.
	TriggerValidator func(string) error
)

// OrderOption defines the ordering options for the MasteryEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySequence orders the results by the sequence field.
func BySequence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSequence, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// BySkillID orders the results by the skill_id field.
func BySkillID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkillID, opts...).ToFunc()
}

// ByFromState orders the results by the from_state field.
func ByFromState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromState, opts...).ToFunc()
}

// ByToState orders the results by the to_state field.
func ByToState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToState, opts...).ToFunc()
}

// ByTrigger orders the results by the trigger field.
func ByTrigger(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrigger, opts...).ToFunc()
}

// ByFluencyScore orders the results by the fluency_score field.
func ByFluencyScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFluencyScore, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}
