// Code generated by ent, DO NOT EDIT.

package childprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the childprofile type in the database.
	Label = "child_profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldFamilySpaceID holds the string denoting the family_space_id field in the database.
	FieldFamilySpaceID = "family_space_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldGrade holds the string denoting the grade field in the database.
	FieldGrade = "grade"
	// FieldPinHash holds the string denoting the pin_hash field in the database.
	FieldPinHash = "pin_hash"
	// FieldArchived holds the string denoting the archived field in the database.
	FieldArchived = "archived"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the childprofile in the database.
	Table = "child_profiles"
)

// Columns holds all SQL columns for childprofile fields.
var Columns = []string{
	FieldID,
	FieldUID,
	FieldFamilySpaceID,
	FieldName,
	FieldGrade,
	FieldPinHash,
	FieldArchived,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPinHash holds the default value on creation for the "pin_hash" field.
	DefaultPinHash string
	// DefaultArchived holds the default value on creation for the "archived" field.
	DefaultArchived bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ChildProfile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUID orders the results by the uid field.
func ByUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUID, opts...).ToFunc()
}

// ByFamilySpaceID orders the results by the family_space_id field.
func ByFamilySpaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFamilySpaceID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByGrade orders the results by the grade field.
func ByGrade(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrade, opts...).ToFunc()
}

// ByPinHash orders the results by the pin_hash field.
func ByPinHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPinHash, opts...).ToFunc()
}

// ByArchived orders the results by the archived field.
func ByArchived(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArchived, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
