package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
)

// LearnerProfileEvent records a changed version of the LLM-generated learner
// profile — an append-only history of the tutor's understanding of the
// learner. Snapshots still carry only the latest profile (and prune old
// rows); these events are what preserve the full history.
type LearnerProfileEvent struct {
	ent.Schema
}

func (LearnerProfileEvent) Mixin() []ent.Mixin {
	return []ent.Mixin{EventMixin{}}
}

func (LearnerProfileEvent) Fields() []ent.Field {
	return []ent.Field{
		field.Text("summary").
			Default("").
			Comment("Natural-language summary of the learner"),
		field.JSON("strengths", []string{}).
			Optional().
			Comment("Observed strengths"),
		field.JSON("weaknesses", []string{}).
			Optional().
			Comment("Observed weaknesses"),
		field.JSON("patterns", []string{}).
			Optional().
			Comment("Observed error/behavior patterns"),
		field.String("generated_at").
			Default("").
			Comment("RFC3339 time the profile was generated by the LLM"),
	}
}
