// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SnapshotsColumns holds the columns for the "snapshots" table.
	SnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sequence", Type: field.TypeInt64},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "data", Type: field.TypeJSON},
	}
	// SnapshotsTable holds the schema information for the "snapshots" table.
	SnapshotsTable = &schema.Table{
		Name:       "snapshots",
		Columns:    SnapshotsColumns,
		PrimaryKey: []*schema.Column{SnapshotsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "snapshot_timestamp",
				Unique:  false,
				Columns: []*schema.Column{SnapshotsColumns[2]},
			},
			{
				Name:    "snapshot_sequence",
				Unique:  false,
				Columns: []*schema.Column{SnapshotsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SnapshotsTable,
	}
)

func init() {
}
