// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnswerEventsColumns holds the columns for the "answer_events" table.
	AnswerEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sequence", Type: field.TypeInt64, Unique: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "session_id", Type: field.TypeString},
		{Name: "skill_id", Type: field.TypeString},
		{Name: "tier", Type: field.TypeString},
		{Name: "category", Type: field.TypeString},
		{Name: "question_text", Type: field.TypeString},
		{Name: "correct_answer", Type: field.TypeString},
		{Name: "learner_answer", Type: field.TypeString},
		{Name: "correct", Type: field.TypeBool},
		{Name: "time_ms", Type: field.TypeInt},
		{Name: "answer_format", Type: field.TypeString},
	}
	// AnswerEventsTable holds the schema information for the "answer_events" table.
	AnswerEventsTable = &schema.Table{
		Name:       "answer_events",
		Columns:    AnswerEventsColumns,
		PrimaryKey: []*schema.Column{AnswerEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "answerevent_sequence",
				Unique:  false,
				Columns: []*schema.Column{AnswerEventsColumns[1]},
			},
			{
				Name:    "answerevent_timestamp",
				Unique:  false,
				Columns: []*schema.Column{AnswerEventsColumns[2]},
			},
			{
				Name:    "answerevent_session_id",
				Unique:  false,
				Columns: []*schema.Column{AnswerEventsColumns[3]},
			},
			{
				Name:    "answerevent_skill_id",
				Unique:  false,
				Columns: []*schema.Column{AnswerEventsColumns[4]},
			},
			{
				Name:    "answerevent_correct",
				Unique:  false,
				Columns: []*schema.Column{AnswerEventsColumns[10]},
			},
		},
	}
	// DiagnosisEventsColumns holds the columns for the "diagnosis_events" table.
	DiagnosisEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sequence", Type: field.TypeInt64, Unique: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "session_id", Type: field.TypeString},
		{Name: "skill_id", Type: field.TypeString},
		{Name: "question_text", Type: field.TypeString},
		{Name: "correct_answer", Type: field.TypeString},
		{Name: "learner_answer", Type: field.TypeString},
		{Name: "category", Type: field.TypeString},
		{Name: "misconception_id", Type: field.TypeString, Nullable: true},
		{Name: "confidence", Type: field.TypeFloat64},
		{Name: "classifier_name", Type: field.TypeString},
		{Name: "reasoning", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// DiagnosisEventsTable holds the schema information for the "diagnosis_events" table.
	DiagnosisEventsTable = &schema.Table{
		Name:       "diagnosis_events",
		Columns:    DiagnosisEventsColumns,
		PrimaryKey: []*schema.Column{DiagnosisEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "diagnosisevent_sequence",
				Unique:  false,
				Columns: []*schema.Column{DiagnosisEventsColumns[1]},
			},
			{
				Name:    "diagnosisevent_timestamp",
				Unique:  false,
				Columns: []*schema.Column{DiagnosisEventsColumns[2]},
			},
			{
				Name:    "diagnosisevent_skill_id",
				Unique:  false,
				Columns: []*schema.Column{DiagnosisEventsColumns[4]},
			},
			{
				Name:    "diagnosisevent_session_id",
				Unique:  false,
				Columns: []*schema.Column{DiagnosisEventsColumns[3]},
			},
		},
	}
	// GemEventsColumns holds the columns for the "gem_events" table.
	GemEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sequence", Type: field.TypeInt64, Unique: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "gem_type", Type: field.TypeString},
		{Name: "rarity", Type: field.TypeString},
		{Name: "skill_id", Type: field.TypeString, Nullable: true},
		{Name: "skill_name", Type: field.TypeString, Nullable: true},
		{Name: "session_id", Type: field.TypeString},
		{Name: "reason", Type: field.TypeString},
	}
	// GemEventsTable holds the schema information for the "gem_events" table.
	GemEventsTable = &schema.Table{
		Name:       "gem_events",
		Columns:    GemEventsColumns,
		PrimaryKey: []*schema.Column{GemEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gemevent_sequence",
				Unique:  false,
				Columns: []*schema.Column{GemEventsColumns[1]},
			},
			{
				Name:    "gemevent_timestamp",
				Unique:  false,
				Columns: []*schema.Column{GemEventsColumns[2]},
			},
			{
				Name:    "gemevent_gem_type",
				Unique:  false,
				Columns: []*schema.Column{GemEventsColumns[3]},
			},
			{
				Name:    "gemevent_session_id",
				Unique:  false,
				Columns: []*schema.Column{GemEventsColumns[7]},
			},
			{
				Name:    "gemevent_rarity",
				Unique:  false,
				Columns: []*schema.Column{GemEventsColumns[4]},
			},
		},
	}
	// HintEventsColumns holds the columns for the "hint_events" table.
	HintEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sequence", Type: field.TypeInt64, Unique: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "session_id", Type: field.TypeString},
		{Name: "skill_id", Type: field.TypeString},
		{Name: "question_text", Type: field.TypeString},
		{Name: "hint_text", Type: field.TypeString},
	}
	// HintEventsTable holds the schema information for the "hint_events" table.
	HintEventsTable = &schema.Table{
		Name:       "hint_events",
		Columns:    HintEventsColumns,
		PrimaryKey: []*schema.Column{HintEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "hintevent_sequence",
				Unique:  false,
				Columns: []*schema.Column{HintEventsColumns[1]},
			},
			{
				Name:    "hintevent_timestamp",
				Unique:  false,
				Columns: []*schema.Column{HintEventsColumns[2]},
			},
			{
				Name:    "hintevent_session_id",
				Unique:  false,
				Columns: []*schema.Column{HintEventsColumns[3]},
			},
			{
				Name:    "hintevent_skill_id",
				Unique:  false,
				Columns: []*schema.Column{HintEventsColumns[4]},
			},
		},
	}
	// LlmRequestEventsColumns holds the columns for the "llm_request_events" table.
	LlmRequestEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sequence", Type: field.TypeInt64, Unique: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "provider", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "purpose", Type: field.TypeString},
		{Name: "input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "output_tokens", Type: field.TypeInt, Default: 0},
		{Name: "latency_ms", Type: field.TypeInt64, Default: 0},
		{Name: "success", Type: field.TypeBool},
		{Name: "error_message", Type: field.TypeString, Default: ""},
		{Name: "request_body", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "response_body", Type: field.TypeString, Size: 2147483647, Default: ""},
	}
	// LlmRequestEventsTable holds the schema information for the "llm_request_events" table.
	LlmRequestEventsTable = &schema.Table{
		Name:       "llm_request_events",
		Columns:    LlmRequestEventsColumns,
		PrimaryKey: []*schema.Column{LlmRequestEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "llmrequestevent_sequence",
				Unique:  false,
				Columns: []*schema.Column{LlmRequestEventsColumns[1]},
			},
			{
				Name:    "llmrequestevent_timestamp",
				Unique:  false,
				Columns: []*schema.Column{LlmRequestEventsColumns[2]},
			},
			{
				Name:    "llmrequestevent_provider",
				Unique:  false,
				Columns: []*schema.Column{LlmRequestEventsColumns[3]},
			},
			{
				Name:    "llmrequestevent_purpose",
				Unique:  false,
				Columns: []*schema.Column{LlmRequestEventsColumns[5]},
			},
			{
				Name:    "llmrequestevent_success",
				Unique:  false,
				Columns: []*schema.Column{LlmRequestEventsColumns[9]},
			},
		},
	}
	// LessonEventsColumns holds the columns for the "lesson_events" table.
	LessonEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sequence", Type: field.TypeInt64, Unique: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "session_id", Type: field.TypeString},
		{Name: "skill_id", Type: field.TypeString},
		{Name: "lesson_title", Type: field.TypeString},
		{Name: "practice_attempted", Type: field.TypeBool},
		{Name: "practice_correct", Type: field.TypeBool},
		{Name: "practice_skipped", Type: field.TypeBool},
	}
	// LessonEventsTable holds the schema information for the "lesson_events" table.
	LessonEventsTable = &schema.Table{
		Name:       "lesson_events",
		Columns:    LessonEventsColumns,
		PrimaryKey: []*schema.Column{LessonEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "lessonevent_sequence",
				Unique:  false,
				Columns: []*schema.Column{LessonEventsColumns[1]},
			},
			{
				Name:    "lessonevent_timestamp",
				Unique:  false,
				Columns: []*schema.Column{LessonEventsColumns[2]},
			},
			{
				Name:    "lessonevent_session_id",
				Unique:  false,
				Columns: []*schema.Column{LessonEventsColumns[3]},
			},
			{
				Name:    "lessonevent_skill_id",
				Unique:  false,
				Columns: []*schema.Column{LessonEventsColumns[4]},
			},
		},
	}
	// MasteryEventsColumns holds the columns for the "mastery_events" table.
	MasteryEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sequence", Type: field.TypeInt64, Unique: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "skill_id", Type: field.TypeString},
		{Name: "from_state", Type: field.TypeString},
		{Name: "to_state", Type: field.TypeString},
		{Name: "trigger", Type: field.TypeString},
		{Name: "fluency_score", Type: field.TypeFloat64},
		{Name: "session_id", Type: field.TypeString, Nullable: true},
	}
	// MasteryEventsTable holds the schema information for the "mastery_events" table.
	MasteryEventsTable = &schema.Table{
		Name:       "mastery_events",
		Columns:    MasteryEventsColumns,
		PrimaryKey: []*schema.Column{MasteryEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "masteryevent_sequence",
				Unique:  false,
				Columns: []*schema.Column{MasteryEventsColumns[1]},
			},
			{
				Name:    "masteryevent_timestamp",
				Unique:  false,
				Columns: []*schema.Column{MasteryEventsColumns[2]},
			},
			{
				Name:    "masteryevent_skill_id",
				Unique:  false,
				Columns: []*schema.Column{MasteryEventsColumns[3]},
			},
		},
	}
	// SessionEventsColumns holds the columns for the "session_events" table.
	SessionEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sequence", Type: field.TypeInt64, Unique: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "session_id", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "questions_served", Type: field.TypeInt, Default: 0},
		{Name: "correct_answers", Type: field.TypeInt, Default: 0},
		{Name: "duration_secs", Type: field.TypeInt, Default: 0},
		{Name: "plan_summary", Type: field.TypeJSON, Nullable: true},
	}
	// SessionEventsTable holds the schema information for the "session_events" table.
	SessionEventsTable = &schema.Table{
		Name:       "session_events",
		Columns:    SessionEventsColumns,
		PrimaryKey: []*schema.Column{SessionEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sessionevent_sequence",
				Unique:  false,
				Columns: []*schema.Column{SessionEventsColumns[1]},
			},
			{
				Name:    "sessionevent_timestamp",
				Unique:  false,
				Columns: []*schema.Column{SessionEventsColumns[2]},
			},
			{
				Name:    "sessionevent_session_id",
				Unique:  false,
				Columns: []*schema.Column{SessionEventsColumns[3]},
			},
			{
				Name:    "sessionevent_action",
				Unique:  false,
				Columns: []*schema.Column{SessionEventsColumns[4]},
			},
		},
	}
	// SnapshotsColumns holds the columns for the "snapshots" table.
	SnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sequence", Type: field.TypeInt64},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "data", Type: field.TypeJSON},
	}
	// SnapshotsTable holds the schema information for the "snapshots" table.
	SnapshotsTable = &schema.Table{
		Name:       "snapshots",
		Columns:    SnapshotsColumns,
		PrimaryKey: []*schema.Column{SnapshotsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "snapshot_timestamp",
				Unique:  false,
				Columns: []*schema.Column{SnapshotsColumns[2]},
			},
			{
				Name:    "snapshot_sequence",
				Unique:  false,
				Columns: []*schema.Column{SnapshotsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnswerEventsTable,
		DiagnosisEventsTable,
		GemEventsTable,
		HintEventsTable,
		LlmRequestEventsTable,
		LessonEventsTable,
		MasteryEventsTable,
		SessionEventsTable,
		SnapshotsTable,
	}
)

func init() {
}
