// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/abhisek/mathiz/ent/answerevent"
)

// AnswerEventCreate is the builder for creating a AnswerEvent entity.
type AnswerEventCreate struct {
	config
	mutation *AnswerEventMutation
	hooks    []Hook
}

// SetSequence sets the "sequence" field.
func (_c *AnswerEventCreate) SetSequence(v int64) *AnswerEventCreate {
	_c.mutation.SetSequence(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *AnswerEventCreate) SetTimestamp(v time.Time) *AnswerEventCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *AnswerEventCreate) SetNillableTimestamp(v *time.Time) *AnswerEventCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *AnswerEventCreate) SetSessionID(v string) *AnswerEventCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetSkillID sets the "skill_id" field.
func (_c *AnswerEventCreate) SetSkillID(v string) *AnswerEventCreate {
	_c.mutation.SetSkillID(v)
	return _c
}

// SetTier sets the "tier" field.
func (_c *AnswerEventCreate) SetTier(v string) *AnswerEventCreate {
	_c.mutation.SetTier(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *AnswerEventCreate) SetCategory(v string) *AnswerEventCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetQuestionText sets the "question_text" field.
func (_c *AnswerEventCreate) SetQuestionText(v string) *AnswerEventCreate {
	_c.mutation.SetQuestionText(v)
	return _c
}

// SetCorrectAnswer sets the "correct_answer" field.
func (_c *AnswerEventCreate) SetCorrectAnswer(v string) *AnswerEventCreate {
	_c.mutation.SetCorrectAnswer(v)
	return _c
}

// SetLearnerAnswer sets the "learner_answer" field.
func (_c *AnswerEventCreate) SetLearnerAnswer(v string) *AnswerEventCreate {
	_c.mutation.SetLearnerAnswer(v)
	return _c
}

// SetCorrect sets the "correct" field.
func (_c *AnswerEventCreate) SetCorrect(v bool) *AnswerEventCreate {
	_c.mutation.SetCorrect(v)
	return _c
}

// SetTimeMs sets the "time_ms" field.
func (_c *AnswerEventCreate) SetTimeMs(v int) *AnswerEventCreate {
	_c.mutation.SetTimeMs(v)
	return _c
}

// SetAnswerFormat sets the "answer_format" field.
func (_c *AnswerEventCreate) SetAnswerFormat(v string) *AnswerEventCreate {
	_c.mutation.SetAnswerFormat(v)
	return _c
}

// Mutation returns the AnswerEventMutation object of the builder.
func (_c *AnswerEventCreate) Mutation() *AnswerEventMutation {
	return _c.mutation
}

// Save creates the AnswerEvent in the database.
func (_c *AnswerEventCreate) Save(ctx context.Context) (*AnswerEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnswerEventCreate) SaveX(ctx context.Context) *AnswerEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnswerEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnswerEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnswerEventCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := answerevent.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnswerEventCreate) check() error {
	if _, ok := _c.mutation.Sequence(); !ok {
		return &ValidationError{Name: "sequence", err: errors.New(`ent: missing required field "AnswerEvent.sequence"`)}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "AnswerEvent.timestamp"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "AnswerEvent.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := answerevent.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AnswerEvent.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SkillID(); !ok {
		return &ValidationError{Name: "skill_id", err: errors.New(`ent: missing required field "AnswerEvent.skill_id"`)}
	}
	if v, ok := _c.mutation.SkillID(); ok {
		if err := answerevent.SkillIDValidator(v); err != nil {
			return &ValidationError{Name: "skill_id", err: fmt.Errorf(`ent: validator failed for field "AnswerEvent.skill_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Tier(); !ok {
		return &ValidationError{Name: "tier", err: errors.New(`ent: missing required field "AnswerEvent.tier"`)}
	}
	if v, ok := _c.mutation.Tier(); ok {
		if err := answerevent.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`ent: validator failed for field "AnswerEvent.tier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "AnswerEvent.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := answerevent.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "AnswerEvent.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QuestionText(); !ok {
		return &ValidationError{Name: "question_text", err: errors.New(`ent: missing required field "AnswerEvent.question_text"`)}
	}
	if v, ok := _c.mutation.QuestionText(); ok {
		if err := answerevent.QuestionTextValidator(v); err != nil {
			return &ValidationError{Name: "question_text", err: fmt.Errorf(`ent: validator failed for field "AnswerEvent.question_text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CorrectAnswer(); !ok {
		return &ValidationError{Name: "correct_answer", err: errors.New(`ent: missing required field "AnswerEvent.correct_answer"`)}
	}
	if v, ok := _c.mutation.CorrectAnswer(); ok {
		if err := answerevent.CorrectAnswerValidator(v); err != nil {
			return &ValidationError{Name: "correct_answer", err: fmt.Errorf(`ent: validator failed for field "AnswerEvent.correct_answer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LearnerAnswer(); !ok {
		return &ValidationError{Name: "learner_answer", err: errors.New(`ent: missing required field "AnswerEvent.learner_answer"`)}
	}
	if v, ok := _c.mutation.LearnerAnswer(); ok {
		if err := answerevent.LearnerAnswerValidator(v); err != nil {
			return &ValidationError{Name: "learner_answer", err: fmt.Errorf(`ent: validator failed for field "AnswerEvent.learner_answer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Correct(); !ok {
		return &ValidationError{Name: "correct", err: errors.New(`ent: missing required field "AnswerEvent.correct"`)}
	}
	if _, ok := _c.mutation.TimeMs(); !ok {
		return &ValidationError{Name: "time_ms", err: errors.New(`ent: missing required field "AnswerEvent.time_ms"`)}
	}
	if _, ok := _c.mutation.AnswerFormat(); !ok {
		return &ValidationError{Name: "answer_format", err: errors.New(`ent: missing required field "AnswerEvent.answer_format"`)}
	}
	if v, ok := _c.mutation.AnswerFormat(); ok {
		if err := answerevent.AnswerFormatValidator(v); err != nil {
			return &ValidationError{Name: "answer_format", err: fmt.Errorf(`ent: validator failed for field "AnswerEvent.answer_format": %w`, err)}
		}
	}
	return nil
}

func (_c *AnswerEventCreate) sqlSave(ctx context.Context) (*AnswerEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnswerEventCreate) createSpec() (*AnswerEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AnswerEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(answerevent.Table, sqlgraph.NewFieldSpec(answerevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Sequence(); ok {
		_spec.SetField(answerevent.FieldSequence, field.TypeInt64, value)
		_node.Sequence = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(answerevent.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(answerevent.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.SkillID(); ok {
		_spec.SetField(answerevent.FieldSkillID, field.TypeString, value)
		_node.SkillID = value
	}
	if value, ok := _c.mutation.Tier(); ok {
		_spec.SetField(answerevent.FieldTier, field.TypeString, value)
		_node.Tier = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(answerevent.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.QuestionText(); ok {
		_spec.SetField(answerevent.FieldQuestionText, field.TypeString, value)
		_node.QuestionText = value
	}
	if value, ok := _c.mutation.CorrectAnswer(); ok {
		_spec.SetField(answerevent.FieldCorrectAnswer, field.TypeString, value)
		_node.CorrectAnswer = value
	}
	if value, ok := _c.mutation.LearnerAnswer(); ok {
		_spec.SetField(answerevent.FieldLearnerAnswer, field.TypeString, value)
		_node.LearnerAnswer = value
	}
	if value, ok := _c.mutation.Correct(); ok {
		_spec.SetField(answerevent.FieldCorrect, field.TypeBool, value)
		_node.Correct = value
	}
	if value, ok := _c.mutation.TimeMs(); ok {
		_spec.SetField(answerevent.FieldTimeMs, field.TypeInt, value)
		_node.TimeMs = value
	}
	if value, ok := _c.mutation.AnswerFormat(); ok {
		_spec.SetField(answerevent.FieldAnswerFormat, field.TypeString, value)
		_node.AnswerFormat = value
	}
	return _node, _spec
}

// AnswerEventCreateBulk is the builder for creating many AnswerEvent entities in bulk.
type AnswerEventCreateBulk struct {
	config
	err      error
	builders []*AnswerEventCreate
}

// Save creates the AnswerEvent entities in the database.
func (_c *AnswerEventCreateBulk) Save(ctx context.Context) ([]*AnswerEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AnswerEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnswerEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnswerEventCreateBulk) SaveX(ctx context.Context) []*AnswerEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnswerEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnswerEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
