// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/abhisek/mathiz/ent/billingstate"
)

// BillingStateCreate is the builder for creating a BillingState entity.
type BillingStateCreate struct {
	config
	mutation *BillingStateMutation
	hooks    []Hook
}

// SetUID sets the "uid" field.
func (_c *BillingStateCreate) SetUID(v string) *BillingStateCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetFamilySpaceID sets the "family_space_id" field.
func (_c *BillingStateCreate) SetFamilySpaceID(v string) *BillingStateCreate {
	_c.mutation.SetFamilySpaceID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *BillingStateCreate) SetProvider(v string) *BillingStateCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *BillingStateCreate) SetNillableProvider(v *string) *BillingStateCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetCustomerID sets the "customer_id" field.
func (_c *BillingStateCreate) SetCustomerID(v string) *BillingStateCreate {
	_c.mutation.SetCustomerID(v)
	return _c
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_c *BillingStateCreate) SetNillableCustomerID(v *string) *BillingStateCreate {
	if v != nil {
		_c.SetCustomerID(*v)
	}
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *BillingStateCreate) SetSubscriptionID(v string) *BillingStateCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_c *BillingStateCreate) SetNillableSubscriptionID(v *string) *BillingStateCreate {
	if v != nil {
		_c.SetSubscriptionID(*v)
	}
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *BillingStateCreate) SetPlanID(v string) *BillingStateCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_c *BillingStateCreate) SetNillablePlanID(v *string) *BillingStateCreate {
	if v != nil {
		_c.SetPlanID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BillingStateCreate) SetStatus(v string) *BillingStateCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BillingStateCreate) SetNillableStatus(v *string) *BillingStateCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_c *BillingStateCreate) SetCurrentPeriodEnd(v time.Time) *BillingStateCreate {
	_c.mutation.SetCurrentPeriodEnd(v)
	return _c
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_c *BillingStateCreate) SetNillableCurrentPeriodEnd(v *time.Time) *BillingStateCreate {
	if v != nil {
		_c.SetCurrentPeriodEnd(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BillingStateCreate) SetUpdatedAt(v time.Time) *BillingStateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BillingStateCreate) SetNillableUpdatedAt(v *time.Time) *BillingStateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the BillingStateMutation object of the builder.
func (_c *BillingStateCreate) Mutation() *BillingStateMutation {
	return _c.mutation
}

// Save creates the BillingState in the database.
func (_c *BillingStateCreate) Save(ctx context.Context) (*BillingState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BillingStateCreate) SaveX(ctx context.Context) *BillingState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillingStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillingStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BillingStateCreate) defaults() {
	if _, ok := _c.mutation.Provider(); !ok {
		v := billingstate.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.CustomerID(); !ok {
		v := billingstate.DefaultCustomerID
		_c.mutation.SetCustomerID(v)
	}
	if _, ok := _c.mutation.SubscriptionID(); !ok {
		v := billingstate.DefaultSubscriptionID
		_c.mutation.SetSubscriptionID(v)
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		v := billingstate.DefaultPlanID
		_c.mutation.SetPlanID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := billingstate.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := billingstate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BillingStateCreate) check() error {
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "BillingState.uid"`)}
	}
	if _, ok := _c.mutation.FamilySpaceID(); !ok {
		return &ValidationError{Name: "family_space_id", err: errors.New(`ent: missing required field "BillingState.family_space_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "BillingState.provider"`)}
	}
	if _, ok := _c.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`ent: missing required field "BillingState.customer_id"`)}
	}
	if _, ok := _c.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "BillingState.subscription_id"`)}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "BillingState.plan_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BillingState.status"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BillingState.updated_at"`)}
	}
	return nil
}

func (_c *BillingStateCreate) sqlSave(ctx context.Context) (*BillingState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BillingStateCreate) createSpec() (*BillingState, *sqlgraph.CreateSpec) {
	var (
		_node = &BillingState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(billingstate.Table, sqlgraph.NewFieldSpec(billingstate.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(billingstate.FieldUID, field.TypeString, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.FamilySpaceID(); ok {
		_spec.SetField(billingstate.FieldFamilySpaceID, field.TypeString, value)
		_node.FamilySpaceID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(billingstate.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.CustomerID(); ok {
		_spec.SetField(billingstate.FieldCustomerID, field.TypeString, value)
		_node.CustomerID = value
	}
	if value, ok := _c.mutation.SubscriptionID(); ok {
		_spec.SetField(billingstate.FieldSubscriptionID, field.TypeString, value)
		_node.SubscriptionID = value
	}
	if value, ok := _c.mutation.PlanID(); ok {
		_spec.SetField(billingstate.FieldPlanID, field.TypeString, value)
		_node.PlanID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(billingstate.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(billingstate.FieldCurrentPeriodEnd, field.TypeTime, value)
		_node.CurrentPeriodEnd = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(billingstate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// BillingStateCreateBulk is the builder for creating many BillingState entities in bulk.
type BillingStateCreateBulk struct {
	config
	err      error
	builders []*BillingStateCreate
}

// Save creates the BillingState entities in the database.
func (_c *BillingStateCreateBulk) Save(ctx context.Context) ([]*BillingState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BillingState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BillingStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BillingStateCreateBulk) SaveX(ctx context.Context) []*BillingState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillingStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillingStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
