// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/abhisek/mathiz/ent/devicetoken"
)

// DeviceTokenCreate is the builder for creating a DeviceToken entity.
type DeviceTokenCreate struct {
	config
	mutation *DeviceTokenMutation
	hooks    []Hook
}

// SetUID sets the "uid" field.
func (_c *DeviceTokenCreate) SetUID(v string) *DeviceTokenCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetChildProfileID sets the "child_profile_id" field.
func (_c *DeviceTokenCreate) SetChildProfileID(v string) *DeviceTokenCreate {
	_c.mutation.SetChildProfileID(v)
	return _c
}

// SetFamilySpaceID sets the "family_space_id" field.
func (_c *DeviceTokenCreate) SetFamilySpaceID(v string) *DeviceTokenCreate {
	_c.mutation.SetFamilySpaceID(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *DeviceTokenCreate) SetTokenHash(v string) *DeviceTokenCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetDeviceLabel sets the "device_label" field.
func (_c *DeviceTokenCreate) SetDeviceLabel(v string) *DeviceTokenCreate {
	_c.mutation.SetDeviceLabel(v)
	return _c
}

// SetNillableDeviceLabel sets the "device_label" field if the given value is not nil.
func (_c *DeviceTokenCreate) SetNillableDeviceLabel(v *string) *DeviceTokenCreate {
	if v != nil {
		_c.SetDeviceLabel(*v)
	}
	return _c
}

// SetRevoked sets the "revoked" field.
func (_c *DeviceTokenCreate) SetRevoked(v bool) *DeviceTokenCreate {
	_c.mutation.SetRevoked(v)
	return _c
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_c *DeviceTokenCreate) SetNillableRevoked(v *bool) *DeviceTokenCreate {
	if v != nil {
		_c.SetRevoked(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *DeviceTokenCreate) SetLastUsedAt(v time.Time) *DeviceTokenCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *DeviceTokenCreate) SetNillableLastUsedAt(v *time.Time) *DeviceTokenCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeviceTokenCreate) SetCreatedAt(v time.Time) *DeviceTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeviceTokenCreate) SetNillableCreatedAt(v *time.Time) *DeviceTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the DeviceTokenMutation object of the builder.
func (_c *DeviceTokenCreate) Mutation() *DeviceTokenMutation {
	return _c.mutation
}

// Save creates the DeviceToken in the database.
func (_c *DeviceTokenCreate) Save(ctx context.Context) (*DeviceToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceTokenCreate) SaveX(ctx context.Context) *DeviceToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceTokenCreate) defaults() {
	if _, ok := _c.mutation.DeviceLabel(); !ok {
		v := devicetoken.DefaultDeviceLabel
		_c.mutation.SetDeviceLabel(v)
	}
	if _, ok := _c.mutation.Revoked(); !ok {
		v := devicetoken.DefaultRevoked
		_c.mutation.SetRevoked(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := devicetoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceTokenCreate) check() error {
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "DeviceToken.uid"`)}
	}
	if _, ok := _c.mutation.ChildProfileID(); !ok {
		return &ValidationError{Name: "child_profile_id", err: errors.New(`ent: missing required field "DeviceToken.child_profile_id"`)}
	}
	if _, ok := _c.mutation.FamilySpaceID(); !ok {
		return &ValidationError{Name: "family_space_id", err: errors.New(`ent: missing required field "DeviceToken.family_space_id"`)}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "DeviceToken.token_hash"`)}
	}
	if _, ok := _c.mutation.DeviceLabel(); !ok {
		return &ValidationError{Name: "device_label", err: errors.New(`ent: missing required field "DeviceToken.device_label"`)}
	}
	if _, ok := _c.mutation.Revoked(); !ok {
		return &ValidationError{Name: "revoked", err: errors.New(`ent: missing required field "DeviceToken.revoked"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeviceToken.created_at"`)}
	}
	return nil
}

func (_c *DeviceTokenCreate) sqlSave(ctx context.Context) (*DeviceToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceTokenCreate) createSpec() (*DeviceToken, *sqlgraph.CreateSpec) {
	var (
		_node = &DeviceToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(devicetoken.Table, sqlgraph.NewFieldSpec(devicetoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(devicetoken.FieldUID, field.TypeString, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.ChildProfileID(); ok {
		_spec.SetField(devicetoken.FieldChildProfileID, field.TypeString, value)
		_node.ChildProfileID = value
	}
	if value, ok := _c.mutation.FamilySpaceID(); ok {
		_spec.SetField(devicetoken.FieldFamilySpaceID, field.TypeString, value)
		_node.FamilySpaceID = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(devicetoken.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.DeviceLabel(); ok {
		_spec.SetField(devicetoken.FieldDeviceLabel, field.TypeString, value)
		_node.DeviceLabel = value
	}
	if value, ok := _c.mutation.Revoked(); ok {
		_spec.SetField(devicetoken.FieldRevoked, field.TypeBool, value)
		_node.Revoked = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(devicetoken.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(devicetoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// DeviceTokenCreateBulk is the builder for creating many DeviceToken entities in bulk.
type DeviceTokenCreateBulk struct {
	config
	err      error
	builders []*DeviceTokenCreate
}

// Save creates the DeviceToken entities in the database.
func (_c *DeviceTokenCreateBulk) Save(ctx context.Context) ([]*DeviceToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeviceToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceTokenCreateBulk) SaveX(ctx context.Context) []*DeviceToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
