// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/abhisek/mathiz/ent/diagnosisevent"
)

// DiagnosisEventCreate is the builder for creating a DiagnosisEvent entity.
type DiagnosisEventCreate struct {
	config
	mutation *DiagnosisEventMutation
	hooks    []Hook
}

// SetSequence sets the "sequence" field.
func (_c *DiagnosisEventCreate) SetSequence(v int64) *DiagnosisEventCreate {
	_c.mutation.SetSequence(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *DiagnosisEventCreate) SetTimestamp(v time.Time) *DiagnosisEventCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *DiagnosisEventCreate) SetNillableTimestamp(v *time.Time) *DiagnosisEventCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *DiagnosisEventCreate) SetSessionID(v string) *DiagnosisEventCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetSkillID sets the "skill_id" field.
func (_c *DiagnosisEventCreate) SetSkillID(v string) *DiagnosisEventCreate {
	_c.mutation.SetSkillID(v)
	return _c
}

// SetQuestionText sets the "question_text" field.
func (_c *DiagnosisEventCreate) SetQuestionText(v string) *DiagnosisEventCreate {
	_c.mutation.SetQuestionText(v)
	return _c
}

// SetCorrectAnswer sets the "correct_answer" field.
func (_c *DiagnosisEventCreate) SetCorrectAnswer(v string) *DiagnosisEventCreate {
	_c.mutation.SetCorrectAnswer(v)
	return _c
}

// SetLearnerAnswer sets the "learner_answer" field.
func (_c *DiagnosisEventCreate) SetLearnerAnswer(v string) *DiagnosisEventCreate {
	_c.mutation.SetLearnerAnswer(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *DiagnosisEventCreate) SetCategory(v string) *DiagnosisEventCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetMisconceptionID sets the "misconception_id" field.
func (_c *DiagnosisEventCreate) SetMisconceptionID(v string) *DiagnosisEventCreate {
	_c.mutation.SetMisconceptionID(v)
	return _c
}

// SetNillableMisconceptionID sets the "misconception_id" field if the given value is not nil.
func (_c *DiagnosisEventCreate) SetNillableMisconceptionID(v *string) *DiagnosisEventCreate {
	if v != nil {
		_c.SetMisconceptionID(*v)
	}
	return _c
}

// SetConfidence sets the "confidence" field.
func (_c *DiagnosisEventCreate) SetConfidence(v float64) *DiagnosisEventCreate {
	_c.mutation.SetConfidence(v)
	return _c
}

// SetClassifierName sets the "classifier_name" field.
func (_c *DiagnosisEventCreate) SetClassifierName(v string) *DiagnosisEventCreate {
	_c.mutation.SetClassifierName(v)
	return _c
}

// SetReasoning sets the "reasoning" field.
func (_c *DiagnosisEventCreate) SetReasoning(v string) *DiagnosisEventCreate {
	_c.mutation.SetReasoning(v)
	return _c
}

// SetNillableReasoning sets the "reasoning" field if the given value is not nil.
func (_c *DiagnosisEventCreate) SetNillableReasoning(v *string) *DiagnosisEventCreate {
	if v != nil {
		_c.SetReasoning(*v)
	}
	return _c
}

// Mutation returns the DiagnosisEventMutation object of the builder.
func (_c *DiagnosisEventCreate) Mutation() *DiagnosisEventMutation {
	return _c.mutation
}

// Save creates the DiagnosisEvent in the database.
func (_c *DiagnosisEventCreate) Save(ctx context.Context) (*DiagnosisEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiagnosisEventCreate) SaveX(ctx context.Context) *DiagnosisEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiagnosisEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiagnosisEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DiagnosisEventCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := diagnosisevent.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
	if _, ok := _c.mutation.Reasoning(); !ok {
		v := diagnosisevent.DefaultReasoning
		_c.mutation.SetReasoning(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiagnosisEventCreate) check() error {
	if _, ok := _c.mutation.Sequence(); !ok {
		return &ValidationError{Name: "sequence", err: errors.New(`ent: missing required field "DiagnosisEvent.sequence"`)}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "DiagnosisEvent.timestamp"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "DiagnosisEvent.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := diagnosisevent.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "DiagnosisEvent.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SkillID(); !ok {
		return &ValidationError{Name: "skill_id", err: errors.New(`ent: missing required field "DiagnosisEvent.skill_id"`)}
	}
	if v, ok := _c.mutation.SkillID(); ok {
		if err := diagnosisevent.SkillIDValidator(v); err != nil {
			return &ValidationError{Name: "skill_id", err: fmt.Errorf(`ent: validator failed for field "DiagnosisEvent.skill_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QuestionText(); !ok {
		return &ValidationError{Name: "question_text", err: errors.New(`ent: missing required field "DiagnosisEvent.question_text"`)}
	}
	if v, ok := _c.mutation.QuestionText(); ok {
		if err := diagnosisevent.QuestionTextValidator(v); err != nil {
			return &ValidationError{Name: "question_text", err: fmt.Errorf(`ent: validator failed for field "DiagnosisEvent.question_text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CorrectAnswer(); !ok {
		return &ValidationError{Name: "correct_answer", err: errors.New(`ent: missing required field "DiagnosisEvent.correct_answer"`)}
	}
	if v, ok := _c.mutation.CorrectAnswer(); ok {
		if err := diagnosisevent.CorrectAnswerValidator(v); err != nil {
			return &ValidationError{Name: "correct_answer", err: fmt.Errorf(`ent: validator failed for field "DiagnosisEvent.correct_answer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LearnerAnswer(); !ok {
		return &ValidationError{Name: "learner_answer", err: errors.New(`ent: missing required field "DiagnosisEvent.learner_answer"`)}
	}
	if v, ok := _c.mutation.LearnerAnswer(); ok {
		if err := diagnosisevent.LearnerAnswerValidator(v); err != nil {
			return &ValidationError{Name: "learner_answer", err: fmt.Errorf(`ent: validator failed for field "DiagnosisEvent.learner_answer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "DiagnosisEvent.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := diagnosisevent.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "DiagnosisEvent.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		return &ValidationError{Name: "confidence", err: errors.New(`ent: missing required field "DiagnosisEvent.confidence"`)}
	}
	if _, ok := _c.mutation.ClassifierName(); !ok {
		return &ValidationError{Name: "classifier_name", err: errors.New(`ent: missing required field "DiagnosisEvent.classifier_name"`)}
	}
	if v, ok := _c.mutation.ClassifierName(); ok {
		if err := diagnosisevent.ClassifierNameValidator(v); err != nil {
			return &ValidationError{Name: "classifier_name", err: fmt.Errorf(`ent: validator failed for field "DiagnosisEvent.classifier_name": %w`, err)}
		}
	}
	return nil
}

func (_c *DiagnosisEventCreate) sqlSave(ctx context.Context) (*DiagnosisEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiagnosisEventCreate) createSpec() (*DiagnosisEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &DiagnosisEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(diagnosisevent.Table, sqlgraph.NewFieldSpec(diagnosisevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Sequence(); ok {
		_spec.SetField(diagnosisevent.FieldSequence, field.TypeInt64, value)
		_node.Sequence = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(diagnosisevent.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(diagnosisevent.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.SkillID(); ok {
		_spec.SetField(diagnosisevent.FieldSkillID, field.TypeString, value)
		_node.SkillID = value
	}
	if value, ok := _c.mutation.QuestionText(); ok {
		_spec.SetField(diagnosisevent.FieldQuestionText, field.TypeString, value)
		_node.QuestionText = value
	}
	if value, ok := _c.mutation.CorrectAnswer(); ok {
		_spec.SetField(diagnosisevent.FieldCorrectAnswer, field.TypeString, value)
		_node.CorrectAnswer = value
	}
	if value, ok := _c.mutation.LearnerAnswer(); ok {
		_spec.SetField(diagnosisevent.FieldLearnerAnswer, field.TypeString, value)
		_node.LearnerAnswer = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(diagnosisevent.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.MisconceptionID(); ok {
		_spec.SetField(diagnosisevent.FieldMisconceptionID, field.TypeString, value)
		_node.MisconceptionID = &value
	}
	if value, ok := _c.mutation.Confidence(); ok {
		_spec.SetField(diagnosisevent.FieldConfidence, field.TypeFloat64, value)
		_node.Confidence = value
	}
	if value, ok := _c.mutation.ClassifierName(); ok {
		_spec.SetField(diagnosisevent.FieldClassifierName, field.TypeString, value)
		_node.ClassifierName = value
	}
	if value, ok := _c.mutation.Reasoning(); ok {
		_spec.SetField(diagnosisevent.FieldReasoning, field.TypeString, value)
		_node.Reasoning = value
	}
	return _node, _spec
}

// DiagnosisEventCreateBulk is the builder for creating many DiagnosisEvent entities in bulk.
type DiagnosisEventCreateBulk struct {
	config
	err      error
	builders []*DiagnosisEventCreate
}

// Save creates the DiagnosisEvent entities in the database.
func (_c *DiagnosisEventCreateBulk) Save(ctx context.Context) ([]*DiagnosisEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DiagnosisEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiagnosisEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiagnosisEventCreateBulk) SaveX(ctx context.Context) []*DiagnosisEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiagnosisEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiagnosisEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
