// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/abhisek/mathiz/ent/diagnosisevent"
)

// DiagnosisEvent is the model entity for the DiagnosisEvent schema.
type DiagnosisEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Monotonically increasing global sequence number
	Sequence int64 `json:"sequence,omitempty"`
	// UTC wall-clock time of the event
	Timestamp time.Time `json:"timestamp,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// SkillID holds the value of the "skill_id" field.
	SkillID string `json:"skill_id,omitempty"`
	// QuestionText holds the value of the "question_text" field.
	QuestionText string `json:"question_text,omitempty"`
	// CorrectAnswer holds the value of the "correct_answer" field.
	CorrectAnswer string `json:"correct_answer,omitempty"`
	// LearnerAnswer holds the value of the "learner_answer" field.
	LearnerAnswer string `json:"learner_answer,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// MisconceptionID holds the value of the "misconception_id" field.
	MisconceptionID *string `json:"misconception_id,omitempty"`
	// Confidence holds the value of the "confidence" field.
	Confidence float64 `json:"confidence,omitempty"`
	// ClassifierName holds the value of the "classifier_name" field.
	ClassifierName string `json:"classifier_name,omitempty"`
	// Reasoning holds the value of the "reasoning" field.
	Reasoning    string `json:"reasoning,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DiagnosisEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case diagnosisevent.FieldConfidence:
			values[i] = new(sql.NullFloat64)
		case diagnosisevent.FieldID, diagnosisevent.FieldSequence:
			values[i] = new(sql.NullInt64)
		case diagnosisevent.FieldSessionID, diagnosisevent.FieldSkillID, diagnosisevent.FieldQuestionText, diagnosisevent.FieldCorrectAnswer, diagnosisevent.FieldLearnerAnswer, diagnosisevent.FieldCategory, diagnosisevent.FieldMisconceptionID, diagnosisevent.FieldClassifierName, diagnosisevent.FieldReasoning:
			values[i] = new(sql.NullString)
		case diagnosisevent.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DiagnosisEvent fields.
func (_m *DiagnosisEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case diagnosisevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case diagnosisevent.FieldSequence:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sequence", values[i])
			} else if value.Valid {
				_m.Sequence = value.Int64
			}
		case diagnosisevent.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		case diagnosisevent.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case diagnosisevent.FieldSkillID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skill_id", values[i])
			} else if value.Valid {
				_m.SkillID = value.String
			}
		case diagnosisevent.FieldQuestionText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field question_text", values[i])
			} else if value.Valid {
				_m.QuestionText = value.String
			}
		case diagnosisevent.FieldCorrectAnswer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field correct_answer", values[i])
			} else if value.Valid {
				_m.CorrectAnswer = value.String
			}
		case diagnosisevent.FieldLearnerAnswer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field learner_answer", values[i])
			} else if value.Valid {
				_m.LearnerAnswer = value.String
			}
		case diagnosisevent.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case diagnosisevent.FieldMisconceptionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field misconception_id", values[i])
			} else if value.Valid {
				_m.MisconceptionID = new(string)
				*_m.MisconceptionID = value.String
			}
		case diagnosisevent.FieldConfidence:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field confidence", values[i])
			} else if value.Valid {
				_m.Confidence = value.Float64
			}
		case diagnosisevent.FieldClassifierName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field classifier_name", values[i])
			} else if value.Valid {
				_m.ClassifierName = value.String
			}
		case diagnosisevent.FieldReasoning:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning", values[i])
			} else if value.Valid {
				_m.Reasoning = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DiagnosisEvent.
// This includes values selected through modifiers, order, etc.
func (_m *DiagnosisEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DiagnosisEvent.
// Note that you need to call DiagnosisEvent.Unwrap() before calling this method if this DiagnosisEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DiagnosisEvent) Update() *DiagnosisEventUpdateOne {
	return NewDiagnosisEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DiagnosisEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DiagnosisEvent) Unwrap() *DiagnosisEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DiagnosisEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DiagnosisEvent) String() string {
	var builder strings.Builder
	builder.WriteString("DiagnosisEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("sequence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sequence))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("skill_id=")
	builder.WriteString(_m.SkillID)
	builder.WriteString(", ")
	builder.WriteString("question_text=")
	builder.WriteString(_m.QuestionText)
	builder.WriteString(", ")
	builder.WriteString("correct_answer=")
	builder.WriteString(_m.CorrectAnswer)
	builder.WriteString(", ")
	builder.WriteString("learner_answer=")
	builder.WriteString(_m.LearnerAnswer)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	if v := _m.MisconceptionID; v != nil {
		builder.WriteString("misconception_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("confidence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Confidence))
	builder.WriteString(", ")
	builder.WriteString("classifier_name=")
	builder.WriteString(_m.ClassifierName)
	builder.WriteString(", ")
	builder.WriteString("reasoning=")
	builder.WriteString(_m.Reasoning)
	builder.WriteByte(')')
	return builder.String()
}

// DiagnosisEvents is a parsable slice of DiagnosisEvent.
type DiagnosisEvents []*DiagnosisEvent
