// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/abhisek/mathiz/ent/diagnosisevent"
	"github.com/abhisek/mathiz/ent/predicate"
)

// DiagnosisEventDelete is the builder for deleting a DiagnosisEvent entity.
type DiagnosisEventDelete struct {
	config
	hooks    []Hook
	mutation *DiagnosisEventMutation
}

// Where appends a list predicates to the DiagnosisEventDelete builder.
func (_d *DiagnosisEventDelete) Where(ps ...predicate.DiagnosisEvent) *DiagnosisEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DiagnosisEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiagnosisEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DiagnosisEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(diagnosisevent.Table, sqlgraph.NewFieldSpec(diagnosisevent.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DiagnosisEventDeleteOne is the builder for deleting a single DiagnosisEvent entity.
type DiagnosisEventDeleteOne struct {
	_d *DiagnosisEventDelete
}

// Where appends a list predicates to the DiagnosisEventDelete builder.
func (_d *DiagnosisEventDeleteOne) Where(ps ...predicate.DiagnosisEvent) *DiagnosisEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DiagnosisEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{diagnosisevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiagnosisEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
