// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/abhisek/mathiz/ent/familyspace"
	"github.com/abhisek/mathiz/ent/predicate"
)

// FamilySpaceUpdate is the builder for updating FamilySpace entities.
type FamilySpaceUpdate struct {
	config
	hooks    []Hook
	mutation *FamilySpaceMutation
}

// Where appends a list predicates to the FamilySpaceUpdate builder.
func (_u *FamilySpaceUpdate) Where(ps ...predicate.FamilySpace) *FamilySpaceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *FamilySpaceUpdate) SetName(v string) *FamilySpaceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FamilySpaceUpdate) SetNillableName(v *string) *FamilySpaceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the FamilySpaceMutation object of the builder.
func (_u *FamilySpaceUpdate) Mutation() *FamilySpaceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FamilySpaceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FamilySpaceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FamilySpaceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FamilySpaceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FamilySpaceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(familyspace.Table, familyspace.Columns, sqlgraph.NewFieldSpec(familyspace.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(familyspace.FieldName, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{familyspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FamilySpaceUpdateOne is the builder for updating a single FamilySpace entity.
type FamilySpaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FamilySpaceMutation
}

// SetName sets the "name" field.
func (_u *FamilySpaceUpdateOne) SetName(v string) *FamilySpaceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FamilySpaceUpdateOne) SetNillableName(v *string) *FamilySpaceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the FamilySpaceMutation object of the builder.
func (_u *FamilySpaceUpdateOne) Mutation() *FamilySpaceMutation {
	return _u.mutation
}

// Where appends a list predicates to the FamilySpaceUpdate builder.
func (_u *FamilySpaceUpdateOne) Where(ps ...predicate.FamilySpace) *FamilySpaceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FamilySpaceUpdateOne) Select(field string, fields ...string) *FamilySpaceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FamilySpace entity.
func (_u *FamilySpaceUpdateOne) Save(ctx context.Context) (*FamilySpace, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FamilySpaceUpdateOne) SaveX(ctx context.Context) *FamilySpace {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FamilySpaceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FamilySpaceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FamilySpaceUpdateOne) sqlSave(ctx context.Context) (_node *FamilySpace, err error) {
	_spec := sqlgraph.NewUpdateSpec(familyspace.Table, familyspace.Columns, sqlgraph.NewFieldSpec(familyspace.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FamilySpace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, familyspace.FieldID)
		for _, f := range fields {
			if !familyspace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != familyspace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(familyspace.FieldName, field.TypeString, value)
	}
	_node = &FamilySpace{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{familyspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
