// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/abhisek/mathiz/ent/familymember"
)

// FamilyMember is the model entity for the FamilyMember schema.
type FamilyMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Membership ID (UUID)
	UID string `json:"uid,omitempty"`
	// FamilySpaceID holds the value of the "family_space_id" field.
	FamilySpaceID string `json:"family_space_id,omitempty"`
	// Member account UID (unique: one family per account in v1)
	AccountID string `json:"account_id,omitempty"`
	// owner | parent
	Role string `json:"role,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FamilyMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case familymember.FieldID:
			values[i] = new(sql.NullInt64)
		case familymember.FieldUID, familymember.FieldFamilySpaceID, familymember.FieldAccountID, familymember.FieldRole:
			values[i] = new(sql.NullString)
		case familymember.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FamilyMember fields.
func (_m *FamilyMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case familymember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case familymember.FieldUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				_m.UID = value.String
			}
		case familymember.FieldFamilySpaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field family_space_id", values[i])
			} else if value.Valid {
				_m.FamilySpaceID = value.String
			}
		case familymember.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.String
			}
		case familymember.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case familymember.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FamilyMember.
// This includes values selected through modifiers, order, etc.
func (_m *FamilyMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FamilyMember.
// Note that you need to call FamilyMember.Unwrap() before calling this method if this FamilyMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FamilyMember) Update() *FamilyMemberUpdateOne {
	return NewFamilyMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FamilyMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FamilyMember) Unwrap() *FamilyMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FamilyMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FamilyMember) String() string {
	var builder strings.Builder
	builder.WriteString("FamilyMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("uid=")
	builder.WriteString(_m.UID)
	builder.WriteString(", ")
	builder.WriteString("family_space_id=")
	builder.WriteString(_m.FamilySpaceID)
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(_m.AccountID)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FamilyMembers is a parsable slice of FamilyMember.
type FamilyMembers []*FamilyMember
