// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/abhisek/mathiz/ent/gemevent"
	"github.com/abhisek/mathiz/ent/predicate"
)

// GemEventUpdate is the builder for updating GemEvent entities.
type GemEventUpdate struct {
	config
	hooks    []Hook
	mutation *GemEventMutation
}

// Where appends a list predicates to the GemEventUpdate builder.
func (_u *GemEventUpdate) Where(ps ...predicate.GemEvent) *GemEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGemType sets the "gem_type" field.
func (_u *GemEventUpdate) SetGemType(v string) *GemEventUpdate {
	_u.mutation.SetGemType(v)
	return _u
}

// SetNillableGemType sets the "gem_type" field if the given value is not nil.
func (_u *GemEventUpdate) SetNillableGemType(v *string) *GemEventUpdate {
	if v != nil {
		_u.SetGemType(*v)
	}
	return _u
}

// SetRarity sets the "rarity" field.
func (_u *GemEventUpdate) SetRarity(v string) *GemEventUpdate {
	_u.mutation.SetRarity(v)
	return _u
}

// SetNillableRarity sets the "rarity" field if the given value is not nil.
func (_u *GemEventUpdate) SetNillableRarity(v *string) *GemEventUpdate {
	if v != nil {
		_u.SetRarity(*v)
	}
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *GemEventUpdate) SetSkillID(v string) *GemEventUpdate {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *GemEventUpdate) SetNillableSkillID(v *string) *GemEventUpdate {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// ClearSkillID clears the value of the "skill_id" field.
func (_u *GemEventUpdate) ClearSkillID() *GemEventUpdate {
	_u.mutation.ClearSkillID()
	return _u
}

// SetSkillName sets the "skill_name" field.
func (_u *GemEventUpdate) SetSkillName(v string) *GemEventUpdate {
	_u.mutation.SetSkillName(v)
	return _u
}

// SetNillableSkillName sets the "skill_name" field if the given value is not nil.
func (_u *GemEventUpdate) SetNillableSkillName(v *string) *GemEventUpdate {
	if v != nil {
		_u.SetSkillName(*v)
	}
	return _u
}

// ClearSkillName clears the value of the "skill_name" field.
func (_u *GemEventUpdate) ClearSkillName() *GemEventUpdate {
	_u.mutation.ClearSkillName()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *GemEventUpdate) SetSessionID(v string) *GemEventUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *GemEventUpdate) SetNillableSessionID(v *string) *GemEventUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *GemEventUpdate) SetReason(v string) *GemEventUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *GemEventUpdate) SetNillableReason(v *string) *GemEventUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// Mutation returns the GemEventMutation object of the builder.
func (_u *GemEventUpdate) Mutation() *GemEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GemEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GemEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GemEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GemEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GemEventUpdate) check() error {
	if v, ok := _u.mutation.GemType(); ok {
		if err := gemevent.GemTypeValidator(v); err != nil {
			return &ValidationError{Name: "gem_type", err: fmt.Errorf(`ent: validator failed for field "GemEvent.gem_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rarity(); ok {
		if err := gemevent.RarityValidator(v); err != nil {
			return &ValidationError{Name: "rarity", err: fmt.Errorf(`ent: validator failed for field "GemEvent.rarity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := gemevent.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "GemEvent.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := gemevent.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "GemEvent.reason": %w`, err)}
		}
	}
	return nil
}

func (_u *GemEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gemevent.Table, gemevent.Columns, sqlgraph.NewFieldSpec(gemevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GemType(); ok {
		_spec.SetField(gemevent.FieldGemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rarity(); ok {
		_spec.SetField(gemevent.FieldRarity, field.TypeString, value)
	}
	if value, ok := _u.mutation.SkillID(); ok {
		_spec.SetField(gemevent.FieldSkillID, field.TypeString, value)
	}
	if _u.mutation.SkillIDCleared() {
		_spec.ClearField(gemevent.FieldSkillID, field.TypeString)
	}
	if value, ok := _u.mutation.SkillName(); ok {
		_spec.SetField(gemevent.FieldSkillName, field.TypeString, value)
	}
	if _u.mutation.SkillNameCleared() {
		_spec.ClearField(gemevent.FieldSkillName, field.TypeString)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(gemevent.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(gemevent.FieldReason, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gemevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GemEventUpdateOne is the builder for updating a single GemEvent entity.
type GemEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GemEventMutation
}

// SetGemType sets the "gem_type" field.
func (_u *GemEventUpdateOne) SetGemType(v string) *GemEventUpdateOne {
	_u.mutation.SetGemType(v)
	return _u
}

// SetNillableGemType sets the "gem_type" field if the given value is not nil.
func (_u *GemEventUpdateOne) SetNillableGemType(v *string) *GemEventUpdateOne {
	if v != nil {
		_u.SetGemType(*v)
	}
	return _u
}

// SetRarity sets the "rarity" field.
func (_u *GemEventUpdateOne) SetRarity(v string) *GemEventUpdateOne {
	_u.mutation.SetRarity(v)
	return _u
}

// SetNillableRarity sets the "rarity" field if the given value is not nil.
func (_u *GemEventUpdateOne) SetNillableRarity(v *string) *GemEventUpdateOne {
	if v != nil {
		_u.SetRarity(*v)
	}
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *GemEventUpdateOne) SetSkillID(v string) *GemEventUpdateOne {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *GemEventUpdateOne) SetNillableSkillID(v *string) *GemEventUpdateOne {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// ClearSkillID clears the value of the "skill_id" field.
func (_u *GemEventUpdateOne) ClearSkillID() *GemEventUpdateOne {
	_u.mutation.ClearSkillID()
	return _u
}

// SetSkillName sets the "skill_name" field.
func (_u *GemEventUpdateOne) SetSkillName(v string) *GemEventUpdateOne {
	_u.mutation.SetSkillName(v)
	return _u
}

// SetNillableSkillName sets the "skill_name" field if the given value is not nil.
func (_u *GemEventUpdateOne) SetNillableSkillName(v *string) *GemEventUpdateOne {
	if v != nil {
		_u.SetSkillName(*v)
	}
	return _u
}

// ClearSkillName clears the value of the "skill_name" field.
func (_u *GemEventUpdateOne) ClearSkillName() *GemEventUpdateOne {
	_u.mutation.ClearSkillName()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *GemEventUpdateOne) SetSessionID(v string) *GemEventUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *GemEventUpdateOne) SetNillableSessionID(v *string) *GemEventUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *GemEventUpdateOne) SetReason(v string) *GemEventUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *GemEventUpdateOne) SetNillableReason(v *string) *GemEventUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// Mutation returns the GemEventMutation object of the builder.
func (_u *GemEventUpdateOne) Mutation() *GemEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the GemEventUpdate builder.
func (_u *GemEventUpdateOne) Where(ps ...predicate.GemEvent) *GemEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GemEventUpdateOne) Select(field string, fields ...string) *GemEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GemEvent entity.
func (_u *GemEventUpdateOne) Save(ctx context.Context) (*GemEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GemEventUpdateOne) SaveX(ctx context.Context) *GemEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GemEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GemEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GemEventUpdateOne) check() error {
	if v, ok := _u.mutation.GemType(); ok {
		if err := gemevent.GemTypeValidator(v); err != nil {
			return &ValidationError{Name: "gem_type", err: fmt.Errorf(`ent: validator failed for field "GemEvent.gem_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rarity(); ok {
		if err := gemevent.RarityValidator(v); err != nil {
			return &ValidationError{Name: "rarity", err: fmt.Errorf(`ent: validator failed for field "GemEvent.rarity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := gemevent.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "GemEvent.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := gemevent.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "GemEvent.reason": %w`, err)}
		}
	}
	return nil
}

func (_u *GemEventUpdateOne) sqlSave(ctx context.Context) (_node *GemEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gemevent.Table, gemevent.Columns, sqlgraph.NewFieldSpec(gemevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GemEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gemevent.FieldID)
		for _, f := range fields {
			if !gemevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gemevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GemType(); ok {
		_spec.SetField(gemevent.FieldGemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rarity(); ok {
		_spec.SetField(gemevent.FieldRarity, field.TypeString, value)
	}
	if value, ok := _u.mutation.SkillID(); ok {
		_spec.SetField(gemevent.FieldSkillID, field.TypeString, value)
	}
	if _u.mutation.SkillIDCleared() {
		_spec.ClearField(gemevent.FieldSkillID, field.TypeString)
	}
	if value, ok := _u.mutation.SkillName(); ok {
		_spec.SetField(gemevent.FieldSkillName, field.TypeString, value)
	}
	if _u.mutation.SkillNameCleared() {
		_spec.ClearField(gemevent.FieldSkillName, field.TypeString)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(gemevent.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(gemevent.FieldReason, field.TypeString, value)
	}
	_node = &GemEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gemevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
