// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/abhisek/mathiz/ent/lessonevent"
)

// LessonEventCreate is the builder for creating a LessonEvent entity.
type LessonEventCreate struct {
	config
	mutation *LessonEventMutation
	hooks    []Hook
}

// SetSequence sets the "sequence" field.
func (_c *LessonEventCreate) SetSequence(v int64) *LessonEventCreate {
	_c.mutation.SetSequence(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *LessonEventCreate) SetTimestamp(v time.Time) *LessonEventCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *LessonEventCreate) SetNillableTimestamp(v *time.Time) *LessonEventCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *LessonEventCreate) SetSessionID(v string) *LessonEventCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetSkillID sets the "skill_id" field.
func (_c *LessonEventCreate) SetSkillID(v string) *LessonEventCreate {
	_c.mutation.SetSkillID(v)
	return _c
}

// SetLessonTitle sets the "lesson_title" field.
func (_c *LessonEventCreate) SetLessonTitle(v string) *LessonEventCreate {
	_c.mutation.SetLessonTitle(v)
	return _c
}

// SetPracticeAttempted sets the "practice_attempted" field.
func (_c *LessonEventCreate) SetPracticeAttempted(v bool) *LessonEventCreate {
	_c.mutation.SetPracticeAttempted(v)
	return _c
}

// SetPracticeCorrect sets the "practice_correct" field.
func (_c *LessonEventCreate) SetPracticeCorrect(v bool) *LessonEventCreate {
	_c.mutation.SetPracticeCorrect(v)
	return _c
}

// SetPracticeSkipped sets the "practice_skipped" field.
func (_c *LessonEventCreate) SetPracticeSkipped(v bool) *LessonEventCreate {
	_c.mutation.SetPracticeSkipped(v)
	return _c
}

// Mutation returns the LessonEventMutation object of the builder.
func (_c *LessonEventCreate) Mutation() *LessonEventMutation {
	return _c.mutation
}

// Save creates the LessonEvent in the database.
func (_c *LessonEventCreate) Save(ctx context.Context) (*LessonEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LessonEventCreate) SaveX(ctx context.Context) *LessonEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LessonEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LessonEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LessonEventCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := lessonevent.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LessonEventCreate) check() error {
	if _, ok := _c.mutation.Sequence(); !ok {
		return &ValidationError{Name: "sequence", err: errors.New(`ent: missing required field "LessonEvent.sequence"`)}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "LessonEvent.timestamp"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "LessonEvent.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := lessonevent.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "LessonEvent.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SkillID(); !ok {
		return &ValidationError{Name: "skill_id", err: errors.New(`ent: missing required field "LessonEvent.skill_id"`)}
	}
	if v, ok := _c.mutation.SkillID(); ok {
		if err := lessonevent.SkillIDValidator(v); err != nil {
			return &ValidationError{Name: "skill_id", err: fmt.Errorf(`ent: validator failed for field "LessonEvent.skill_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LessonTitle(); !ok {
		return &ValidationError{Name: "lesson_title", err: errors.New(`ent: missing required field "LessonEvent.lesson_title"`)}
	}
	if v, ok := _c.mutation.LessonTitle(); ok {
		if err := lessonevent.LessonTitleValidator(v); err != nil {
			return &ValidationError{Name: "lesson_title", err: fmt.Errorf(`ent: validator failed for field "LessonEvent.lesson_title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PracticeAttempted(); !ok {
		return &ValidationError{Name: "practice_attempted", err: errors.New(`ent: missing required field "LessonEvent.practice_attempted"`)}
	}
	if _, ok := _c.mutation.PracticeCorrect(); !ok {
		return &ValidationError{Name: "practice_correct", err: errors.New(`ent: missing required field "LessonEvent.practice_correct"`)}
	}
	if _, ok := _c.mutation.PracticeSkipped(); !ok {
		return &ValidationError{Name: "practice_skipped", err: errors.New(`ent: missing required field "LessonEvent.practice_skipped"`)}
	}
	return nil
}

func (_c *LessonEventCreate) sqlSave(ctx context.Context) (*LessonEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LessonEventCreate) createSpec() (*LessonEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &LessonEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lessonevent.Table, sqlgraph.NewFieldSpec(lessonevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Sequence(); ok {
		_spec.SetField(lessonevent.FieldSequence, field.TypeInt64, value)
		_node.Sequence = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(lessonevent.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(lessonevent.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.SkillID(); ok {
		_spec.SetField(lessonevent.FieldSkillID, field.TypeString, value)
		_node.SkillID = value
	}
	if value, ok := _c.mutation.LessonTitle(); ok {
		_spec.SetField(lessonevent.FieldLessonTitle, field.TypeString, value)
		_node.LessonTitle = value
	}
	if value, ok := _c.mutation.PracticeAttempted(); ok {
		_spec.SetField(lessonevent.FieldPracticeAttempted, field.TypeBool, value)
		_node.PracticeAttempted = value
	}
	if value, ok := _c.mutation.PracticeCorrect(); ok {
		_spec.SetField(lessonevent.FieldPracticeCorrect, field.TypeBool, value)
		_node.PracticeCorrect = value
	}
	if value, ok := _c.mutation.PracticeSkipped(); ok {
		_spec.SetField(lessonevent.FieldPracticeSkipped, field.TypeBool, value)
		_node.PracticeSkipped = value
	}
	return _node, _spec
}

// LessonEventCreateBulk is the builder for creating many LessonEvent entities in bulk.
type LessonEventCreateBulk struct {
	config
	err      error
	builders []*LessonEventCreate
}

// Save creates the LessonEvent entities in the database.
func (_c *LessonEventCreateBulk) Save(ctx context.Context) ([]*LessonEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LessonEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LessonEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LessonEventCreateBulk) SaveX(ctx context.Context) []*LessonEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LessonEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LessonEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
