// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/abhisek/mathiz/ent/lessonevent"
)

// LessonEvent is the model entity for the LessonEvent schema.
type LessonEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Monotonically increasing global sequence number
	Sequence int64 `json:"sequence,omitempty"`
	// UTC wall-clock time of the event
	Timestamp time.Time `json:"timestamp,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// SkillID holds the value of the "skill_id" field.
	SkillID string `json:"skill_id,omitempty"`
	// LessonTitle holds the value of the "lesson_title" field.
	LessonTitle string `json:"lesson_title,omitempty"`
	// PracticeAttempted holds the value of the "practice_attempted" field.
	PracticeAttempted bool `json:"practice_attempted,omitempty"`
	// PracticeCorrect holds the value of the "practice_correct" field.
	PracticeCorrect bool `json:"practice_correct,omitempty"`
	// PracticeSkipped holds the value of the "practice_skipped" field.
	PracticeSkipped bool `json:"practice_skipped,omitempty"`
	selectValues    sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LessonEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lessonevent.FieldPracticeAttempted, lessonevent.FieldPracticeCorrect, lessonevent.FieldPracticeSkipped:
			values[i] = new(sql.NullBool)
		case lessonevent.FieldID, lessonevent.FieldSequence:
			values[i] = new(sql.NullInt64)
		case lessonevent.FieldSessionID, lessonevent.FieldSkillID, lessonevent.FieldLessonTitle:
			values[i] = new(sql.NullString)
		case lessonevent.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LessonEvent fields.
func (_m *LessonEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lessonevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case lessonevent.FieldSequence:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sequence", values[i])
			} else if value.Valid {
				_m.Sequence = value.Int64
			}
		case lessonevent.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		case lessonevent.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case lessonevent.FieldSkillID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skill_id", values[i])
			} else if value.Valid {
				_m.SkillID = value.String
			}
		case lessonevent.FieldLessonTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lesson_title", values[i])
			} else if value.Valid {
				_m.LessonTitle = value.String
			}
		case lessonevent.FieldPracticeAttempted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field practice_attempted", values[i])
			} else if value.Valid {
				_m.PracticeAttempted = value.Bool
			}
		case lessonevent.FieldPracticeCorrect:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field practice_correct", values[i])
			} else if value.Valid {
				_m.PracticeCorrect = value.Bool
			}
		case lessonevent.FieldPracticeSkipped:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field practice_skipped", values[i])
			} else if value.Valid {
				_m.PracticeSkipped = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LessonEvent.
// This includes values selected through modifiers, order, etc.
func (_m *LessonEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LessonEvent.
// Note that you need to call LessonEvent.Unwrap() before calling this method if this LessonEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LessonEvent) Update() *LessonEventUpdateOne {
	return NewLessonEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LessonEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LessonEvent) Unwrap() *LessonEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LessonEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LessonEvent) String() string {
	var builder strings.Builder
	builder.WriteString("LessonEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("sequence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sequence))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("skill_id=")
	builder.WriteString(_m.SkillID)
	builder.WriteString(", ")
	builder.WriteString("lesson_title=")
	builder.WriteString(_m.LessonTitle)
	builder.WriteString(", ")
	builder.WriteString("practice_attempted=")
	builder.WriteString(fmt.Sprintf("%v", _m.PracticeAttempted))
	builder.WriteString(", ")
	builder.WriteString("practice_correct=")
	builder.WriteString(fmt.Sprintf("%v", _m.PracticeCorrect))
	builder.WriteString(", ")
	builder.WriteString("practice_skipped=")
	builder.WriteString(fmt.Sprintf("%v", _m.PracticeSkipped))
	builder.WriteByte(')')
	return builder.String()
}

// LessonEvents is a parsable slice of LessonEvent.
type LessonEvents []*LessonEvent
