// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/abhisek/mathiz/ent/masteryevent"
)

// MasteryEventCreate is the builder for creating a MasteryEvent entity.
type MasteryEventCreate struct {
	config
	mutation *MasteryEventMutation
	hooks    []Hook
}

// SetSequence sets the "sequence" field.
func (_c *MasteryEventCreate) SetSequence(v int64) *MasteryEventCreate {
	_c.mutation.SetSequence(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *MasteryEventCreate) SetTimestamp(v time.Time) *MasteryEventCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *MasteryEventCreate) SetNillableTimestamp(v *time.Time) *MasteryEventCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetSkillID sets the "skill_id" field.
func (_c *MasteryEventCreate) SetSkillID(v string) *MasteryEventCreate {
	_c.mutation.SetSkillID(v)
	return _c
}

// SetFromState sets the "from_state" field.
func (_c *MasteryEventCreate) SetFromState(v string) *MasteryEventCreate {
	_c.mutation.SetFromState(v)
	return _c
}

// SetToState sets the "to_state" field.
func (_c *MasteryEventCreate) SetToState(v string) *MasteryEventCreate {
	_c.mutation.SetToState(v)
	return _c
}

// SetTrigger sets the "trigger" field.
func (_c *MasteryEventCreate) SetTrigger(v string) *MasteryEventCreate {
	_c.mutation.SetTrigger(v)
	return _c
}

// SetFluencyScore sets the "fluency_score" field.
func (_c *MasteryEventCreate) SetFluencyScore(v float64) *MasteryEventCreate {
	_c.mutation.SetFluencyScore(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *MasteryEventCreate) SetSessionID(v string) *MasteryEventCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_c *MasteryEventCreate) SetNillableSessionID(v *string) *MasteryEventCreate {
	if v != nil {
		_c.SetSessionID(*v)
	}
	return _c
}

// Mutation returns the MasteryEventMutation object of the builder.
func (_c *MasteryEventCreate) Mutation() *MasteryEventMutation {
	return _c.mutation
}

// Save creates the MasteryEvent in the database.
func (_c *MasteryEventCreate) Save(ctx context.Context) (*MasteryEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MasteryEventCreate) SaveX(ctx context.Context) *MasteryEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MasteryEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MasteryEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MasteryEventCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := masteryevent.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MasteryEventCreate) check() error {
	if _, ok := _c.mutation.Sequence(); !ok {
		return &ValidationError{Name: "sequence", err: errors.New(`ent: missing required field "MasteryEvent.sequence"`)}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "MasteryEvent.timestamp"`)}
	}
	if _, ok := _c.mutation.SkillID(); !ok {
		return &ValidationError{Name: "skill_id", err: errors.New(`ent: missing required field "MasteryEvent.skill_id"`)}
	}
	if v, ok := _c.mutation.SkillID(); ok {
		if err := masteryevent.SkillIDValidator(v); err != nil {
			return &ValidationError{Name: "skill_id", err: fmt.Errorf(`ent: validator failed for field "MasteryEvent.skill_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FromState(); !ok {
		return &ValidationError{Name: "from_state", err: errors.New(`ent: missing required field "MasteryEvent.from_state"`)}
	}
	if v, ok := _c.mutation.FromState(); ok {
		if err := masteryevent.FromStateValidator(v); err != nil {
			return &ValidationError{Name: "from_state", err: fmt.Errorf(`ent: validator failed for field "MasteryEvent.from_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ToState(); !ok {
		return &ValidationError{Name: "to_state", err: errors.New(`ent: missing required field "MasteryEvent.to_state"`)}
	}
	if v, ok := _c.mutation.ToState(); ok {
		if err := masteryevent.ToStateValidator(v); err != nil {
			return &ValidationError{Name: "to_state", err: fmt.Errorf(`ent: validator failed for field "MasteryEvent.to_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`ent: missing required field "MasteryEvent.trigger"`)}
	}
	if v, ok := _c.mutation.Trigger(); ok {
		if err := masteryevent.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "MasteryEvent.trigger": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FluencyScore(); !ok {
		return &ValidationError{Name: "fluency_score", err: errors.New(`ent: missing required field "MasteryEvent.fluency_score"`)}
	}
	return nil
}

func (_c *MasteryEventCreate) sqlSave(ctx context.Context) (*MasteryEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MasteryEventCreate) createSpec() (*MasteryEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &MasteryEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(masteryevent.Table, sqlgraph.NewFieldSpec(masteryevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Sequence(); ok {
		_spec.SetField(masteryevent.FieldSequence, field.TypeInt64, value)
		_node.Sequence = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(masteryevent.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.SkillID(); ok {
		_spec.SetField(masteryevent.FieldSkillID, field.TypeString, value)
		_node.SkillID = value
	}
	if value, ok := _c.mutation.FromState(); ok {
		_spec.SetField(masteryevent.FieldFromState, field.TypeString, value)
		_node.FromState = value
	}
	if value, ok := _c.mutation.ToState(); ok {
		_spec.SetField(masteryevent.FieldToState, field.TypeString, value)
		_node.ToState = value
	}
	if value, ok := _c.mutation.Trigger(); ok {
		_spec.SetField(masteryevent.FieldTrigger, field.TypeString, value)
		_node.Trigger = value
	}
	if value, ok := _c.mutation.FluencyScore(); ok {
		_spec.SetField(masteryevent.FieldFluencyScore, field.TypeFloat64, value)
		_node.FluencyScore = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(masteryevent.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	return _node, _spec
}

// MasteryEventCreateBulk is the builder for creating many MasteryEvent entities in bulk.
type MasteryEventCreateBulk struct {
	config
	err      error
	builders []*MasteryEventCreate
}

// Save creates the MasteryEvent entities in the database.
func (_c *MasteryEventCreateBulk) Save(ctx context.Context) ([]*MasteryEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MasteryEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MasteryEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MasteryEventCreateBulk) SaveX(ctx context.Context) []*MasteryEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MasteryEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MasteryEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
