// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/abhisek/mathiz/ent/parentinvite"
)

// ParentInvite is the model entity for the ParentInvite schema.
type ParentInvite struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Parent invite ID (UUID)
	UID string `json:"uid,omitempty"`
	// FamilySpaceID holds the value of the "family_space_id" field.
	FamilySpaceID string `json:"family_space_id,omitempty"`
	// Invitee email, stored lowercased
	Email string `json:"email,omitempty"`
	// pending | accepted | revoked
	Status string `json:"status,omitempty"`
	// Account UID of the inviting owner
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ParentInvite) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case parentinvite.FieldID:
			values[i] = new(sql.NullInt64)
		case parentinvite.FieldUID, parentinvite.FieldFamilySpaceID, parentinvite.FieldEmail, parentinvite.FieldStatus, parentinvite.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case parentinvite.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ParentInvite fields.
func (_m *ParentInvite) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case parentinvite.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case parentinvite.FieldUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				_m.UID = value.String
			}
		case parentinvite.FieldFamilySpaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field family_space_id", values[i])
			} else if value.Valid {
				_m.FamilySpaceID = value.String
			}
		case parentinvite.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case parentinvite.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case parentinvite.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case parentinvite.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ParentInvite.
// This includes values selected through modifiers, order, etc.
func (_m *ParentInvite) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ParentInvite.
// Note that you need to call ParentInvite.Unwrap() before calling this method if this ParentInvite
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ParentInvite) Update() *ParentInviteUpdateOne {
	return NewParentInviteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ParentInvite entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ParentInvite) Unwrap() *ParentInvite {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ParentInvite is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ParentInvite) String() string {
	var builder strings.Builder
	builder.WriteString("ParentInvite(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("uid=")
	builder.WriteString(_m.UID)
	builder.WriteString(", ")
	builder.WriteString("family_space_id=")
	builder.WriteString(_m.FamilySpaceID)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ParentInvites is a parsable slice of ParentInvite.
type ParentInvites []*ParentInvite
