// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/abhisek/mathiz/ent/parentinvite"
)

// ParentInviteCreate is the builder for creating a ParentInvite entity.
type ParentInviteCreate struct {
	config
	mutation *ParentInviteMutation
	hooks    []Hook
}

// SetUID sets the "uid" field.
func (_c *ParentInviteCreate) SetUID(v string) *ParentInviteCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetFamilySpaceID sets the "family_space_id" field.
func (_c *ParentInviteCreate) SetFamilySpaceID(v string) *ParentInviteCreate {
	_c.mutation.SetFamilySpaceID(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *ParentInviteCreate) SetEmail(v string) *ParentInviteCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ParentInviteCreate) SetStatus(v string) *ParentInviteCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ParentInviteCreate) SetNillableStatus(v *string) *ParentInviteCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ParentInviteCreate) SetCreatedBy(v string) *ParentInviteCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ParentInviteCreate) SetCreatedAt(v time.Time) *ParentInviteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ParentInviteCreate) SetNillableCreatedAt(v *time.Time) *ParentInviteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ParentInviteMutation object of the builder.
func (_c *ParentInviteCreate) Mutation() *ParentInviteMutation {
	return _c.mutation
}

// Save creates the ParentInvite in the database.
func (_c *ParentInviteCreate) Save(ctx context.Context) (*ParentInvite, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ParentInviteCreate) SaveX(ctx context.Context) *ParentInvite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ParentInviteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ParentInviteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ParentInviteCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := parentinvite.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := parentinvite.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ParentInviteCreate) check() error {
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "ParentInvite.uid"`)}
	}
	if _, ok := _c.mutation.FamilySpaceID(); !ok {
		return &ValidationError{Name: "family_space_id", err: errors.New(`ent: missing required field "ParentInvite.family_space_id"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "ParentInvite.email"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ParentInvite.status"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "ParentInvite.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ParentInvite.created_at"`)}
	}
	return nil
}

func (_c *ParentInviteCreate) sqlSave(ctx context.Context) (*ParentInvite, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ParentInviteCreate) createSpec() (*ParentInvite, *sqlgraph.CreateSpec) {
	var (
		_node = &ParentInvite{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(parentinvite.Table, sqlgraph.NewFieldSpec(parentinvite.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(parentinvite.FieldUID, field.TypeString, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.FamilySpaceID(); ok {
		_spec.SetField(parentinvite.FieldFamilySpaceID, field.TypeString, value)
		_node.FamilySpaceID = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(parentinvite.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(parentinvite.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(parentinvite.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(parentinvite.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ParentInviteCreateBulk is the builder for creating many ParentInvite entities in bulk.
type ParentInviteCreateBulk struct {
	config
	err      error
	builders []*ParentInviteCreate
}

// Save creates the ParentInvite entities in the database.
func (_c *ParentInviteCreateBulk) Save(ctx context.Context) ([]*ParentInvite, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ParentInvite, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ParentInviteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ParentInviteCreateBulk) SaveX(ctx context.Context) []*ParentInvite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ParentInviteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ParentInviteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
