// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/abhisek/mathiz/ent/predicate"
	"github.com/abhisek/mathiz/ent/quest"
)

// QuestUpdate is the builder for updating Quest entities.
type QuestUpdate struct {
	config
	hooks    []Hook
	mutation *QuestMutation
}

// Where appends a list predicates to the QuestUpdate builder.
func (_u *QuestUpdate) Where(ps ...predicate.Quest) *QuestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *QuestUpdate) SetName(v string) *QuestUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *QuestUpdate) SetNillableName(v *string) *QuestUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmoji sets the "emoji" field.
func (_u *QuestUpdate) SetEmoji(v string) *QuestUpdate {
	_u.mutation.SetEmoji(v)
	return _u
}

// SetNillableEmoji sets the "emoji" field if the given value is not nil.
func (_u *QuestUpdate) SetNillableEmoji(v *string) *QuestUpdate {
	if v != nil {
		_u.SetEmoji(*v)
	}
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *QuestUpdate) SetSkillID(v string) *QuestUpdate {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *QuestUpdate) SetNillableSkillID(v *string) *QuestUpdate {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetChildUID sets the "child_uid" field.
func (_u *QuestUpdate) SetChildUID(v string) *QuestUpdate {
	_u.mutation.SetChildUID(v)
	return _u
}

// SetNillableChildUID sets the "child_uid" field if the given value is not nil.
func (_u *QuestUpdate) SetNillableChildUID(v *string) *QuestUpdate {
	if v != nil {
		_u.SetChildUID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuestUpdate) SetStatus(v string) *QuestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuestUpdate) SetNillableStatus(v *string) *QuestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuestUpdate) SetUpdatedAt(v time.Time) *QuestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the QuestMutation object of the builder.
func (_u *QuestUpdate) Mutation() *QuestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *QuestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(quest.Table, quest.Columns, sqlgraph.NewFieldSpec(quest.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(quest.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Emoji(); ok {
		_spec.SetField(quest.FieldEmoji, field.TypeString, value)
	}
	if value, ok := _u.mutation.SkillID(); ok {
		_spec.SetField(quest.FieldSkillID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChildUID(); ok {
		_spec.SetField(quest.FieldChildUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quest.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuestUpdateOne is the builder for updating a single Quest entity.
type QuestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuestMutation
}

// SetName sets the "name" field.
func (_u *QuestUpdateOne) SetName(v string) *QuestUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *QuestUpdateOne) SetNillableName(v *string) *QuestUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmoji sets the "emoji" field.
func (_u *QuestUpdateOne) SetEmoji(v string) *QuestUpdateOne {
	_u.mutation.SetEmoji(v)
	return _u
}

// SetNillableEmoji sets the "emoji" field if the given value is not nil.
func (_u *QuestUpdateOne) SetNillableEmoji(v *string) *QuestUpdateOne {
	if v != nil {
		_u.SetEmoji(*v)
	}
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *QuestUpdateOne) SetSkillID(v string) *QuestUpdateOne {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *QuestUpdateOne) SetNillableSkillID(v *string) *QuestUpdateOne {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetChildUID sets the "child_uid" field.
func (_u *QuestUpdateOne) SetChildUID(v string) *QuestUpdateOne {
	_u.mutation.SetChildUID(v)
	return _u
}

// SetNillableChildUID sets the "child_uid" field if the given value is not nil.
func (_u *QuestUpdateOne) SetNillableChildUID(v *string) *QuestUpdateOne {
	if v != nil {
		_u.SetChildUID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuestUpdateOne) SetStatus(v string) *QuestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuestUpdateOne) SetNillableStatus(v *string) *QuestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuestUpdateOne) SetUpdatedAt(v time.Time) *QuestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the QuestMutation object of the builder.
func (_u *QuestUpdateOne) Mutation() *QuestMutation {
	return _u.mutation
}

// Where appends a list predicates to the QuestUpdate builder.
func (_u *QuestUpdateOne) Where(ps ...predicate.Quest) *QuestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuestUpdateOne) Select(field string, fields ...string) *QuestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Quest entity.
func (_u *QuestUpdateOne) Save(ctx context.Context) (*Quest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuestUpdateOne) SaveX(ctx context.Context) *Quest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *QuestUpdateOne) sqlSave(ctx context.Context) (_node *Quest, err error) {
	_spec := sqlgraph.NewUpdateSpec(quest.Table, quest.Columns, sqlgraph.NewFieldSpec(quest.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Quest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quest.FieldID)
		for _, f := range fields {
			if !quest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(quest.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Emoji(); ok {
		_spec.SetField(quest.FieldEmoji, field.TypeString, value)
	}
	if value, ok := _u.mutation.SkillID(); ok {
		_spec.SetField(quest.FieldSkillID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChildUID(); ok {
		_spec.SetField(quest.FieldChildUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quest.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Quest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
