// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/abhisek/mathiz/ent/answerevent"
	"github.com/abhisek/mathiz/ent/diagnosisevent"
	"github.com/abhisek/mathiz/ent/gemevent"
	"github.com/abhisek/mathiz/ent/hintevent"
	"github.com/abhisek/mathiz/ent/lessonevent"
	"github.com/abhisek/mathiz/ent/llmrequestevent"
	"github.com/abhisek/mathiz/ent/masteryevent"
	"github.com/abhisek/mathiz/ent/schema"
	"github.com/abhisek/mathiz/ent/sessionevent"
	"github.com/abhisek/mathiz/ent/snapshot"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	answereventMixin := schema.AnswerEvent{}.Mixin()
	answereventMixinFields0 := answereventMixin[0].Fields()
	_ = answereventMixinFields0
	answereventFields := schema.AnswerEvent{}.Fields()
	_ = answereventFields
	// answereventDescTimestamp is the schema descriptor for timestamp field.
	answereventDescTimestamp := answereventMixinFields0[1].Descriptor()
	// answerevent.DefaultTimestamp holds the default value on creation for the timestamp field.
	answerevent.DefaultTimestamp = answereventDescTimestamp.Default.(func() time.Time)
	// answereventDescSessionID is the schema descriptor for session_id field.
	answereventDescSessionID := answereventFields[0].Descriptor()
	// answerevent.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	answerevent.SessionIDValidator = answereventDescSessionID.Validators[0].(func(string) error)
	// answereventDescSkillID is the schema descriptor for skill_id field.
	answereventDescSkillID := answereventFields[1].Descriptor()
	// answerevent.SkillIDValidator is a validator for the "skill_id" field. It is called by the builders before save.
	answerevent.SkillIDValidator = answereventDescSkillID.Validators[0].(func(string) error)
	// answereventDescTier is the schema descriptor for tier field.
	answereventDescTier := answereventFields[2].Descriptor()
	// answerevent.TierValidator is a validator for the "tier" field. It is called by the builders before save.
	answerevent.TierValidator = answereventDescTier.Validators[0].(func(string) error)
	// answereventDescCategory is the schema descriptor for category field.
	answereventDescCategory := answereventFields[3].Descriptor()
	// answerevent.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	answerevent.CategoryValidator = answereventDescCategory.Validators[0].(func(string) error)
	// answereventDescQuestionText is the schema descriptor for question_text field.
	answereventDescQuestionText := answereventFields[4].Descriptor()
	// answerevent.QuestionTextValidator is a validator for the "question_text" field. It is called by the builders before save.
	answerevent.QuestionTextValidator = answereventDescQuestionText.Validators[0].(func(string) error)
	// answereventDescCorrectAnswer is the schema descriptor for correct_answer field.
	answereventDescCorrectAnswer := answereventFields[5].Descriptor()
	// answerevent.CorrectAnswerValidator is a validator for the "correct_answer" field. It is called by the builders before save.
	answerevent.CorrectAnswerValidator = answereventDescCorrectAnswer.Validators[0].(func(string) error)
	// answereventDescLearnerAnswer is the schema descriptor for learner_answer field.
	answereventDescLearnerAnswer := answereventFields[6].Descriptor()
	// answerevent.LearnerAnswerValidator is a validator for the "learner_answer" field. It is called by the builders before save.
	answerevent.LearnerAnswerValidator = answereventDescLearnerAnswer.Validators[0].(func(string) error)
	// answereventDescAnswerFormat is the schema descriptor for answer_format field.
	answereventDescAnswerFormat := answereventFields[9].Descriptor()
	// answerevent.AnswerFormatValidator is a validator for the "answer_format" field. It is called by the builders before save.
	answerevent.AnswerFormatValidator = answereventDescAnswerFormat.Validators[0].(func(string) error)
	diagnosiseventMixin := schema.DiagnosisEvent{}.Mixin()
	diagnosiseventMixinFields0 := diagnosiseventMixin[0].Fields()
	_ = diagnosiseventMixinFields0
	diagnosiseventFields := schema.DiagnosisEvent{}.Fields()
	_ = diagnosiseventFields
	// diagnosiseventDescTimestamp is the schema descriptor for timestamp field.
	diagnosiseventDescTimestamp := diagnosiseventMixinFields0[1].Descriptor()
	// diagnosisevent.DefaultTimestamp holds the default value on creation for the timestamp field.
	diagnosisevent.DefaultTimestamp = diagnosiseventDescTimestamp.Default.(func() time.Time)
	// diagnosiseventDescSessionID is the schema descriptor for session_id field.
	diagnosiseventDescSessionID := diagnosiseventFields[0].Descriptor()
	// diagnosisevent.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	diagnosisevent.SessionIDValidator = diagnosiseventDescSessionID.Validators[0].(func(string) error)
	// diagnosiseventDescSkillID is the schema descriptor for skill_id field.
	diagnosiseventDescSkillID := diagnosiseventFields[1].Descriptor()
	// diagnosisevent.SkillIDValidator is a validator for the "skill_id" field. It is called by the builders before save.
	diagnosisevent.SkillIDValidator = diagnosiseventDescSkillID.Validators[0].(func(string) error)
	// diagnosiseventDescQuestionText is the schema descriptor for question_text field.
	diagnosiseventDescQuestionText := diagnosiseventFields[2].Descriptor()
	// diagnosisevent.QuestionTextValidator is a validator for the "question_text" field. It is called by the builders before save.
	diagnosisevent.QuestionTextValidator = diagnosiseventDescQuestionText.Validators[0].(func(string) error)
	// diagnosiseventDescCorrectAnswer is the schema descriptor for correct_answer field.
	diagnosiseventDescCorrectAnswer := diagnosiseventFields[3].Descriptor()
	// diagnosisevent.CorrectAnswerValidator is a validator for the "correct_answer" field. It is called by the builders before save.
	diagnosisevent.CorrectAnswerValidator = diagnosiseventDescCorrectAnswer.Validators[0].(func(string) error)
	// diagnosiseventDescLearnerAnswer is the schema descriptor for learner_answer field.
	diagnosiseventDescLearnerAnswer := diagnosiseventFields[4].Descriptor()
	// diagnosisevent.LearnerAnswerValidator is a validator for the "learner_answer" field. It is called by the builders before save.
	diagnosisevent.LearnerAnswerValidator = diagnosiseventDescLearnerAnswer.Validators[0].(func(string) error)
	// diagnosiseventDescCategory is the schema descriptor for category field.
	diagnosiseventDescCategory := diagnosiseventFields[5].Descriptor()
	// diagnosisevent.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	diagnosisevent.CategoryValidator = diagnosiseventDescCategory.Validators[0].(func(string) error)
	// diagnosiseventDescClassifierName is the schema descriptor for classifier_name field.
	diagnosiseventDescClassifierName := diagnosiseventFields[8].Descriptor()
	// diagnosisevent.ClassifierNameValidator is a validator for the "classifier_name" field. It is called by the builders before save.
	diagnosisevent.ClassifierNameValidator = diagnosiseventDescClassifierName.Validators[0].(func(string) error)
	// diagnosiseventDescReasoning is the schema descriptor for reasoning field.
	diagnosiseventDescReasoning := diagnosiseventFields[9].Descriptor()
	// diagnosisevent.DefaultReasoning holds the default value on creation for the reasoning field.
	diagnosisevent.DefaultReasoning = diagnosiseventDescReasoning.Default.(string)
	gemeventMixin := schema.GemEvent{}.Mixin()
	gemeventMixinFields0 := gemeventMixin[0].Fields()
	_ = gemeventMixinFields0
	gemeventFields := schema.GemEvent{}.Fields()
	_ = gemeventFields
	// gemeventDescTimestamp is the schema descriptor for timestamp field.
	gemeventDescTimestamp := gemeventMixinFields0[1].Descriptor()
	// gemevent.DefaultTimestamp holds the default value on creation for the timestamp field.
	gemevent.DefaultTimestamp = gemeventDescTimestamp.Default.(func() time.Time)
	// gemeventDescGemType is the schema descriptor for gem_type field.
	gemeventDescGemType := gemeventFields[0].Descriptor()
	// gemevent.GemTypeValidator is a validator for the "gem_type" field. It is called by the builders before save.
	gemevent.GemTypeValidator = gemeventDescGemType.Validators[0].(func(string) error)
	// gemeventDescRarity is the schema descriptor for rarity field.
	gemeventDescRarity := gemeventFields[1].Descriptor()
	// gemevent.RarityValidator is a validator for the "rarity" field. It is called by the builders before save.
	gemevent.RarityValidator = gemeventDescRarity.Validators[0].(func(string) error)
	// gemeventDescSessionID is the schema descriptor for session_id field.
	gemeventDescSessionID := gemeventFields[4].Descriptor()
	// gemevent.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	gemevent.SessionIDValidator = gemeventDescSessionID.Validators[0].(func(string) error)
	// gemeventDescReason is the schema descriptor for reason field.
	gemeventDescReason := gemeventFields[5].Descriptor()
	// gemevent.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	gemevent.ReasonValidator = gemeventDescReason.Validators[0].(func(string) error)
	hinteventMixin := schema.HintEvent{}.Mixin()
	hinteventMixinFields0 := hinteventMixin[0].Fields()
	_ = hinteventMixinFields0
	hinteventFields := schema.HintEvent{}.Fields()
	_ = hinteventFields
	// hinteventDescTimestamp is the schema descriptor for timestamp field.
	hinteventDescTimestamp := hinteventMixinFields0[1].Descriptor()
	// hintevent.DefaultTimestamp holds the default value on creation for the timestamp field.
	hintevent.DefaultTimestamp = hinteventDescTimestamp.Default.(func() time.Time)
	// hinteventDescSessionID is the schema descriptor for session_id field.
	hinteventDescSessionID := hinteventFields[0].Descriptor()
	// hintevent.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	hintevent.SessionIDValidator = hinteventDescSessionID.Validators[0].(func(string) error)
	// hinteventDescSkillID is the schema descriptor for skill_id field.
	hinteventDescSkillID := hinteventFields[1].Descriptor()
	// hintevent.SkillIDValidator is a validator for the "skill_id" field. It is called by the builders before save.
	hintevent.SkillIDValidator = hinteventDescSkillID.Validators[0].(func(string) error)
	// hinteventDescQuestionText is the schema descriptor for question_text field.
	hinteventDescQuestionText := hinteventFields[2].Descriptor()
	// hintevent.QuestionTextValidator is a validator for the "question_text" field. It is called by the builders before save.
	hintevent.QuestionTextValidator = hinteventDescQuestionText.Validators[0].(func(string) error)
	// hinteventDescHintText is the schema descriptor for hint_text field.
	hinteventDescHintText := hinteventFields[3].Descriptor()
	// hintevent.HintTextValidator is a validator for the "hint_text" field. It is called by the builders before save.
	hintevent.HintTextValidator = hinteventDescHintText.Validators[0].(func(string) error)
	llmrequesteventMixin := schema.LLMRequestEvent{}.Mixin()
	llmrequesteventMixinFields0 := llmrequesteventMixin[0].Fields()
	_ = llmrequesteventMixinFields0
	llmrequesteventFields := schema.LLMRequestEvent{}.Fields()
	_ = llmrequesteventFields
	// llmrequesteventDescTimestamp is the schema descriptor for timestamp field.
	llmrequesteventDescTimestamp := llmrequesteventMixinFields0[1].Descriptor()
	// llmrequestevent.DefaultTimestamp holds the default value on creation for the timestamp field.
	llmrequestevent.DefaultTimestamp = llmrequesteventDescTimestamp.Default.(func() time.Time)
	// llmrequesteventDescInputTokens is the schema descriptor for input_tokens field.
	llmrequesteventDescInputTokens := llmrequesteventFields[3].Descriptor()
	// llmrequestevent.DefaultInputTokens holds the default value on creation for the input_tokens field.
	llmrequestevent.DefaultInputTokens = llmrequesteventDescInputTokens.Default.(int)
	// llmrequesteventDescOutputTokens is the schema descriptor for output_tokens field.
	llmrequesteventDescOutputTokens := llmrequesteventFields[4].Descriptor()
	// llmrequestevent.DefaultOutputTokens holds the default value on creation for the output_tokens field.
	llmrequestevent.DefaultOutputTokens = llmrequesteventDescOutputTokens.Default.(int)
	// llmrequesteventDescLatencyMs is the schema descriptor for latency_ms field.
	llmrequesteventDescLatencyMs := llmrequesteventFields[5].Descriptor()
	// llmrequestevent.DefaultLatencyMs holds the default value on creation for the latency_ms field.
	llmrequestevent.DefaultLatencyMs = llmrequesteventDescLatencyMs.Default.(int64)
	// llmrequesteventDescErrorMessage is the schema descriptor for error_message field.
	llmrequesteventDescErrorMessage := llmrequesteventFields[7].Descriptor()
	// llmrequestevent.DefaultErrorMessage holds the default value on creation for the error_message field.
	llmrequestevent.DefaultErrorMessage = llmrequesteventDescErrorMessage.Default.(string)
	// llmrequesteventDescRequestBody is the schema descriptor for request_body field.
	llmrequesteventDescRequestBody := llmrequesteventFields[8].Descriptor()
	// llmrequestevent.DefaultRequestBody holds the default value on creation for the request_body field.
	llmrequestevent.DefaultRequestBody = llmrequesteventDescRequestBody.Default.(string)
	// llmrequesteventDescResponseBody is the schema descriptor for response_body field.
	llmrequesteventDescResponseBody := llmrequesteventFields[9].Descriptor()
	// llmrequestevent.DefaultResponseBody holds the default value on creation for the response_body field.
	llmrequestevent.DefaultResponseBody = llmrequesteventDescResponseBody.Default.(string)
	lessoneventMixin := schema.LessonEvent{}.Mixin()
	lessoneventMixinFields0 := lessoneventMixin[0].Fields()
	_ = lessoneventMixinFields0
	lessoneventFields := schema.LessonEvent{}.Fields()
	_ = lessoneventFields
	// lessoneventDescTimestamp is the schema descriptor for timestamp field.
	lessoneventDescTimestamp := lessoneventMixinFields0[1].Descriptor()
	// lessonevent.DefaultTimestamp holds the default value on creation for the timestamp field.
	lessonevent.DefaultTimestamp = lessoneventDescTimestamp.Default.(func() time.Time)
	// lessoneventDescSessionID is the schema descriptor for session_id field.
	lessoneventDescSessionID := lessoneventFields[0].Descriptor()
	// lessonevent.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	lessonevent.SessionIDValidator = lessoneventDescSessionID.Validators[0].(func(string) error)
	// lessoneventDescSkillID is the schema descriptor for skill_id field.
	lessoneventDescSkillID := lessoneventFields[1].Descriptor()
	// lessonevent.SkillIDValidator is a validator for the "skill_id" field. It is called by the builders before save.
	lessonevent.SkillIDValidator = lessoneventDescSkillID.Validators[0].(func(string) error)
	// lessoneventDescLessonTitle is the schema descriptor for lesson_title field.
	lessoneventDescLessonTitle := lessoneventFields[2].Descriptor()
	// lessonevent.LessonTitleValidator is a validator for the "lesson_title" field. It is called by the builders before save.
	lessonevent.LessonTitleValidator = lessoneventDescLessonTitle.Validators[0].(func(string) error)
	masteryeventMixin := schema.MasteryEvent{}.Mixin()
	masteryeventMixinFields0 := masteryeventMixin[0].Fields()
	_ = masteryeventMixinFields0
	masteryeventFields := schema.MasteryEvent{}.Fields()
	_ = masteryeventFields
	// masteryeventDescTimestamp is the schema descriptor for timestamp field.
	masteryeventDescTimestamp := masteryeventMixinFields0[1].Descriptor()
	// masteryevent.DefaultTimestamp holds the default value on creation for the timestamp field.
	masteryevent.DefaultTimestamp = masteryeventDescTimestamp.Default.(func() time.Time)
	// masteryeventDescSkillID is the schema descriptor for skill_id field.
	masteryeventDescSkillID := masteryeventFields[0].Descriptor()
	// masteryevent.SkillIDValidator is a validator for the "skill_id" field. It is called by the builders before save.
	masteryevent.SkillIDValidator = masteryeventDescSkillID.Validators[0].(func(string) error)
	// masteryeventDescFromState is the schema descriptor for from_state field.
	masteryeventDescFromState := masteryeventFields[1].Descriptor()
	// masteryevent.FromStateValidator is a validator for the "from_state" field. It is called by the builders before save.
	masteryevent.FromStateValidator = masteryeventDescFromState.Validators[0].(func(string) error)
	// masteryeventDescToState is the schema descriptor for to_state field.
	masteryeventDescToState := masteryeventFields[2].Descriptor()
	// masteryevent.ToStateValidator is a validator for the "to_state" field. It is called by the builders before save.
	masteryevent.ToStateValidator = masteryeventDescToState.Validators[0].(func(string) error)
	// masteryeventDescTrigger is the schema descriptor for trigger field.
	masteryeventDescTrigger := masteryeventFields[3].Descriptor()
	// masteryevent.TriggerValidator is a validator for the "trigger" field. It is called by the builders before save.
	masteryevent.TriggerValidator = masteryeventDescTrigger.Validators[0].(func(string) error)
	sessioneventMixin := schema.SessionEvent{}.Mixin()
	sessioneventMixinFields0 := sessioneventMixin[0].Fields()
	_ = sessioneventMixinFields0
	sessioneventFields := schema.SessionEvent{}.Fields()
	_ = sessioneventFields
	// sessioneventDescTimestamp is the schema descriptor for timestamp field.
	sessioneventDescTimestamp := sessioneventMixinFields0[1].Descriptor()
	// sessionevent.DefaultTimestamp holds the default value on creation for the timestamp field.
	sessionevent.DefaultTimestamp = sessioneventDescTimestamp.Default.(func() time.Time)
	// sessioneventDescSessionID is the schema descriptor for session_id field.
	sessioneventDescSessionID := sessioneventFields[0].Descriptor()
	// sessionevent.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	sessionevent.SessionIDValidator = sessioneventDescSessionID.Validators[0].(func(string) error)
	// sessioneventDescAction is the schema descriptor for action field.
	sessioneventDescAction := sessioneventFields[1].Descriptor()
	// sessionevent.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	sessionevent.ActionValidator = sessioneventDescAction.Validators[0].(func(string) error)
	// sessioneventDescQuestionsServed is the schema descriptor for questions_served field.
	sessioneventDescQuestionsServed := sessioneventFields[2].Descriptor()
	// sessionevent.DefaultQuestionsServed holds the default value on creation for the questions_served field.
	sessionevent.DefaultQuestionsServed = sessioneventDescQuestionsServed.Default.(int)
	// sessioneventDescCorrectAnswers is the schema descriptor for correct_answers field.
	sessioneventDescCorrectAnswers := sessioneventFields[3].Descriptor()
	// sessionevent.DefaultCorrectAnswers holds the default value on creation for the correct_answers field.
	sessionevent.DefaultCorrectAnswers = sessioneventDescCorrectAnswers.Default.(int)
	// sessioneventDescDurationSecs is the schema descriptor for duration_secs field.
	sessioneventDescDurationSecs := sessioneventFields[4].Descriptor()
	// sessionevent.DefaultDurationSecs holds the default value on creation for the duration_secs field.
	sessionevent.DefaultDurationSecs = sessioneventDescDurationSecs.Default.(int)
	snapshotFields := schema.Snapshot{}.Fields()
	_ = snapshotFields
	// snapshotDescTimestamp is the schema descriptor for timestamp field.
	snapshotDescTimestamp := snapshotFields[1].Descriptor()
	// snapshot.DefaultTimestamp holds the default value on creation for the timestamp field.
	snapshot.DefaultTimestamp = snapshotDescTimestamp.Default.(func() time.Time)
}
