// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/abhisek/mathiz/ent/schema"
	"github.com/abhisek/mathiz/ent/snapshot"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	snapshotFields := schema.Snapshot{}.Fields()
	_ = snapshotFields
	// snapshotDescTimestamp is the schema descriptor for timestamp field.
	snapshotDescTimestamp := snapshotFields[1].Descriptor()
	// snapshot.DefaultTimestamp holds the default value on creation for the timestamp field.
	snapshot.DefaultTimestamp = snapshotDescTimestamp.Default.(func() time.Time)
}
