package skillgraph

import "fmt"

// skills contains all 52 skill definitions for the MVP.
var skills = []Skill{

	// ── Number & Place Value (8 nodes) ────────────────────────

	{
		ID:            "pv-hundreds",
		Name:          "Place Value to 1,000",
		Description:   "Understand ones, tens, and hundreds places up to 1,000",
		Strand:        StrandNumberPlace,
		GradeLevel:    3,
		CommonCoreID:  "2.NBT.A.1",
		EstimatedMins: 10,
		Keywords:      []string{"ones", "tens", "hundreds", "place value"},
		Prerequisites: nil,
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "compare-1000",
		Name:          "Compare & Order to 1,000",
		Description:   "Compare and order numbers up to 1,000 using place value",
		Strand:        StrandNumberPlace,
		GradeLevel:    3,
		CommonCoreID:  "2.NBT.A.4",
		EstimatedMins: 8,
		Keywords:      []string{"greater than", "less than", "order"},
		Prerequisites: []string{"pv-hundreds"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "round-nearest-10-100",
		Name:          "Round to Nearest 10 or 100",
		Description:   "Round whole numbers to the nearest 10 or 100",
		Strand:        StrandNumberPlace,
		GradeLevel:    3,
		CommonCoreID:  "3.NBT.A.1",
		EstimatedMins: 8,
		Keywords:      []string{"round", "nearest", "estimate"},
		Prerequisites: []string{"pv-hundreds"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "pv-ten-thousands",
		Name:          "Place Value to 10,000",
		Description:   "Understand place value through the ten-thousands place",
		Strand:        StrandNumberPlace,
		GradeLevel:    4,
		CommonCoreID:  "4.NBT.A.1",
		EstimatedMins: 10,
		Keywords:      []string{"thousands", "ten-thousands", "expanded form"},
		Prerequisites: []string{"pv-hundreds"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "compare-10000",
		Name:          "Compare & Order to 10,000",
		Description:   "Compare and order numbers up to 10,000 using place value",
		Strand:        StrandNumberPlace,
		GradeLevel:    4,
		CommonCoreID:  "4.NBT.A.2",
		EstimatedMins: 8,
		Keywords:      []string{"compare", "order", "place value"},
		Prerequisites: []string{"pv-ten-thousands"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "round-nearest-1000",
		Name:          "Round to Nearest 1,000",
		Description:   "Round whole numbers to the nearest 1,000",
		Strand:        StrandNumberPlace,
		GradeLevel:    4,
		CommonCoreID:  "4.NBT.A.3",
		EstimatedMins: 8,
		Keywords:      []string{"round", "estimate", "nearest thousand"},
		Prerequisites: []string{"pv-ten-thousands", "round-nearest-10-100"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "pv-millions",
		Name:          "Place Value to 1,000,000",
		Description:   "Understand place value through the millions place with expanded form",
		Strand:        StrandNumberPlace,
		GradeLevel:    5,
		CommonCoreID:  "5.NBT.A.1",
		EstimatedMins: 12,
		Keywords:      []string{"hundred-thousands", "millions", "expanded form"},
		Prerequisites: []string{"pv-ten-thousands"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "compare-millions",
		Name:          "Compare & Order to 1,000,000",
		Description:   "Compare and order numbers up to 1,000,000",
		Strand:        StrandNumberPlace,
		GradeLevel:    5,
		CommonCoreID:  "4.NBT.A.2",
		EstimatedMins: 8,
		Keywords:      []string{"compare", "order", "large numbers"},
		Prerequisites: []string{"pv-millions"},
		Tiers:         DefaultTiers(),
	},

	// ── Addition & Subtraction (10 nodes) ─────────────────────

	{
		ID:            "add-2digit",
		Name:          "Add 2-Digit Numbers",
		Description:   "Add two 2-digit numbers with and without regrouping",
		Strand:        StrandAddSub,
		GradeLevel:    3,
		CommonCoreID:  "2.NBT.B.5",
		EstimatedMins: 10,
		Keywords:      []string{"addition", "carry", "regrouping"},
		Prerequisites: []string{"pv-hundreds"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "sub-2digit",
		Name:          "Subtract 2-Digit Numbers",
		Description:   "Subtract 2-digit numbers with and without borrowing",
		Strand:        StrandAddSub,
		GradeLevel:    3,
		CommonCoreID:  "2.NBT.B.5",
		EstimatedMins: 10,
		Keywords:      []string{"subtraction", "borrow", "regrouping"},
		Prerequisites: []string{"pv-hundreds"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "add-3digit",
		Name:          "Add 3-Digit Numbers",
		Description:   "Add two 3-digit numbers with and without regrouping",
		Strand:        StrandAddSub,
		GradeLevel:    3,
		CommonCoreID:  "3.NBT.A.2",
		EstimatedMins: 12,
		Keywords:      []string{"addition", "carry", "three-digit"},
		Prerequisites: []string{"add-2digit"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "sub-3digit",
		Name:          "Subtract 3-Digit Numbers",
		Description:   "Subtract 3-digit numbers with and without borrowing",
		Strand:        StrandAddSub,
		GradeLevel:    3,
		CommonCoreID:  "3.NBT.A.2",
		EstimatedMins: 12,
		Keywords:      []string{"subtraction", "borrow", "three-digit"},
		Prerequisites: []string{"sub-2digit"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "add-sub-estimation",
		Name:          "Estimate Sums & Differences",
		Description:   "Estimate sums and differences by rounding before computing",
		Strand:        StrandAddSub,
		GradeLevel:    3,
		CommonCoreID:  "3.OA.D.8",
		EstimatedMins: 8,
		Keywords:      []string{"estimate", "round", "approximate"},
		Prerequisites: []string{"round-nearest-10-100", "add-2digit", "sub-2digit"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "add-4digit",
		Name:          "Add 4-Digit Numbers",
		Description:   "Add two 4-digit numbers with regrouping across multiple places",
		Strand:        StrandAddSub,
		GradeLevel:    4,
		CommonCoreID:  "4.NBT.B.4",
		EstimatedMins: 12,
		Keywords:      []string{"addition", "four-digit", "carry"},
		Prerequisites: []string{"add-3digit", "pv-ten-thousands"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "sub-4digit",
		Name:          "Subtract 4-Digit Numbers",
		Description:   "Subtract 4-digit numbers with borrowing across multiple places",
		Strand:        StrandAddSub,
		GradeLevel:    4,
		CommonCoreID:  "4.NBT.B.4",
		EstimatedMins: 12,
		Keywords:      []string{"subtraction", "four-digit", "borrow"},
		Prerequisites: []string{"sub-3digit", "pv-ten-thousands"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "add-sub-word-3digit",
		Name:          "Addition & Subtraction Word Problems (3-digit)",
		Description:   "Solve multi-step word problems involving 3-digit addition and subtraction",
		Strand:        StrandAddSub,
		GradeLevel:    3,
		CommonCoreID:  "3.OA.D.8",
		EstimatedMins: 15,
		Keywords:      []string{"word problem", "context", "multi-step"},
		Prerequisites: []string{"add-3digit", "sub-3digit"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "add-5digit",
		Name:          "Add 5+ Digit Numbers",
		Description:   "Add numbers with five or more digits fluently",
		Strand:        StrandAddSub,
		GradeLevel:    5,
		CommonCoreID:  "4.NBT.B.4",
		EstimatedMins: 12,
		Keywords:      []string{"large number addition", "carry"},
		Prerequisites: []string{"add-4digit", "pv-millions"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "sub-5digit",
		Name:          "Subtract 5+ Digit Numbers",
		Description:   "Subtract numbers with five or more digits fluently",
		Strand:        StrandAddSub,
		GradeLevel:    5,
		CommonCoreID:  "4.NBT.B.4",
		EstimatedMins: 12,
		Keywords:      []string{"large number subtraction", "borrow"},
		Prerequisites: []string{"sub-4digit", "pv-millions"},
		Tiers:         DefaultTiers(),
	},

	// ── Multiplication & Division (14 nodes) ──────────────────

	{
		ID:            "mult-concept",
		Name:          "Multiplication Concept",
		Description:   "Understand multiplication as groups of and repeated addition",
		Strand:        StrandMultDiv,
		GradeLevel:    3,
		CommonCoreID:  "3.OA.A.1",
		EstimatedMins: 10,
		Keywords:      []string{"groups of", "repeated addition", "array"},
		Prerequisites: []string{"add-2digit"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "mult-facts-2-5-10",
		Name:          "Multiply by 2, 5, and 10",
		Description:   "Recall multiplication facts for 2, 5, and 10",
		Strand:        StrandMultDiv,
		GradeLevel:    3,
		CommonCoreID:  "3.OA.C.7",
		EstimatedMins: 12,
		Keywords:      []string{"times tables", "skip counting", "facts"},
		Prerequisites: []string{"mult-concept"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "mult-facts-3-4-6",
		Name:          "Multiply by 3, 4, and 6",
		Description:   "Recall multiplication facts for 3, 4, and 6",
		Strand:        StrandMultDiv,
		GradeLevel:    3,
		CommonCoreID:  "3.OA.C.7",
		EstimatedMins: 12,
		Keywords:      []string{"times tables", "facts", "memorization"},
		Prerequisites: []string{"mult-facts-2-5-10"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "mult-facts-7-8-9",
		Name:          "Multiply by 7, 8, and 9",
		Description:   "Recall multiplication facts for 7, 8, and 9",
		Strand:        StrandMultDiv,
		GradeLevel:    3,
		CommonCoreID:  "3.OA.C.7",
		EstimatedMins: 15,
		Keywords:      []string{"times tables", "facts", "memorization"},
		Prerequisites: []string{"mult-facts-3-4-6"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "mult-properties",
		Name:          "Multiplication Properties",
		Description:   "Apply commutative, associative, and distributive properties of multiplication",
		Strand:        StrandMultDiv,
		GradeLevel:    3,
		CommonCoreID:  "3.OA.B.5",
		EstimatedMins: 10,
		Keywords:      []string{"commutative", "associative", "distributive"},
		Prerequisites: []string{"mult-facts-2-5-10"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "div-concept",
		Name:          "Division Concept",
		Description:   "Understand division as sharing equally and grouping",
		Strand:        StrandMultDiv,
		GradeLevel:    3,
		CommonCoreID:  "3.OA.A.2",
		EstimatedMins: 10,
		Keywords:      []string{"sharing", "grouping", "inverse of multiplication"},
		Prerequisites: []string{"mult-concept"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "div-facts",
		Name:          "Division Facts (÷1 through ÷9)",
		Description:   "Recall division facts using the inverse of multiplication",
		Strand:        StrandMultDiv,
		GradeLevel:    3,
		CommonCoreID:  "3.OA.C.7",
		EstimatedMins: 15,
		Keywords:      []string{"division facts", "inverse", "fluency"},
		Prerequisites: []string{"div-concept", "mult-facts-7-8-9"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "mult-div-word",
		Name:          "Multiplication & Division Word Problems",
		Description:   "Solve word problems requiring multiplication or division",
		Strand:        StrandMultDiv,
		GradeLevel:    3,
		CommonCoreID:  "3.OA.A.3",
		EstimatedMins: 15,
		Keywords:      []string{"word problem", "context", "operation choice"},
		Prerequisites: []string{"mult-facts-7-8-9", "div-facts"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "mult-2d-by-1d",
		Name:          "Multiply 2-Digit by 1-Digit",
		Description:   "Multiply a 2-digit number by a 1-digit number using partial products or area model",
		Strand:        StrandMultDiv,
		GradeLevel:    4,
		CommonCoreID:  "4.NBT.B.5",
		EstimatedMins: 12,
		Keywords:      []string{"partial products", "area model"},
		Prerequisites: []string{"mult-facts-7-8-9", "pv-ten-thousands"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "mult-2d-by-2d",
		Name:          "Multiply 2-Digit by 2-Digit",
		Description:   "Multiply two 2-digit numbers using partial products or standard algorithm",
		Strand:        StrandMultDiv,
		GradeLevel:    4,
		CommonCoreID:  "4.NBT.B.5",
		EstimatedMins: 15,
		Keywords:      []string{"partial products", "standard algorithm"},
		Prerequisites: []string{"mult-2d-by-1d"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "div-2d-by-1d",
		Name:          "Divide 2-Digit by 1-Digit",
		Description:   "Divide a 2-digit number by a 1-digit number with or without remainders",
		Strand:        StrandMultDiv,
		GradeLevel:    4,
		CommonCoreID:  "4.NBT.B.6",
		EstimatedMins: 12,
		Keywords:      []string{"long division", "remainder"},
		Prerequisites: []string{"div-facts", "pv-ten-thousands"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "div-3d-by-1d",
		Name:          "Divide 3-Digit by 1-Digit",
		Description:   "Divide a 3-digit number by a 1-digit number using long division",
		Strand:        StrandMultDiv,
		GradeLevel:    4,
		CommonCoreID:  "4.NBT.B.6",
		EstimatedMins: 15,
		Keywords:      []string{"long division", "multi-step"},
		Prerequisites: []string{"div-2d-by-1d"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "mult-3d-by-2d",
		Name:          "Multiply 3-Digit by 2-Digit",
		Description:   "Multiply a 3-digit number by a 2-digit number using the standard algorithm",
		Strand:        StrandMultDiv,
		GradeLevel:    5,
		CommonCoreID:  "5.NBT.B.5",
		EstimatedMins: 15,
		Keywords:      []string{"standard algorithm", "large multiplication"},
		Prerequisites: []string{"mult-2d-by-2d"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "div-4d-by-2d",
		Name:          "Divide 4-Digit by 2-Digit",
		Description:   "Divide a 4-digit number by a 2-digit divisor using long division",
		Strand:        StrandMultDiv,
		GradeLevel:    5,
		CommonCoreID:  "5.NBT.B.6",
		EstimatedMins: 15,
		Keywords:      []string{"long division", "two-digit divisor"},
		Prerequisites: []string{"div-3d-by-1d", "mult-2d-by-2d"},
		Tiers:         DefaultTiers(),
	},

	// ── Fractions (12 nodes) ──────────────────────────────────

	{
		ID:            "frac-concept",
		Name:          "Fraction Concepts",
		Description:   "Understand fractions as parts of a whole using numerator and denominator",
		Strand:        StrandFractions,
		GradeLevel:    3,
		CommonCoreID:  "3.NF.A.1",
		EstimatedMins: 12,
		Keywords:      []string{"numerator", "denominator", "part of whole"},
		Prerequisites: []string{"div-concept"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "frac-on-number-line",
		Name:          "Fractions on a Number Line",
		Description:   "Locate and represent fractions on a number line",
		Strand:        StrandFractions,
		GradeLevel:    3,
		CommonCoreID:  "3.NF.A.2",
		EstimatedMins: 10,
		Keywords:      []string{"number line", "position", "unit fraction"},
		Prerequisites: []string{"frac-concept"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "frac-equivalent",
		Name:          "Equivalent Fractions",
		Description:   "Identify and generate simple equivalent fractions",
		Strand:        StrandFractions,
		GradeLevel:    3,
		CommonCoreID:  "3.NF.A.3",
		EstimatedMins: 12,
		Keywords:      []string{"same value", "simplify", "multiply numerator denominator"},
		Prerequisites: []string{"frac-concept"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "frac-compare",
		Name:          "Compare Fractions",
		Description:   "Compare fractions with same or different denominators using benchmarks",
		Strand:        StrandFractions,
		GradeLevel:    3,
		CommonCoreID:  "3.NF.A.3",
		EstimatedMins: 10,
		Keywords:      []string{"greater than", "less than", "same denominator", "benchmark"},
		Prerequisites: []string{"frac-equivalent", "frac-on-number-line"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "frac-equiv-generate",
		Name:          "Generate Equivalent Fractions",
		Description:   "Create equivalent fractions by multiplying or dividing numerator and denominator",
		Strand:        StrandFractions,
		GradeLevel:    4,
		CommonCoreID:  "4.NF.A.1",
		EstimatedMins: 12,
		Keywords:      []string{"multiply", "divide", "visual model"},
		Prerequisites: []string{"frac-equivalent", "mult-facts-7-8-9"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "frac-add-same-denom",
		Name:          "Add Fractions (Same Denominator)",
		Description:   "Add fractions that share the same denominator",
		Strand:        StrandFractions,
		GradeLevel:    4,
		CommonCoreID:  "4.NF.B.3",
		EstimatedMins: 10,
		Keywords:      []string{"add numerators", "same denominator"},
		Prerequisites: []string{"frac-compare"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "frac-sub-same-denom",
		Name:          "Subtract Fractions (Same Denominator)",
		Description:   "Subtract fractions that share the same denominator",
		Strand:        StrandFractions,
		GradeLevel:    4,
		CommonCoreID:  "4.NF.B.3",
		EstimatedMins: 10,
		Keywords:      []string{"subtract numerators", "same denominator"},
		Prerequisites: []string{"frac-compare"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "frac-mixed-numbers",
		Name:          "Mixed Numbers & Improper Fractions",
		Description:   "Convert between mixed numbers and improper fractions",
		Strand:        StrandFractions,
		GradeLevel:    4,
		CommonCoreID:  "4.NF.B.3",
		EstimatedMins: 12,
		Keywords:      []string{"mixed number", "improper", "convert"},
		Prerequisites: []string{"frac-add-same-denom"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "frac-add-diff-denom",
		Name:          "Add Fractions (Different Denominators)",
		Description:   "Add fractions with unlike denominators by finding a common denominator",
		Strand:        StrandFractions,
		GradeLevel:    5,
		CommonCoreID:  "5.NF.A.1",
		EstimatedMins: 15,
		Keywords:      []string{"common denominator", "LCD", "unlike fractions"},
		Prerequisites: []string{"frac-add-same-denom", "frac-equiv-generate"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "frac-sub-diff-denom",
		Name:          "Subtract Fractions (Different Denominators)",
		Description:   "Subtract fractions with unlike denominators by finding a common denominator",
		Strand:        StrandFractions,
		GradeLevel:    5,
		CommonCoreID:  "5.NF.A.1",
		EstimatedMins: 15,
		Keywords:      []string{"common denominator", "LCD", "unlike fractions"},
		Prerequisites: []string{"frac-sub-same-denom", "frac-equiv-generate"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "frac-mult",
		Name:          "Multiply Fractions",
		Description:   "Multiply fractions and mixed numbers",
		Strand:        StrandFractions,
		GradeLevel:    5,
		CommonCoreID:  "5.NF.B.4",
		EstimatedMins: 12,
		Keywords:      []string{"multiply numerators", "multiply denominators"},
		Prerequisites: []string{"frac-mixed-numbers", "mult-facts-7-8-9"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "frac-div",
		Name:          "Divide Fractions",
		Description:   "Divide fractions using the reciprocal (invert and multiply)",
		Strand:        StrandFractions,
		GradeLevel:    5,
		CommonCoreID:  "5.NF.B.7",
		EstimatedMins: 12,
		Keywords:      []string{"reciprocal", "invert and multiply"},
		Prerequisites: []string{"frac-mult", "div-facts"},
		Tiers:         DefaultTiers(),
	},

	// ── Measurement (8 nodes) ────────────────────────────────

	{
		ID:            "meas-length",
		Name:          "Measure Length (cm, m, in, ft)",
		Description:   "Measure and estimate lengths in metric and customary units",
		Strand:        StrandMeasurement,
		GradeLevel:    3,
		CommonCoreID:  "3.MD.B.4",
		EstimatedMins: 10,
		Keywords:      []string{"ruler", "centimeter", "meter", "inch", "foot"},
		Prerequisites: []string{"pv-hundreds"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "meas-time",
		Name:          "Tell Time & Elapsed Time",
		Description:   "Read clocks and calculate elapsed time in hours and minutes",
		Strand:        StrandMeasurement,
		GradeLevel:    3,
		CommonCoreID:  "3.MD.A.1",
		EstimatedMins: 12,
		Keywords:      []string{"clock", "hour", "minute", "elapsed", "duration"},
		Prerequisites: []string{"add-2digit", "sub-2digit"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "meas-mass-volume",
		Name:          "Mass & Volume (g, kg, mL, L)",
		Description:   "Measure and estimate mass and liquid volume in metric units",
		Strand:        StrandMeasurement,
		GradeLevel:    3,
		CommonCoreID:  "3.MD.A.2",
		EstimatedMins: 10,
		Keywords:      []string{"gram", "kilogram", "liter", "milliliter", "measure"},
		Prerequisites: []string{"pv-hundreds"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "meas-perimeter",
		Name:          "Perimeter",
		Description:   "Calculate the perimeter of polygons by adding side lengths",
		Strand:        StrandMeasurement,
		GradeLevel:    3,
		CommonCoreID:  "3.MD.D.8",
		EstimatedMins: 10,
		Keywords:      []string{"perimeter", "side lengths", "add sides"},
		Prerequisites: []string{"add-3digit"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "meas-area-concept",
		Name:          "Area Concept (Counting Squares)",
		Description:   "Understand area by counting unit squares",
		Strand:        StrandMeasurement,
		GradeLevel:    3,
		CommonCoreID:  "3.MD.C.5",
		EstimatedMins: 10,
		Keywords:      []string{"area", "square unit", "count", "cover"},
		Prerequisites: []string{"mult-concept"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "meas-area-formula",
		Name:          "Area by Multiplication",
		Description:   "Calculate the area of rectangles using length times width",
		Strand:        StrandMeasurement,
		GradeLevel:    3,
		CommonCoreID:  "3.MD.C.7",
		EstimatedMins: 10,
		Keywords:      []string{"length times width", "rectangle", "formula"},
		Prerequisites: []string{"meas-area-concept", "mult-facts-2-5-10"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "meas-unit-conversion",
		Name:          "Unit Conversions",
		Description:   "Convert between metric and customary measurement units using tables",
		Strand:        StrandMeasurement,
		GradeLevel:    4,
		CommonCoreID:  "4.MD.A.1",
		EstimatedMins: 12,
		Keywords:      []string{"convert", "metric", "customary", "table"},
		Prerequisites: []string{"meas-length", "meas-mass-volume", "mult-2d-by-1d"},
		Tiers:         DefaultTiers(),
	},
	{
		ID:            "meas-area-perimeter-word",
		Name:          "Area & Perimeter Word Problems",
		Description:   "Solve real-world word problems involving area and perimeter",
		Strand:        StrandMeasurement,
		GradeLevel:    4,
		CommonCoreID:  "4.MD.A.3",
		EstimatedMins: 15,
		Keywords:      []string{"word problem", "real-world", "area", "perimeter"},
		Prerequisites: []string{"meas-area-formula", "meas-perimeter", "mult-2d-by-1d"},
		Tiers:         DefaultTiers(),
	},
}

func init() {
	g = buildGraph(skills)
	if err := Validate(); err != nil {
		panic(fmt.Sprintf("skillgraph: %v", err))
	}
}
