// Code generated by ent, DO NOT EDIT.

package sessionevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/abhisek/mathiz/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLTE(FieldID, id))
}

// Sequence applies equality check predicate on the "sequence" field. It's identical to SequenceEQ.
func Sequence(v int64) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldSequence, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldTimestamp, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldSessionID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldAction, v))
}

// QuestionsServed applies equality check predicate on the "questions_served" field. It's identical to QuestionsServedEQ.
func QuestionsServed(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldQuestionsServed, v))
}

// CorrectAnswers applies equality check predicate on the "correct_answers" field. It's identical to CorrectAnswersEQ.
func CorrectAnswers(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldCorrectAnswers, v))
}

// DurationSecs applies equality check predicate on the "duration_secs" field. It's identical to DurationSecsEQ.
func DurationSecs(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldDurationSecs, v))
}

// SequenceEQ applies the EQ predicate on the "sequence" field.
func SequenceEQ(v int64) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldSequence, v))
}

// SequenceNEQ applies the NEQ predicate on the "sequence" field.
func SequenceNEQ(v int64) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNEQ(FieldSequence, v))
}

// SequenceIn applies the In predicate on the "sequence" field.
func SequenceIn(vs ...int64) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldIn(FieldSequence, vs...))
}

// SequenceNotIn applies the NotIn predicate on the "sequence" field.
func SequenceNotIn(vs ...int64) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNotIn(FieldSequence, vs...))
}

// SequenceGT applies the GT predicate on the "sequence" field.
func SequenceGT(v int64) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGT(FieldSequence, v))
}

// SequenceGTE applies the GTE predicate on the "sequence" field.
func SequenceGTE(v int64) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGTE(FieldSequence, v))
}

// SequenceLT applies the LT predicate on the "sequence" field.
func SequenceLT(v int64) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLT(FieldSequence, v))
}

// SequenceLTE applies the LTE predicate on the "sequence" field.
func SequenceLTE(v int64) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLTE(FieldSequence, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLTE(FieldTimestamp, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldContainsFold(FieldSessionID, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldContainsFold(FieldAction, v))
}

// QuestionsServedEQ applies the EQ predicate on the "questions_served" field.
func QuestionsServedEQ(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldQuestionsServed, v))
}

// QuestionsServedNEQ applies the NEQ predicate on the "questions_served" field.
func QuestionsServedNEQ(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNEQ(FieldQuestionsServed, v))
}

// QuestionsServedIn applies the In predicate on the "questions_served" field.
func QuestionsServedIn(vs ...int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldIn(FieldQuestionsServed, vs...))
}

// QuestionsServedNotIn applies the NotIn predicate on the "questions_served" field.
func QuestionsServedNotIn(vs ...int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNotIn(FieldQuestionsServed, vs...))
}

// QuestionsServedGT applies the GT predicate on the "questions_served" field.
func QuestionsServedGT(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGT(FieldQuestionsServed, v))
}

// QuestionsServedGTE applies the GTE predicate on the "questions_served" field.
func QuestionsServedGTE(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGTE(FieldQuestionsServed, v))
}

// QuestionsServedLT applies the LT predicate on the "questions_served" field.
func QuestionsServedLT(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLT(FieldQuestionsServed, v))
}

// QuestionsServedLTE applies the LTE predicate on the "questions_served" field.
func QuestionsServedLTE(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLTE(FieldQuestionsServed, v))
}

// CorrectAnswersEQ applies the EQ predicate on the "correct_answers" field.
func CorrectAnswersEQ(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldCorrectAnswers, v))
}

// CorrectAnswersNEQ applies the NEQ predicate on the "correct_answers" field.
func CorrectAnswersNEQ(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNEQ(FieldCorrectAnswers, v))
}

// CorrectAnswersIn applies the In predicate on the "correct_answers" field.
func CorrectAnswersIn(vs ...int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldIn(FieldCorrectAnswers, vs...))
}

// CorrectAnswersNotIn applies the NotIn predicate on the "correct_answers" field.
func CorrectAnswersNotIn(vs ...int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNotIn(FieldCorrectAnswers, vs...))
}

// CorrectAnswersGT applies the GT predicate on the "correct_answers" field.
func CorrectAnswersGT(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGT(FieldCorrectAnswers, v))
}

// CorrectAnswersGTE applies the GTE predicate on the "correct_answers" field.
func CorrectAnswersGTE(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGTE(FieldCorrectAnswers, v))
}

// CorrectAnswersLT applies the LT predicate on the "correct_answers" field.
func CorrectAnswersLT(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLT(FieldCorrectAnswers, v))
}

// CorrectAnswersLTE applies the LTE predicate on the "correct_answers" field.
func CorrectAnswersLTE(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLTE(FieldCorrectAnswers, v))
}

// DurationSecsEQ applies the EQ predicate on the "duration_secs" field.
func DurationSecsEQ(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldEQ(FieldDurationSecs, v))
}

// DurationSecsNEQ applies the NEQ predicate on the "duration_secs" field.
func DurationSecsNEQ(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNEQ(FieldDurationSecs, v))
}

// DurationSecsIn applies the In predicate on the "duration_secs" field.
func DurationSecsIn(vs ...int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldIn(FieldDurationSecs, vs...))
}

// DurationSecsNotIn applies the NotIn predicate on the "duration_secs" field.
func DurationSecsNotIn(vs ...int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNotIn(FieldDurationSecs, vs...))
}

// DurationSecsGT applies the GT predicate on the "duration_secs" field.
func DurationSecsGT(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGT(FieldDurationSecs, v))
}

// DurationSecsGTE applies the GTE predicate on the "duration_secs" field.
func DurationSecsGTE(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldGTE(FieldDurationSecs, v))
}

// DurationSecsLT applies the LT predicate on the "duration_secs" field.
func DurationSecsLT(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLT(FieldDurationSecs, v))
}

// DurationSecsLTE applies the LTE predicate on the "duration_secs" field.
func DurationSecsLTE(v int) predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldLTE(FieldDurationSecs, v))
}

// PlanSummaryIsNil applies the IsNil predicate on the "plan_summary" field.
func PlanSummaryIsNil() predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldIsNull(FieldPlanSummary))
}

// PlanSummaryNotNil applies the NotNil predicate on the "plan_summary" field.
func PlanSummaryNotNil() predicate.SessionEvent {
	return predicate.SessionEvent(sql.FieldNotNull(FieldPlanSummary))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SessionEvent) predicate.SessionEvent {
	return predicate.SessionEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SessionEvent) predicate.SessionEvent {
	return predicate.SessionEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SessionEvent) predicate.SessionEvent {
	return predicate.SessionEvent(sql.NotPredicates(p))
}
