// Code generated by ent, DO NOT EDIT.

package questquestion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/abhisek/mathiz/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLTE(FieldID, id))
}

// UID applies equality check predicate on the "uid" field. It's identical to UIDEQ.
func UID(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldUID, v))
}

// QuestUID applies equality check predicate on the "quest_uid" field. It's identical to QuestUIDEQ.
func QuestUID(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldQuestUID, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldPosition, v))
}

// Text applies equality check predicate on the "text" field. It's identical to TextEQ.
func Text(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldText, v))
}

// Answer applies equality check predicate on the "answer" field. It's identical to AnswerEQ.
func Answer(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldAnswer, v))
}

// AnswerType applies equality check predicate on the "answer_type" field. It's identical to AnswerTypeEQ.
func AnswerType(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldAnswerType, v))
}

// Format applies equality check predicate on the "format" field. It's identical to FormatEQ.
func Format(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldFormat, v))
}

// Hint applies equality check predicate on the "hint" field. It's identical to HintEQ.
func Hint(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldHint, v))
}

// Explanation applies equality check predicate on the "explanation" field. It's identical to ExplanationEQ.
func Explanation(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldExplanation, v))
}

// ClientKey applies equality check predicate on the "client_key" field. It's identical to ClientKeyEQ.
func ClientKey(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldClientKey, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldCreatedAt, v))
}

// UIDEQ applies the EQ predicate on the "uid" field.
func UIDEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldUID, v))
}

// UIDNEQ applies the NEQ predicate on the "uid" field.
func UIDNEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNEQ(FieldUID, v))
}

// UIDIn applies the In predicate on the "uid" field.
func UIDIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldIn(FieldUID, vs...))
}

// UIDNotIn applies the NotIn predicate on the "uid" field.
func UIDNotIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNotIn(FieldUID, vs...))
}

// UIDGT applies the GT predicate on the "uid" field.
func UIDGT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGT(FieldUID, v))
}

// UIDGTE applies the GTE predicate on the "uid" field.
func UIDGTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGTE(FieldUID, v))
}

// UIDLT applies the LT predicate on the "uid" field.
func UIDLT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLT(FieldUID, v))
}

// UIDLTE applies the LTE predicate on the "uid" field.
func UIDLTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLTE(FieldUID, v))
}

// UIDContains applies the Contains predicate on the "uid" field.
func UIDContains(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContains(FieldUID, v))
}

// UIDHasPrefix applies the HasPrefix predicate on the "uid" field.
func UIDHasPrefix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasPrefix(FieldUID, v))
}

// UIDHasSuffix applies the HasSuffix predicate on the "uid" field.
func UIDHasSuffix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasSuffix(FieldUID, v))
}

// UIDEqualFold applies the EqualFold predicate on the "uid" field.
func UIDEqualFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEqualFold(FieldUID, v))
}

// UIDContainsFold applies the ContainsFold predicate on the "uid" field.
func UIDContainsFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContainsFold(FieldUID, v))
}

// QuestUIDEQ applies the EQ predicate on the "quest_uid" field.
func QuestUIDEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldQuestUID, v))
}

// QuestUIDNEQ applies the NEQ predicate on the "quest_uid" field.
func QuestUIDNEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNEQ(FieldQuestUID, v))
}

// QuestUIDIn applies the In predicate on the "quest_uid" field.
func QuestUIDIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldIn(FieldQuestUID, vs...))
}

// QuestUIDNotIn applies the NotIn predicate on the "quest_uid" field.
func QuestUIDNotIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNotIn(FieldQuestUID, vs...))
}

// QuestUIDGT applies the GT predicate on the "quest_uid" field.
func QuestUIDGT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGT(FieldQuestUID, v))
}

// QuestUIDGTE applies the GTE predicate on the "quest_uid" field.
func QuestUIDGTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGTE(FieldQuestUID, v))
}

// QuestUIDLT applies the LT predicate on the "quest_uid" field.
func QuestUIDLT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLT(FieldQuestUID, v))
}

// QuestUIDLTE applies the LTE predicate on the "quest_uid" field.
func QuestUIDLTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLTE(FieldQuestUID, v))
}

// QuestUIDContains applies the Contains predicate on the "quest_uid" field.
func QuestUIDContains(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContains(FieldQuestUID, v))
}

// QuestUIDHasPrefix applies the HasPrefix predicate on the "quest_uid" field.
func QuestUIDHasPrefix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasPrefix(FieldQuestUID, v))
}

// QuestUIDHasSuffix applies the HasSuffix predicate on the "quest_uid" field.
func QuestUIDHasSuffix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasSuffix(FieldQuestUID, v))
}

// QuestUIDEqualFold applies the EqualFold predicate on the "quest_uid" field.
func QuestUIDEqualFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEqualFold(FieldQuestUID, v))
}

// QuestUIDContainsFold applies the ContainsFold predicate on the "quest_uid" field.
func QuestUIDContainsFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContainsFold(FieldQuestUID, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLTE(FieldPosition, v))
}

// TextEQ applies the EQ predicate on the "text" field.
func TextEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldText, v))
}

// TextNEQ applies the NEQ predicate on the "text" field.
func TextNEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNEQ(FieldText, v))
}

// TextIn applies the In predicate on the "text" field.
func TextIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldIn(FieldText, vs...))
}

// TextNotIn applies the NotIn predicate on the "text" field.
func TextNotIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNotIn(FieldText, vs...))
}

// TextGT applies the GT predicate on the "text" field.
func TextGT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGT(FieldText, v))
}

// TextGTE applies the GTE predicate on the "text" field.
func TextGTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGTE(FieldText, v))
}

// TextLT applies the LT predicate on the "text" field.
func TextLT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLT(FieldText, v))
}

// TextLTE applies the LTE predicate on the "text" field.
func TextLTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLTE(FieldText, v))
}

// TextContains applies the Contains predicate on the "text" field.
func TextContains(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContains(FieldText, v))
}

// TextHasPrefix applies the HasPrefix predicate on the "text" field.
func TextHasPrefix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasPrefix(FieldText, v))
}

// TextHasSuffix applies the HasSuffix predicate on the "text" field.
func TextHasSuffix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasSuffix(FieldText, v))
}

// TextEqualFold applies the EqualFold predicate on the "text" field.
func TextEqualFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEqualFold(FieldText, v))
}

// TextContainsFold applies the ContainsFold predicate on the "text" field.
func TextContainsFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContainsFold(FieldText, v))
}

// AnswerEQ applies the EQ predicate on the "answer" field.
func AnswerEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldAnswer, v))
}

// AnswerNEQ applies the NEQ predicate on the "answer" field.
func AnswerNEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNEQ(FieldAnswer, v))
}

// AnswerIn applies the In predicate on the "answer" field.
func AnswerIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldIn(FieldAnswer, vs...))
}

// AnswerNotIn applies the NotIn predicate on the "answer" field.
func AnswerNotIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNotIn(FieldAnswer, vs...))
}

// AnswerGT applies the GT predicate on the "answer" field.
func AnswerGT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGT(FieldAnswer, v))
}

// AnswerGTE applies the GTE predicate on the "answer" field.
func AnswerGTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGTE(FieldAnswer, v))
}

// AnswerLT applies the LT predicate on the "answer" field.
func AnswerLT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLT(FieldAnswer, v))
}

// AnswerLTE applies the LTE predicate on the "answer" field.
func AnswerLTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLTE(FieldAnswer, v))
}

// AnswerContains applies the Contains predicate on the "answer" field.
func AnswerContains(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContains(FieldAnswer, v))
}

// AnswerHasPrefix applies the HasPrefix predicate on the "answer" field.
func AnswerHasPrefix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasPrefix(FieldAnswer, v))
}

// AnswerHasSuffix applies the HasSuffix predicate on the "answer" field.
func AnswerHasSuffix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasSuffix(FieldAnswer, v))
}

// AnswerEqualFold applies the EqualFold predicate on the "answer" field.
func AnswerEqualFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEqualFold(FieldAnswer, v))
}

// AnswerContainsFold applies the ContainsFold predicate on the "answer" field.
func AnswerContainsFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContainsFold(FieldAnswer, v))
}

// AnswerTypeEQ applies the EQ predicate on the "answer_type" field.
func AnswerTypeEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldAnswerType, v))
}

// AnswerTypeNEQ applies the NEQ predicate on the "answer_type" field.
func AnswerTypeNEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNEQ(FieldAnswerType, v))
}

// AnswerTypeIn applies the In predicate on the "answer_type" field.
func AnswerTypeIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldIn(FieldAnswerType, vs...))
}

// AnswerTypeNotIn applies the NotIn predicate on the "answer_type" field.
func AnswerTypeNotIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNotIn(FieldAnswerType, vs...))
}

// AnswerTypeGT applies the GT predicate on the "answer_type" field.
func AnswerTypeGT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGT(FieldAnswerType, v))
}

// AnswerTypeGTE applies the GTE predicate on the "answer_type" field.
func AnswerTypeGTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGTE(FieldAnswerType, v))
}

// AnswerTypeLT applies the LT predicate on the "answer_type" field.
func AnswerTypeLT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLT(FieldAnswerType, v))
}

// AnswerTypeLTE applies the LTE predicate on the "answer_type" field.
func AnswerTypeLTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLTE(FieldAnswerType, v))
}

// AnswerTypeContains applies the Contains predicate on the "answer_type" field.
func AnswerTypeContains(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContains(FieldAnswerType, v))
}

// AnswerTypeHasPrefix applies the HasPrefix predicate on the "answer_type" field.
func AnswerTypeHasPrefix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasPrefix(FieldAnswerType, v))
}

// AnswerTypeHasSuffix applies the HasSuffix predicate on the "answer_type" field.
func AnswerTypeHasSuffix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasSuffix(FieldAnswerType, v))
}

// AnswerTypeEqualFold applies the EqualFold predicate on the "answer_type" field.
func AnswerTypeEqualFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEqualFold(FieldAnswerType, v))
}

// AnswerTypeContainsFold applies the ContainsFold predicate on the "answer_type" field.
func AnswerTypeContainsFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContainsFold(FieldAnswerType, v))
}

// FormatEQ applies the EQ predicate on the "format" field.
func FormatEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldFormat, v))
}

// FormatNEQ applies the NEQ predicate on the "format" field.
func FormatNEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNEQ(FieldFormat, v))
}

// FormatIn applies the In predicate on the "format" field.
func FormatIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldIn(FieldFormat, vs...))
}

// FormatNotIn applies the NotIn predicate on the "format" field.
func FormatNotIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNotIn(FieldFormat, vs...))
}

// FormatGT applies the GT predicate on the "format" field.
func FormatGT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGT(FieldFormat, v))
}

// FormatGTE applies the GTE predicate on the "format" field.
func FormatGTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGTE(FieldFormat, v))
}

// FormatLT applies the LT predicate on the "format" field.
func FormatLT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLT(FieldFormat, v))
}

// FormatLTE applies the LTE predicate on the "format" field.
func FormatLTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLTE(FieldFormat, v))
}

// FormatContains applies the Contains predicate on the "format" field.
func FormatContains(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContains(FieldFormat, v))
}

// FormatHasPrefix applies the HasPrefix predicate on the "format" field.
func FormatHasPrefix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasPrefix(FieldFormat, v))
}

// FormatHasSuffix applies the HasSuffix predicate on the "format" field.
func FormatHasSuffix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasSuffix(FieldFormat, v))
}

// FormatEqualFold applies the EqualFold predicate on the "format" field.
func FormatEqualFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEqualFold(FieldFormat, v))
}

// FormatContainsFold applies the ContainsFold predicate on the "format" field.
func FormatContainsFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContainsFold(FieldFormat, v))
}

// ChoicesIsNil applies the IsNil predicate on the "choices" field.
func ChoicesIsNil() predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldIsNull(FieldChoices))
}

// ChoicesNotNil applies the NotNil predicate on the "choices" field.
func ChoicesNotNil() predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNotNull(FieldChoices))
}

// HintEQ applies the EQ predicate on the "hint" field.
func HintEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldHint, v))
}

// HintNEQ applies the NEQ predicate on the "hint" field.
func HintNEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNEQ(FieldHint, v))
}

// HintIn applies the In predicate on the "hint" field.
func HintIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldIn(FieldHint, vs...))
}

// HintNotIn applies the NotIn predicate on the "hint" field.
func HintNotIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNotIn(FieldHint, vs...))
}

// HintGT applies the GT predicate on the "hint" field.
func HintGT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGT(FieldHint, v))
}

// HintGTE applies the GTE predicate on the "hint" field.
func HintGTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGTE(FieldHint, v))
}

// HintLT applies the LT predicate on the "hint" field.
func HintLT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLT(FieldHint, v))
}

// HintLTE applies the LTE predicate on the "hint" field.
func HintLTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLTE(FieldHint, v))
}

// HintContains applies the Contains predicate on the "hint" field.
func HintContains(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContains(FieldHint, v))
}

// HintHasPrefix applies the HasPrefix predicate on the "hint" field.
func HintHasPrefix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasPrefix(FieldHint, v))
}

// HintHasSuffix applies the HasSuffix predicate on the "hint" field.
func HintHasSuffix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasSuffix(FieldHint, v))
}

// HintEqualFold applies the EqualFold predicate on the "hint" field.
func HintEqualFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEqualFold(FieldHint, v))
}

// HintContainsFold applies the ContainsFold predicate on the "hint" field.
func HintContainsFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContainsFold(FieldHint, v))
}

// ExplanationEQ applies the EQ predicate on the "explanation" field.
func ExplanationEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldExplanation, v))
}

// ExplanationNEQ applies the NEQ predicate on the "explanation" field.
func ExplanationNEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNEQ(FieldExplanation, v))
}

// ExplanationIn applies the In predicate on the "explanation" field.
func ExplanationIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldIn(FieldExplanation, vs...))
}

// ExplanationNotIn applies the NotIn predicate on the "explanation" field.
func ExplanationNotIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNotIn(FieldExplanation, vs...))
}

// ExplanationGT applies the GT predicate on the "explanation" field.
func ExplanationGT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGT(FieldExplanation, v))
}

// ExplanationGTE applies the GTE predicate on the "explanation" field.
func ExplanationGTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGTE(FieldExplanation, v))
}

// ExplanationLT applies the LT predicate on the "explanation" field.
func ExplanationLT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLT(FieldExplanation, v))
}

// ExplanationLTE applies the LTE predicate on the "explanation" field.
func ExplanationLTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLTE(FieldExplanation, v))
}

// ExplanationContains applies the Contains predicate on the "explanation" field.
func ExplanationContains(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContains(FieldExplanation, v))
}

// ExplanationHasPrefix applies the HasPrefix predicate on the "explanation" field.
func ExplanationHasPrefix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasPrefix(FieldExplanation, v))
}

// ExplanationHasSuffix applies the HasSuffix predicate on the "explanation" field.
func ExplanationHasSuffix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasSuffix(FieldExplanation, v))
}

// ExplanationEqualFold applies the EqualFold predicate on the "explanation" field.
func ExplanationEqualFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEqualFold(FieldExplanation, v))
}

// ExplanationContainsFold applies the ContainsFold predicate on the "explanation" field.
func ExplanationContainsFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContainsFold(FieldExplanation, v))
}

// ClientKeyEQ applies the EQ predicate on the "client_key" field.
func ClientKeyEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldClientKey, v))
}

// ClientKeyNEQ applies the NEQ predicate on the "client_key" field.
func ClientKeyNEQ(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNEQ(FieldClientKey, v))
}

// ClientKeyIn applies the In predicate on the "client_key" field.
func ClientKeyIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldIn(FieldClientKey, vs...))
}

// ClientKeyNotIn applies the NotIn predicate on the "client_key" field.
func ClientKeyNotIn(vs ...string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNotIn(FieldClientKey, vs...))
}

// ClientKeyGT applies the GT predicate on the "client_key" field.
func ClientKeyGT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGT(FieldClientKey, v))
}

// ClientKeyGTE applies the GTE predicate on the "client_key" field.
func ClientKeyGTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGTE(FieldClientKey, v))
}

// ClientKeyLT applies the LT predicate on the "client_key" field.
func ClientKeyLT(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLT(FieldClientKey, v))
}

// ClientKeyLTE applies the LTE predicate on the "client_key" field.
func ClientKeyLTE(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLTE(FieldClientKey, v))
}

// ClientKeyContains applies the Contains predicate on the "client_key" field.
func ClientKeyContains(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContains(FieldClientKey, v))
}

// ClientKeyHasPrefix applies the HasPrefix predicate on the "client_key" field.
func ClientKeyHasPrefix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasPrefix(FieldClientKey, v))
}

// ClientKeyHasSuffix applies the HasSuffix predicate on the "client_key" field.
func ClientKeyHasSuffix(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldHasSuffix(FieldClientKey, v))
}

// ClientKeyEqualFold applies the EqualFold predicate on the "client_key" field.
func ClientKeyEqualFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEqualFold(FieldClientKey, v))
}

// ClientKeyContainsFold applies the ContainsFold predicate on the "client_key" field.
func ClientKeyContainsFold(v string) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldContainsFold(FieldClientKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QuestQuestion) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QuestQuestion) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QuestQuestion) predicate.QuestQuestion {
	return predicate.QuestQuestion(sql.NotPredicates(p))
}
