// Code generated by ent, DO NOT EDIT.

package lessonevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/abhisek/mathiz/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLTE(FieldID, id))
}

// Sequence applies equality check predicate on the "sequence" field. It's identical to SequenceEQ.
func Sequence(v int64) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldSequence, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldTimestamp, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldOwnerID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldSessionID, v))
}

// SkillID applies equality check predicate on the "skill_id" field. It's identical to SkillIDEQ.
func SkillID(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldSkillID, v))
}

// LessonTitle applies equality check predicate on the "lesson_title" field. It's identical to LessonTitleEQ.
func LessonTitle(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldLessonTitle, v))
}

// PracticeAttempted applies equality check predicate on the "practice_attempted" field. It's identical to PracticeAttemptedEQ.
func PracticeAttempted(v bool) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldPracticeAttempted, v))
}

// PracticeCorrect applies equality check predicate on the "practice_correct" field. It's identical to PracticeCorrectEQ.
func PracticeCorrect(v bool) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldPracticeCorrect, v))
}

// PracticeSkipped applies equality check predicate on the "practice_skipped" field. It's identical to PracticeSkippedEQ.
func PracticeSkipped(v bool) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldPracticeSkipped, v))
}

// Explanation applies equality check predicate on the "explanation" field. It's identical to ExplanationEQ.
func Explanation(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldExplanation, v))
}

// WorkedExample applies equality check predicate on the "worked_example" field. It's identical to WorkedExampleEQ.
func WorkedExample(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldWorkedExample, v))
}

// PracticeText applies equality check predicate on the "practice_text" field. It's identical to PracticeTextEQ.
func PracticeText(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldPracticeText, v))
}

// PracticeAnswer applies equality check predicate on the "practice_answer" field. It's identical to PracticeAnswerEQ.
func PracticeAnswer(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldPracticeAnswer, v))
}

// PracticeExplanation applies equality check predicate on the "practice_explanation" field. It's identical to PracticeExplanationEQ.
func PracticeExplanation(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldPracticeExplanation, v))
}

// SequenceEQ applies the EQ predicate on the "sequence" field.
func SequenceEQ(v int64) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldSequence, v))
}

// SequenceNEQ applies the NEQ predicate on the "sequence" field.
func SequenceNEQ(v int64) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldSequence, v))
}

// SequenceIn applies the In predicate on the "sequence" field.
func SequenceIn(vs ...int64) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldIn(FieldSequence, vs...))
}

// SequenceNotIn applies the NotIn predicate on the "sequence" field.
func SequenceNotIn(vs ...int64) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNotIn(FieldSequence, vs...))
}

// SequenceGT applies the GT predicate on the "sequence" field.
func SequenceGT(v int64) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGT(FieldSequence, v))
}

// SequenceGTE applies the GTE predicate on the "sequence" field.
func SequenceGTE(v int64) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGTE(FieldSequence, v))
}

// SequenceLT applies the LT predicate on the "sequence" field.
func SequenceLT(v int64) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLT(FieldSequence, v))
}

// SequenceLTE applies the LTE predicate on the "sequence" field.
func SequenceLTE(v int64) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLTE(FieldSequence, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLTE(FieldTimestamp, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLTE(FieldOwnerID, v))
}

// OwnerIDContains applies the Contains predicate on the "owner_id" field.
func OwnerIDContains(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContains(FieldOwnerID, v))
}

// OwnerIDHasPrefix applies the HasPrefix predicate on the "owner_id" field.
func OwnerIDHasPrefix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasPrefix(FieldOwnerID, v))
}

// OwnerIDHasSuffix applies the HasSuffix predicate on the "owner_id" field.
func OwnerIDHasSuffix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasSuffix(FieldOwnerID, v))
}

// OwnerIDEqualFold applies the EqualFold predicate on the "owner_id" field.
func OwnerIDEqualFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEqualFold(FieldOwnerID, v))
}

// OwnerIDContainsFold applies the ContainsFold predicate on the "owner_id" field.
func OwnerIDContainsFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContainsFold(FieldOwnerID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContainsFold(FieldSessionID, v))
}

// SkillIDEQ applies the EQ predicate on the "skill_id" field.
func SkillIDEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldSkillID, v))
}

// SkillIDNEQ applies the NEQ predicate on the "skill_id" field.
func SkillIDNEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldSkillID, v))
}

// SkillIDIn applies the In predicate on the "skill_id" field.
func SkillIDIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldIn(FieldSkillID, vs...))
}

// SkillIDNotIn applies the NotIn predicate on the "skill_id" field.
func SkillIDNotIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNotIn(FieldSkillID, vs...))
}

// SkillIDGT applies the GT predicate on the "skill_id" field.
func SkillIDGT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGT(FieldSkillID, v))
}

// SkillIDGTE applies the GTE predicate on the "skill_id" field.
func SkillIDGTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGTE(FieldSkillID, v))
}

// SkillIDLT applies the LT predicate on the "skill_id" field.
func SkillIDLT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLT(FieldSkillID, v))
}

// SkillIDLTE applies the LTE predicate on the "skill_id" field.
func SkillIDLTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLTE(FieldSkillID, v))
}

// SkillIDContains applies the Contains predicate on the "skill_id" field.
func SkillIDContains(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContains(FieldSkillID, v))
}

// SkillIDHasPrefix applies the HasPrefix predicate on the "skill_id" field.
func SkillIDHasPrefix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasPrefix(FieldSkillID, v))
}

// SkillIDHasSuffix applies the HasSuffix predicate on the "skill_id" field.
func SkillIDHasSuffix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasSuffix(FieldSkillID, v))
}

// SkillIDEqualFold applies the EqualFold predicate on the "skill_id" field.
func SkillIDEqualFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEqualFold(FieldSkillID, v))
}

// SkillIDContainsFold applies the ContainsFold predicate on the "skill_id" field.
func SkillIDContainsFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContainsFold(FieldSkillID, v))
}

// LessonTitleEQ applies the EQ predicate on the "lesson_title" field.
func LessonTitleEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldLessonTitle, v))
}

// LessonTitleNEQ applies the NEQ predicate on the "lesson_title" field.
func LessonTitleNEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldLessonTitle, v))
}

// LessonTitleIn applies the In predicate on the "lesson_title" field.
func LessonTitleIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldIn(FieldLessonTitle, vs...))
}

// LessonTitleNotIn applies the NotIn predicate on the "lesson_title" field.
func LessonTitleNotIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNotIn(FieldLessonTitle, vs...))
}

// LessonTitleGT applies the GT predicate on the "lesson_title" field.
func LessonTitleGT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGT(FieldLessonTitle, v))
}

// LessonTitleGTE applies the GTE predicate on the "lesson_title" field.
func LessonTitleGTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGTE(FieldLessonTitle, v))
}

// LessonTitleLT applies the LT predicate on the "lesson_title" field.
func LessonTitleLT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLT(FieldLessonTitle, v))
}

// LessonTitleLTE applies the LTE predicate on the "lesson_title" field.
func LessonTitleLTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLTE(FieldLessonTitle, v))
}

// LessonTitleContains applies the Contains predicate on the "lesson_title" field.
func LessonTitleContains(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContains(FieldLessonTitle, v))
}

// LessonTitleHasPrefix applies the HasPrefix predicate on the "lesson_title" field.
func LessonTitleHasPrefix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasPrefix(FieldLessonTitle, v))
}

// LessonTitleHasSuffix applies the HasSuffix predicate on the "lesson_title" field.
func LessonTitleHasSuffix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasSuffix(FieldLessonTitle, v))
}

// LessonTitleEqualFold applies the EqualFold predicate on the "lesson_title" field.
func LessonTitleEqualFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEqualFold(FieldLessonTitle, v))
}

// LessonTitleContainsFold applies the ContainsFold predicate on the "lesson_title" field.
func LessonTitleContainsFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContainsFold(FieldLessonTitle, v))
}

// PracticeAttemptedEQ applies the EQ predicate on the "practice_attempted" field.
func PracticeAttemptedEQ(v bool) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldPracticeAttempted, v))
}

// PracticeAttemptedNEQ applies the NEQ predicate on the "practice_attempted" field.
func PracticeAttemptedNEQ(v bool) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldPracticeAttempted, v))
}

// PracticeCorrectEQ applies the EQ predicate on the "practice_correct" field.
func PracticeCorrectEQ(v bool) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldPracticeCorrect, v))
}

// PracticeCorrectNEQ applies the NEQ predicate on the "practice_correct" field.
func PracticeCorrectNEQ(v bool) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldPracticeCorrect, v))
}

// PracticeSkippedEQ applies the EQ predicate on the "practice_skipped" field.
func PracticeSkippedEQ(v bool) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldPracticeSkipped, v))
}

// PracticeSkippedNEQ applies the NEQ predicate on the "practice_skipped" field.
func PracticeSkippedNEQ(v bool) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldPracticeSkipped, v))
}

// ExplanationEQ applies the EQ predicate on the "explanation" field.
func ExplanationEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldExplanation, v))
}

// ExplanationNEQ applies the NEQ predicate on the "explanation" field.
func ExplanationNEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldExplanation, v))
}

// ExplanationIn applies the In predicate on the "explanation" field.
func ExplanationIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldIn(FieldExplanation, vs...))
}

// ExplanationNotIn applies the NotIn predicate on the "explanation" field.
func ExplanationNotIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNotIn(FieldExplanation, vs...))
}

// ExplanationGT applies the GT predicate on the "explanation" field.
func ExplanationGT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGT(FieldExplanation, v))
}

// ExplanationGTE applies the GTE predicate on the "explanation" field.
func ExplanationGTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGTE(FieldExplanation, v))
}

// ExplanationLT applies the LT predicate on the "explanation" field.
func ExplanationLT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLT(FieldExplanation, v))
}

// ExplanationLTE applies the LTE predicate on the "explanation" field.
func ExplanationLTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLTE(FieldExplanation, v))
}

// ExplanationContains applies the Contains predicate on the "explanation" field.
func ExplanationContains(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContains(FieldExplanation, v))
}

// ExplanationHasPrefix applies the HasPrefix predicate on the "explanation" field.
func ExplanationHasPrefix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasPrefix(FieldExplanation, v))
}

// ExplanationHasSuffix applies the HasSuffix predicate on the "explanation" field.
func ExplanationHasSuffix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasSuffix(FieldExplanation, v))
}

// ExplanationEqualFold applies the EqualFold predicate on the "explanation" field.
func ExplanationEqualFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEqualFold(FieldExplanation, v))
}

// ExplanationContainsFold applies the ContainsFold predicate on the "explanation" field.
func ExplanationContainsFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContainsFold(FieldExplanation, v))
}

// WorkedExampleEQ applies the EQ predicate on the "worked_example" field.
func WorkedExampleEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldWorkedExample, v))
}

// WorkedExampleNEQ applies the NEQ predicate on the "worked_example" field.
func WorkedExampleNEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldWorkedExample, v))
}

// WorkedExampleIn applies the In predicate on the "worked_example" field.
func WorkedExampleIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldIn(FieldWorkedExample, vs...))
}

// WorkedExampleNotIn applies the NotIn predicate on the "worked_example" field.
func WorkedExampleNotIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNotIn(FieldWorkedExample, vs...))
}

// WorkedExampleGT applies the GT predicate on the "worked_example" field.
func WorkedExampleGT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGT(FieldWorkedExample, v))
}

// WorkedExampleGTE applies the GTE predicate on the "worked_example" field.
func WorkedExampleGTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGTE(FieldWorkedExample, v))
}

// WorkedExampleLT applies the LT predicate on the "worked_example" field.
func WorkedExampleLT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLT(FieldWorkedExample, v))
}

// WorkedExampleLTE applies the LTE predicate on the "worked_example" field.
func WorkedExampleLTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLTE(FieldWorkedExample, v))
}

// WorkedExampleContains applies the Contains predicate on the "worked_example" field.
func WorkedExampleContains(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContains(FieldWorkedExample, v))
}

// WorkedExampleHasPrefix applies the HasPrefix predicate on the "worked_example" field.
func WorkedExampleHasPrefix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasPrefix(FieldWorkedExample, v))
}

// WorkedExampleHasSuffix applies the HasSuffix predicate on the "worked_example" field.
func WorkedExampleHasSuffix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasSuffix(FieldWorkedExample, v))
}

// WorkedExampleEqualFold applies the EqualFold predicate on the "worked_example" field.
func WorkedExampleEqualFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEqualFold(FieldWorkedExample, v))
}

// WorkedExampleContainsFold applies the ContainsFold predicate on the "worked_example" field.
func WorkedExampleContainsFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContainsFold(FieldWorkedExample, v))
}

// PracticeTextEQ applies the EQ predicate on the "practice_text" field.
func PracticeTextEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldPracticeText, v))
}

// PracticeTextNEQ applies the NEQ predicate on the "practice_text" field.
func PracticeTextNEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldPracticeText, v))
}

// PracticeTextIn applies the In predicate on the "practice_text" field.
func PracticeTextIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldIn(FieldPracticeText, vs...))
}

// PracticeTextNotIn applies the NotIn predicate on the "practice_text" field.
func PracticeTextNotIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNotIn(FieldPracticeText, vs...))
}

// PracticeTextGT applies the GT predicate on the "practice_text" field.
func PracticeTextGT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGT(FieldPracticeText, v))
}

// PracticeTextGTE applies the GTE predicate on the "practice_text" field.
func PracticeTextGTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGTE(FieldPracticeText, v))
}

// PracticeTextLT applies the LT predicate on the "practice_text" field.
func PracticeTextLT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLT(FieldPracticeText, v))
}

// PracticeTextLTE applies the LTE predicate on the "practice_text" field.
func PracticeTextLTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLTE(FieldPracticeText, v))
}

// PracticeTextContains applies the Contains predicate on the "practice_text" field.
func PracticeTextContains(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContains(FieldPracticeText, v))
}

// PracticeTextHasPrefix applies the HasPrefix predicate on the "practice_text" field.
func PracticeTextHasPrefix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasPrefix(FieldPracticeText, v))
}

// PracticeTextHasSuffix applies the HasSuffix predicate on the "practice_text" field.
func PracticeTextHasSuffix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasSuffix(FieldPracticeText, v))
}

// PracticeTextEqualFold applies the EqualFold predicate on the "practice_text" field.
func PracticeTextEqualFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEqualFold(FieldPracticeText, v))
}

// PracticeTextContainsFold applies the ContainsFold predicate on the "practice_text" field.
func PracticeTextContainsFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContainsFold(FieldPracticeText, v))
}

// PracticeAnswerEQ applies the EQ predicate on the "practice_answer" field.
func PracticeAnswerEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldPracticeAnswer, v))
}

// PracticeAnswerNEQ applies the NEQ predicate on the "practice_answer" field.
func PracticeAnswerNEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldPracticeAnswer, v))
}

// PracticeAnswerIn applies the In predicate on the "practice_answer" field.
func PracticeAnswerIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldIn(FieldPracticeAnswer, vs...))
}

// PracticeAnswerNotIn applies the NotIn predicate on the "practice_answer" field.
func PracticeAnswerNotIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNotIn(FieldPracticeAnswer, vs...))
}

// PracticeAnswerGT applies the GT predicate on the "practice_answer" field.
func PracticeAnswerGT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGT(FieldPracticeAnswer, v))
}

// PracticeAnswerGTE applies the GTE predicate on the "practice_answer" field.
func PracticeAnswerGTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGTE(FieldPracticeAnswer, v))
}

// PracticeAnswerLT applies the LT predicate on the "practice_answer" field.
func PracticeAnswerLT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLT(FieldPracticeAnswer, v))
}

// PracticeAnswerLTE applies the LTE predicate on the "practice_answer" field.
func PracticeAnswerLTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLTE(FieldPracticeAnswer, v))
}

// PracticeAnswerContains applies the Contains predicate on the "practice_answer" field.
func PracticeAnswerContains(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContains(FieldPracticeAnswer, v))
}

// PracticeAnswerHasPrefix applies the HasPrefix predicate on the "practice_answer" field.
func PracticeAnswerHasPrefix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasPrefix(FieldPracticeAnswer, v))
}

// PracticeAnswerHasSuffix applies the HasSuffix predicate on the "practice_answer" field.
func PracticeAnswerHasSuffix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasSuffix(FieldPracticeAnswer, v))
}

// PracticeAnswerEqualFold applies the EqualFold predicate on the "practice_answer" field.
func PracticeAnswerEqualFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEqualFold(FieldPracticeAnswer, v))
}

// PracticeAnswerContainsFold applies the ContainsFold predicate on the "practice_answer" field.
func PracticeAnswerContainsFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContainsFold(FieldPracticeAnswer, v))
}

// PracticeExplanationEQ applies the EQ predicate on the "practice_explanation" field.
func PracticeExplanationEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEQ(FieldPracticeExplanation, v))
}

// PracticeExplanationNEQ applies the NEQ predicate on the "practice_explanation" field.
func PracticeExplanationNEQ(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNEQ(FieldPracticeExplanation, v))
}

// PracticeExplanationIn applies the In predicate on the "practice_explanation" field.
func PracticeExplanationIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldIn(FieldPracticeExplanation, vs...))
}

// PracticeExplanationNotIn applies the NotIn predicate on the "practice_explanation" field.
func PracticeExplanationNotIn(vs ...string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldNotIn(FieldPracticeExplanation, vs...))
}

// PracticeExplanationGT applies the GT predicate on the "practice_explanation" field.
func PracticeExplanationGT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGT(FieldPracticeExplanation, v))
}

// PracticeExplanationGTE applies the GTE predicate on the "practice_explanation" field.
func PracticeExplanationGTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldGTE(FieldPracticeExplanation, v))
}

// PracticeExplanationLT applies the LT predicate on the "practice_explanation" field.
func PracticeExplanationLT(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLT(FieldPracticeExplanation, v))
}

// PracticeExplanationLTE applies the LTE predicate on the "practice_explanation" field.
func PracticeExplanationLTE(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldLTE(FieldPracticeExplanation, v))
}

// PracticeExplanationContains applies the Contains predicate on the "practice_explanation" field.
func PracticeExplanationContains(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContains(FieldPracticeExplanation, v))
}

// PracticeExplanationHasPrefix applies the HasPrefix predicate on the "practice_explanation" field.
func PracticeExplanationHasPrefix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasPrefix(FieldPracticeExplanation, v))
}

// PracticeExplanationHasSuffix applies the HasSuffix predicate on the "practice_explanation" field.
func PracticeExplanationHasSuffix(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldHasSuffix(FieldPracticeExplanation, v))
}

// PracticeExplanationEqualFold applies the EqualFold predicate on the "practice_explanation" field.
func PracticeExplanationEqualFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldEqualFold(FieldPracticeExplanation, v))
}

// PracticeExplanationContainsFold applies the ContainsFold predicate on the "practice_explanation" field.
func PracticeExplanationContainsFold(v string) predicate.LessonEvent {
	return predicate.LessonEvent(sql.FieldContainsFold(FieldPracticeExplanation, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LessonEvent) predicate.LessonEvent {
	return predicate.LessonEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LessonEvent) predicate.LessonEvent {
	return predicate.LessonEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LessonEvent) predicate.LessonEvent {
	return predicate.LessonEvent(sql.NotPredicates(p))
}
