// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// AnswerEvent is the predicate function for answerevent builders.
type AnswerEvent func(*sql.Selector)

// BillingState is the predicate function for billingstate builders.
type BillingState func(*sql.Selector)

// ChildProfile is the predicate function for childprofile builders.
type ChildProfile func(*sql.Selector)

// CreditEntry is the predicate function for creditentry builders.
type CreditEntry func(*sql.Selector)

// DeviceToken is the predicate function for devicetoken builders.
type DeviceToken func(*sql.Selector)

// DiagnosisEvent is the predicate function for diagnosisevent builders.
type DiagnosisEvent func(*sql.Selector)

// FamilySpace is the predicate function for familyspace builders.
type FamilySpace func(*sql.Selector)

// GemEvent is the predicate function for gemevent builders.
type GemEvent func(*sql.Selector)

// HintEvent is the predicate function for hintevent builders.
type HintEvent func(*sql.Selector)

// Invite is the predicate function for invite builders.
type Invite func(*sql.Selector)

// LLMRequestEvent is the predicate function for llmrequestevent builders.
type LLMRequestEvent func(*sql.Selector)

// LessonEvent is the predicate function for lessonevent builders.
type LessonEvent func(*sql.Selector)

// MasteryEvent is the predicate function for masteryevent builders.
type MasteryEvent func(*sql.Selector)

// Quest is the predicate function for quest builders.
type Quest func(*sql.Selector)

// QuestProgress is the predicate function for questprogress builders.
type QuestProgress func(*sql.Selector)

// QuestQuestion is the predicate function for questquestion builders.
type QuestQuestion func(*sql.Selector)

// SessionEvent is the predicate function for sessionevent builders.
type SessionEvent func(*sql.Selector)

// Snapshot is the predicate function for snapshot builders.
type Snapshot func(*sql.Selector)
